// Class: ReadBDT
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.10/04       [395780]
Creator        : marine5575
Date           : Wed Oct  9 17:31:07 2019
Host           : Linux htop.hanyang.ac.kr 2.6.32-696.el6.centos.plus.x86_64 #1 SMP Mon Apr 3 14:56:08 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/marine5575/work/Undergrad2018/mva
Training events: 65134
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "100" [Number of trees in the forest]
MaxDepth: "3" [Max depth of the decision tree allowed]
MinNodeSize: "5%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
nCuts: "30" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "Grad" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
Shrinkage: "5.000000e-01" [Learning rate for GradBoost algorithm]
SeparationType: "giniindex" [Separation criterion for node splitting]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
UseBaggedBoost: "False" [Use only a random subsample of all events for growing the trees in each boost iteration.]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "3" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Poisson distribution in each split with RandomisedTree option]
BaggedSampleFraction: "6.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "pray" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in training sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
RegressionLossFunctionBDTG: "huber" [Loss function for BDTG regression.]
HuberQuantile: "7.000000e-01" [In the Huber loss function this is the quantile that separates the core from the tails in the residuals distribution.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
SkipNormalization: "False" [Skip normalization at initialization, to keep expectation value of BDT output according to the fraction of events]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "6.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 11
lepton1_pt                    lepton1_pt                    lepton1_pt                    lepton1_pt                                                      'F'    [30.0022735596,875.963500977]
met_pt                        met_pt                        met_pt                        met_pt                                                          'F'    [0.174064293504,815.994018555]
tau1_pt                       tau1_pt                       tau1_pt                       tau1_pt                                                         'F'    [30.0001525879,1040.04150391]
jet_ht                        jet_ht                        jet_ht                        jet_ht                                                          'F'    [95.0174484253,3019.39990234]
jetlepmet_ht                  jetlepmet_ht                  jetlepmet_ht                  jetlepmet_ht                                                    'F'    [155.10949707,3288.48583984]
lep1met_pt                    lep1met_pt                    lep1met_pt                    lep1met_pt                                                      'F'    [0.211814135313,879.103881836]
lep1tau1_pt                   lep1tau1_pt                   lep1tau1_pt                   lep1tau1_pt                                                     'F'    [0.17061945796,1256.81884766]
tau1_lep1_dr                  tau1_lep1_dr                  tau1_lep1_dr                  tau1_lep1_dr                                                    'F'    [0.390903234482,5.5550994873]
lep1_met_dphi                 lep1_met_dphi                 lep1_met_dphi                 lep1_met_dphi                                                   'F'    [-3.14144611359,3.14149641991]
tau1_met_dphi                 tau1_met_dphi                 tau1_met_dphi                 tau1_met_dphi                                                   'F'    [-3.14148163795,3.14157342911]
tau1lep1_met_dphi             tau1lep1_met_dphi             tau1lep1_met_dphi             tau1lep1_met_dphi                                               'F'    [-3.14146351814,3.14153146744]
NSpec 2
njet                          njet                          njet                          njet                                                            'F'    [3,12]
nbjet                         nbjet                         nbjet                         nbjet                                                           'F'    [0,6]


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDTNode
   
#ifndef BDTNode__def
#define BDTNode__def
   
class BDTNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDTNode ( BDTNode* left,BDTNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDTNode();

   // test event if it descends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDTNode* GetRight( void )  {return fRight; };

   // test event if it descends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDTNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDTNode*   fLeft;     // pointer to the left daughter node
   BDTNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value applied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDTNode::~BDTNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDTNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDTNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT : public IClassifierReader {

 public:

   // constructor
   ReadBDT( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDT" ),
        fNvars( 11 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "lepton1_pt", "met_pt", "tau1_pt", "jet_ht", "jetlepmet_ht", "lep1met_pt", "lep1tau1_pt", "tau1_lep1_dr", "lep1_met_dphi", "tau1_met_dphi", "tau1lep1_met_dphi" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;
      fVmin[8] = 0;
      fVmax[8] = 0;
      fVmin[9] = 0;
      fVmax[9] = 0;
      fVmin[10] = 0;
      fVmax[10] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[11];
   double fVmax[11];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[11];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDTNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDTNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDTNode*)current->GetRight();
         else current=(BDTNode*)current->GetLeft();
      }
      myMVA += current->GetResponse();
   }
   return 2.0/(1.0+exp(-2.0*myMVA))-1.0;
};

void ReadBDT::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.80759,0.266708) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.692225,0.173319) , 
7, 1.64752, 1, 0, 0.735261,0.235261) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.620991,0.111843) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.458122,-0.0410808) , 
7, 1.89019, 1, 0, 0.529438,0.0294377) , 
1, 29.0361, 1, 0, 0.63626,0.13626) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.51555,0.0149317) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.392431,-0.108193) , 
1, 77.4313, 1, 0, 0.446695,-0.0533048) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.350554,-0.152779) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.17793,-0.353128) , 
5, 114.242, 1, 0, 0.263719,-0.236281) , 
7, 1.55733, 1, 0, 0.31414,-0.18586) , 
1, 52.8076, 1, 0, 0.5,-1.547e-15)    );
  // itree = 1
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.735637,0.138867) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.599599,0.0100781) , 
4, 531.754, 1, 0, 0.711242,0.125445) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.548429,0.0333849) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.404253,-0.10759) , 
9, 0.912182, 1, 0, 0.504308,-0.00842152) , 
1, 34.1294, 1, 0, 0.63626,0.0769389) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.424232,-0.0149091) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.276216,-0.125888) , 
7, 2.22015, 1, 0, 0.35021,-0.0637069) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.185862,-0.215268) , 
5, 170.898, 1, 0, 0.31414,-0.0893773) , 
1, 52.8076, 1, 0, 0.5,0.00658569)    );
  // itree = 2
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.811381,0.141815) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.745408,0.0813079) , 
1, 19.6977, 1, 0, 0.788372,0.122895) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.680792,0.03753) , 
7, 2.27061, 1, 0, 0.74603,0.0894708) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.411752,-0.0404143) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.289168,-0.145616) , 
3, 285.017, 1, 0, 0.340763,-0.0893719) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.569598,0.105084) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.349826,-0.0718727) , 
9, 0.657197, 1, 0, 0.449188,0.0124682) , 
9, -0.709331, 1, 0, 0.411658,-0.0227821) , 
1, 26.4908, 1, 0, 0.5,0.00687538)    );
  // itree = 3
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.416142,-0.105447) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.525384,-0.00681069) , 
9, -0.912153, 1, 0, 0.490288,-0.0350535) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.685275,0.11043) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.468342,0.0326303) , 
5, 99.0951, 1, 0, 0.640602,0.0938177) , 
2, 42.6692, 1, 0, 0.581632,0.0432601) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.461941,-0.0292223) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.604556,0.0797186) , 
6, 119.252, 1, 0, 0.55449,0.0414295) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.300038,-0.100855) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.215943,-0.191228) , 
3, 499.975, 1, 0, 0.270442,-0.10627) , 
7, 1.81428, 1, 0, 0.393672,-0.0421927) , 
4, 458.339, 1, 0, 0.5,0.00614743)    );
  // itree = 4
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.506675,-0.0255991) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.617953,0.0491771) , 
9, -1.31725, 1, 0, 0.590615,0.0297549) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.351422,-0.00616128) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.19249,-0.102593) , 
5, 142.937, 1, 0, 0.272424,-0.0370633) , 
1, 79.1244, 1, 0, 0.517446,0.0143898) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.300521,-0.122519) , 
7, 3.22288, 1, 0, 0.5,0.00526994)    );
  // itree = 5
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.673153,0.0823343) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.508657,-0.0241692) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.680725,0.0712681) , 
2, 38.9466, 1, 0, 0.622119,0.0368619) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.502989,-0.00281202) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.322486,-0.0578381) , 
7, 2.39534, 1, 0, 0.423979,-0.0212374) , 
4, 348.459, 1, 0, 0.48124,-0.00444697) , 
7, 0.890664, 1, 0, 0.5,0.00371853)    );
  // itree = 6
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.657832,0.0220136) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.30285,-0.0467874) , 
1, 39.6686, 1, 0, 0.458198,-0.0115489) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.664975,0.0901505) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.544981,0.00797136) , 
9, 0.384077, 1, 0, 0.617431,0.0548648) , 
9, -0.395531, 1, 0, 0.526632,0.0169939) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.332056,-0.12347) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.51597,0.00815067) , 
2, 40.5222, 1, 0, 0.406825,-0.0569898) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.437771,-0.0253689) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.515664,0.0345156) , 
10, 2.12784, 1, 0, 0.468621,-0.000794242) , 
2, 59.6588, 1, 0, 0.434326,-0.0319819) , 
9, 1.11478, 1, 0, 0.5,0.00286352)    );
  // itree = 7
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.459872,-0.0172692) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.326551,-0.111549) , 
3, 314.114, 1, 0, 0.41913,-0.037692) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.610679,0.0509333) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.51437,0.00601594) , 
9, 1.31742, 1, 0, 0.585706,0.0347475) , 
2, 40.2457, 1, 0, 0.530677,0.0108167) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.581469,0.00896674) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.245622,-0.102013) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.289195,-0.0488433) , 
2, 61.5136, 1, 0, 0.268793,-0.0522612) , 
7, 1.33982, 1, 0, 0.368006,-0.0329967) , 
3, 472.357, 1, 0, 0.5,0.00255431)    );
  // itree = 8
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.820733,0.0967609) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.754885,0.0403095) , 
5, 58.5584, 1, 0, 0.785138,0.0564419) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.733707,0.0155951) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.685721,-0.0278513) , 
1, 21.5602, 1, 0, 0.710459,-0.0047554) , 
1, 16.3023, 1, 0, 0.74603,0.0243941) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.422788,0.0340654) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.365026,-0.0437631) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.42373,-0.00390329) , 
10, -0.918402, 1, 0, 0.410116,-0.0108909) , 
10, -2.33066, 1, 0, 0.411658,-0.00596272) , 
1, 26.4908, 1, 0, 0.5,0.00205763)    );
  // itree = 9
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.690054,0.0566812) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.592217,-0.0280455) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.686507,0.0237911) , 
9, -1.72268, 1, 0, 0.668766,0.0123065) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.434781,0.0293837) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.325426,-0.0233878) , 
8, -2.33076, 1, 0, 0.337861,-0.0128678) , 
1, 41.5261, 1, 0, 0.488669,-0.00139474) , 
7, 0.724077, 1, 0, 0.5,0.00156739)    );
  // itree = 10
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.469704,-0.00340411) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.630122,0.0335783) , 
9, -0.3957, 1, 0, 0.539217,0.011316) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.42125,0.00226976) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.483427,-0.0479751) , 
8, 0.506714, 1, 0, 0.444581,-0.0141007) , 
9, 1.11478, 1, 0, 0.512099,0.00403285) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.277381,-0.0697503) , 
7, 3.38947, 1, 0, 0.5,0.00128345)    );
  // itree = 11
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.405087,-0.0284386) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.548351,0.0441618) , 
2, 39.3869, 1, 0, 0.429063,-0.0130023) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.642695,0.0294207) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.46183,-0.00109076) , 
7, 2.38025, 1, 0, 0.570818,0.014926) , 
2, 42.6532, 1, 0, 0.519391,0.00479396) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.409767,-0.0171627) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.274845,-0.0707173) , 
4, 868.356, 1, 0, 0.342144,-0.0303964) , 
3, 566.692, 1, 0, 0.5,0.000944057)    );
  // itree = 12
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.6007,0.0454299) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.28041,-0.00721243) , 
5, 72.5475, 1, 0, 0.457391,0.0208683) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.554064,0.000135443) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.339742,-0.038156) , 
7, 2.5878, 1, 0, 0.506896,-0.00601567) , 
6, 40.7077, 1, 0, 0.498742,-0.00158781) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.518465,0.0426603) , 
10, 2.73618, 1, 0, 0.5,0.000852814)    );
  // itree = 13
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.502661,-0.0233494) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.448644,0.0112716) , 
8, -0.304029, 1, 0, 0.470262,-0.00246377) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.741732,0.0768454) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.565129,-0.00694839) , 
7, 2.24977, 1, 0, 0.67501,0.0392932) , 
9, -0.251726, 1, 0, 0.519085,0.0074933) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.530616,-0.00135636) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.582503,0.0300146) , 
10, 1.92562, 1, 0, 0.546231,0.00726969) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.584832,-0.00703481) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.230864,-0.0552623) , 
1, 53.0022, 1, 0, 0.424087,-0.0197037) , 
3, 276.87, 1, 0, 0.474413,-0.00859009) , 
9, 0.304065, 1, 0, 0.5,0.000622153)    );
  // itree = 14
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.690054,0.0308459) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.793768,0.0426786) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.702567,-0.0194531) , 
0, 73.1165, 1, 0, 0.761775,0.0159896) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.432382,-0.00877491) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.373682,0.0245835) , 
2, 124.54, 1, 0, 0.426516,-0.00464057) , 
1, 20.8501, 1, 0, 0.488669,-0.000815948) , 
7, 0.724077, 1, 0, 0.5,0.000722598)    );
  // itree = 15
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.514,0.0207001) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.570989,-0.0196963) , 
6, 56.0124, 1, 0, 0.54841,-0.00300565) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.719478,0.0795803) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.479941,0.00457391) , 
7, 1.49787, 1, 0, 0.544343,0.0214582) , 
0, 70.2362, 1, 0, 0.547023,0.00533527) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.620947,0.017764) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.461297,-0.0236762) , 
5, 106.111, 1, 0, 0.545446,-0.000803172) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.286138,-0.0620829) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.255045,-0.00765619) , 
8, -0.912035, 1, 0, 0.264506,-0.0170599) , 
7, 1.97243, 1, 0, 0.40535,-0.00890989) , 
3, 378.022, 1, 0, 0.5,0.000607102)    );
  // itree = 16
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.508112,-0.0087044) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.473487,0.028422) , 
8, -0.657051, 1, 0, 0.494453,0.00377034) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.477426,-0.0325342) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.557736,0.00253001) , 
8, 1.84699, 1, 0, 0.522684,-0.0101021) , 
8, 0.912065, 1, 0, 0.504406,-0.00112058) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.436984,0.0333632) , 
0, 139.159, 1, 0, 0.5,0.000587055)    );
  // itree = 17
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.56586,0.0215133) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.798519,0.0397774) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.489085,-0.00343771) , 
1, 12.8175, 1, 0, 0.516274,6.6777e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.214877,-0.0414132) , 
5, 199.152, 1, 0, 0.493264,-0.00162665) , 
8, -2.53342, 1, 0, 0.5,0.000310855)    );
  // itree = 18
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.594454,0.0137247) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.504251,-0.0170092) , 
9, 1.52019, 1, 0, 0.57416,0.00580738) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.383965,-0.0337961) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.186139,0.011342) , 
7, 2.19875, 1, 0, 0.303439,-0.0127599) , 
5, 141.969, 1, 0, 0.525342,0.00245925) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.455421,-0.0327914) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.239715,0.00278147) , 
5, 84.478, 1, 0, 0.343863,-0.012622) , 
7, 3.05629, 1, 0, 0.5,0.000353249)    );
  // itree = 19
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.464067,0.0341183) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.460737,0.0029007) , 
6, 21.745, 1, 0, 0.462469,0.014995) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.458984,-0.0177766) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.546365,0.00215912) , 
9, -0.506676, 1, 0, 0.513027,-0.0042986) , 
6, 32.0202, 1, 0, 0.506753,-0.00190466) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.59069,-0.00990685) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.297997,0.0674094) , 
1, 53.1482, 1, 0, 0.45375,0.0153798) , 
0, 111.869, 1, 0, 0.5,0.000297619)    );
  // itree = 20
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.607428,0.00422245) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.641804,0.0457957) , 
0, 83.6433, 1, 0, 0.611793,0.00835926) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.367505,0.038297) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.38413,-0.0252177) , 
10, -1.11406, 1, 0, 0.380787,-0.00937596) , 
5, 105.623, 1, 0, 0.534549,0.00242889) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.54079,-0.00584493) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.304415,-0.0564886) , 
4, 420.516, 1, 0, 0.447371,-0.0203261) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.212516,0.026456) , 
5, 113.912, 1, 0, 0.368359,-0.00888484) , 
7, 2.88971, 1, 0, 0.5,7.69227e-05)    );
  // itree = 21
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.437972,-0.0721264) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.531731,-0.00033841) , 
9, -0.708856, 1, 0, 0.504137,-0.017767) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.629178,0.0332752) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.421858,-0.0235868) , 
7, 2.21781, 1, 0, 0.531147,0.00646049) , 
0, 58.7687, 1, 0, 0.517234,-0.00601916) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.592087,0.0255576) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.274586,-0.015319) , 
5, 142.57, 1, 0, 0.494294,0.0116588) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.483927,-0.0184351) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.494554,0.0173334) , 
10, 2.27855, 1, 0, 0.48713,-0.00590805) , 
10, 0.709404, 1, 0, 0.490934,0.00341897) , 
8, -0.912015, 1, 0, 0.5,0.000165432)    );
  // itree = 22
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.508462,0.0131128) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.426911,0.0126992) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.461921,-0.0211495) , 
6, 52.2484, 1, 0, 0.45252,-0.00936984) , 
10, -2.12808, 1, 0, 0.465252,-0.00472616) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.761929,0.0622702) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.584989,0.00124146) , 
7, 1.94136, 1, 0, 0.67726,0.0268419) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.461254,0.0062645) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.529734,-0.0127871) , 
8, 0.304038, 1, 0, 0.489366,-0.00144376) , 
9, 0.140618, 1, 0, 0.525601,0.00401103) , 
9, -0.303973, 1, 0, 0.5,0.000304591)    );
  // itree = 23
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.617349,0.0122512) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.561346,-0.0306414) , 
9, 1.92515, 1, 0, 0.608646,0.00470875) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.418525,0.0386321) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.420655,-0.0124074) , 
10, -2.12776, 1, 0, 0.420434,-0.00521136) , 
5, 72.2416, 1, 0, 0.504406,-0.000785424) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.436984,0.0207459) , 
0, 139.159, 1, 0, 0.5,0.000297439)    );
  // itree = 24
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.518536,-0.000760048) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.542701,-0.0246584) , 
6, 61.6638, 1, 0, 0.534444,-0.0141224) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.28467,0.0266631) , 
1, 77.1117, 1, 0, 0.475843,-0.00657531) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.407026,-0.0196498) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.594032,0.0183532) , 
2, 40.0065, 1, 0, 0.535038,0.00528159) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.29638,-0.0245324) , 
4, 764.75, 1, 0, 0.510179,0.00308946) , 
10, -1.11469, 1, 0, 0.5,0.000224423)    );
  // itree = 25
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.612671,-0.02451) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.708976,0.0620715) , 
0, 73.129, 1, 0, 0.654402,0.011618) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.595802,0.00436561) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.368588,-0.0149162) , 
5, 78.6631, 1, 0, 0.48184,-0.00352443) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.395618,0.0231509) , 
2, 124.54, 1, 0, 0.474082,-0.00170568) , 
7, 1.05725, 1, 0, 0.5,0.000209363)    );
  // itree = 26
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.451752,0.00262442) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.275013,-0.0583338) , 
3, 343.815, 1, 0, 0.392972,-0.0113751) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.742635,0.063438) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.553449,0.0059293) , 
7, 1.06133, 1, 0, 0.581072,0.0115508) , 
2, 40.5103, 1, 0, 0.507101,0.00253512) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.609689,-0.0433336) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.387333,0.0211431) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.413899,-0.0137224) , 
8, 0.506645, 1, 0, 0.398075,0.00474329) , 
7, 1.48425, 1, 0, 0.46989,-0.00925195) , 
2, 95.1641, 1, 0, 0.5,0.000285789)    );
  // itree = 27
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.590566,-0.0025375) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.381183,-0.0290477) , 
5, 69.6925, 1, 0, 0.513324,-0.00960956) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.531411,0.0123743) , 
0, 87.5352, 1, 0, 0.517234,-0.00531416) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.508827,0.0446859) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.404834,-0.00890945) , 
0, 65.1257, 1, 0, 0.456879,0.0132751) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.513502,-0.0103117) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.514412,0.0158978) , 
0, 84.5827, 1, 0, 0.51372,-0.00323423) , 
8, 0.657121, 1, 0, 0.490934,0.00338408) , 
8, -0.912015, 1, 0, 0.5,0.000385601)    );
  // itree = 28
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.398654,-0.0208067) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.566858,0.0115868) , 
2, 34.2041, 1, 0, 0.539407,0.00511368) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.489541,0.00477721) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.532908,-0.0265669) , 
6, 144.544, 1, 0, 0.513121,-0.0100724) , 
2, 95.1641, 1, 0, 0.534549,0.00230677) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.307272,0.00884892) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.448247,-0.0360319) , 
9, -1.44169, 1, 0, 0.391077,-0.0152443) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.324907,0.0108376) , 
9, 0.911899, 1, 0, 0.368359,-0.00752695) , 
7, 2.88971, 1, 0, 0.5,0.000262472)    );
  // itree = 29
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.674359,0.00736603) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.627876,-0.024723) , 
10, 2.12812, 1, 0, 0.667113,0.00183773) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.462362,-0.0330145) , 
1, 44.316, 1, 0, 0.63626,-0.00283933) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.403189,-0.0461028) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.283254,-0.002241) , 
7, 1.55818, 1, 0, 0.314929,-0.011854) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.285552,0.0151184) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.399425,0.0615339) , 
8, 1.11422, 1, 0, 0.313401,0.0194965) , 
0, 57.2937, 1, 0, 0.31414,0.00433932) , 
1, 52.8076, 1, 0, 0.5,0.000197302)    );
  // itree = 30
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.506437,0.00940661) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.524894,-0.0109353) , 
8, 1.11478, 1, 0, 0.5123,0.00207505) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.679762,0.0218774) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.394895,-0.0217726) , 
7, 1.3392, 1, 0, 0.472456,-0.0068159) , 
0, 74.2188, 1, 0, 0.498742,-0.000950371) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.518465,0.0183663) , 
10, 2.73618, 1, 0, 0.5,9.87676e-05)    );
  // itree = 31
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.527801,0.0116923) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.379022,-0.0568368) , 
10, -1.9099, 1, 0, 0.455291,-0.0151535) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.539843,0.00316644) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.410116,-0.0192237) , 
9, 2.18053, 1, 0, 0.513411,-0.000966145) , 
9, -1.11462, 1, 0, 0.499152,-0.00444692) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.479062,0.0274315) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.480333,-0.0210588) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.508255,0.0042509) , 
10, -1.72272, 1, 0, 0.504941,0.000879057) , 
8, 0.251757, 1, 0, 0.500689,0.00386279) , 
8, -0.303988, 1, 0, 0.5,0.000139299)    );
  // itree = 32
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.794924,0.0194833) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.729199,-0.0129433) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.437734,0.00260168) , 
1, 25.5623, 1, 0, 0.494134,-0.000232649) , 
1, 13.0762, 1, 0, 0.521429,0.00104515) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.217801,-0.0232695) , 
5, 198.671, 1, 0, 0.5,0.000128587)    );
  // itree = 33
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.609599,0.0067367) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.541399,-0.0182001) , 
9, 1.61799, 1, 0, 0.600785,0.00290041) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.306913,0.0144638) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.433082,-0.0123761) , 
9, -1.86003, 1, 0, 0.403751,-0.0048891) , 
5, 85.2659, 1, 0, 0.50819,-0.000760204) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.421365,0.0110257) , 
9, 2.53354, 1, 0, 0.5,9.21863e-05)    );
  // itree = 34
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.588224,-0.0317193) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.473462,-0.0103303) , 
7, 2.0942, 1, 0, 0.5318,-0.0182373) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.252595,0.0210291) , 
1, 59.4158, 1, 0, 0.417525,-0.00555002) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.615534,0.0100509) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.287568,-0.00626032) , 
1, 62.3459, 1, 0, 0.509044,0.00426356) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.674778,0.00894692) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.421462,-0.0330246) , 
7, 1.33243, 1, 0, 0.559103,-0.00726223) , 
6, 121.864, 1, 0, 0.521029,0.00150414) , 
9, -1.72273, 1, 0, 0.5,7.09534e-05)    );
  // itree = 35
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.808935,0.0161618) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.527376,-0.00434148) , 
1, 20.8594, 1, 0, 0.599091,3.05374e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.491203,-0.0233686) , 
4, 419.206, 1, 0, 0.581632,-0.0030184) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.466471,0.00798721) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.202952,-0.0246854) , 
1, 102.812, 1, 0, 0.402811,0.00148019) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.330748,0.0352032) , 
9, 2.33086, 1, 0, 0.393672,0.00416993) , 
4, 458.339, 1, 0, 0.5,0.000103533)    );
  // itree = 36
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.740328,0.0140108) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.802537,-0.000511913) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.648625,-0.0374371) , 
7, 1.94275, 1, 0, 0.748036,-0.0113583) , 
6, 56.0517, 1, 0, 0.74603,-0.00546109) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.427381,-0.0279292) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.413942,0.00414367) , 
8, -1.52008, 1, 0, 0.417365,-0.00372194) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.381905,0.00173358) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.494555,0.0337157) , 
8, 1.51943, 1, 0, 0.406382,0.0075732) , 
0, 57.2937, 1, 0, 0.411658,0.00214732) , 
1, 26.4908, 1, 0, 0.5,0.000137164)    );
  // itree = 37
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.742965,-0.00417173) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.422724,0.00900514) , 
1, 28.188, 1, 0, 0.520443,0.00400885) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.176258,-0.0236235) , 
1, 124.233, 1, 0, 0.486417,0.00245572) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.503584,-0.00886733) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.484027,-0.0345644) , 
9, 0.3038, 1, 0, 0.498348,-0.0130106) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.577895,-0.00515325) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.595677,0.0259702) , 
10, 1.72247, 1, 0, 0.586777,0.00916692) , 
6, 96.2161, 1, 0, 0.529744,-0.00513674) , 
8, 1.11474, 1, 0, 0.5,7.54615e-05)    );
  // itree = 38
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.521028,0.000386491) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.691874,0.0254021) , 
9, -0.0817222, 1, 0, 0.560739,0.00497144) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.561082,-0.0115645) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.26062,0.0242565) , 
1, 79.2681, 1, 0, 0.492097,-0.00398918) , 
9, 0.506744, 1, 0, 0.534549,0.00155253) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.544749,0.000111189) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.38562,-0.0254692) , 
3, 246.419, 1, 0, 0.447371,-0.0122276) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.212516,0.0136159) , 
5, 113.912, 1, 0, 0.368359,-0.0056776) , 
7, 2.88971, 1, 0, 0.5,4.94823e-05)    );
  // itree = 39
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.571186,0.0126002) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.539498,-0.0230903) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.35963,0.000109179) , 
4, 348.459, 1, 0, 0.409099,-0.00541448) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.508193,0.00500788) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.561335,-0.0117795) , 
6, 121.864, 1, 0, 0.521266,0.000731095) , 
9, -1.52005, 1, 0, 0.495241,-0.000694818) , 
8, -2.73609, 1, 0, 0.5,3.86571e-05)    );
  // itree = 40
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.566768,0.00215483) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.411924,-0.00796266) , 
7, 2.39535, 1, 0, 0.504594,-0.00136901) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.415731,0.0142412) , 
2, 125.433, 1, 0, 0.498324,-0.000516852) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.529365,0.0118635) , 
6, 202.856, 1, 0, 0.5,1.56817e-05)    );
  // itree = 41
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.699255,-0.0115344) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.445055,0.0225129) , 
1, 39.0243, 1, 0, 0.561213,0.00654451) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.41829,0.0249394) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.467193,-0.0116088) , 
2, 50.0158, 1, 0, 0.438696,0.0070833) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.50753,0.00104563) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.490349,-0.00897471) , 
10, 0.506727, 1, 0, 0.50072,-0.00232308) , 
6, 40.7077, 1, 0, 0.491285,-0.00089219) , 
3, 189.352, 1, 0, 0.5,3.46694e-05)    );
  // itree = 42
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.633496,-0.0237015) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.626946,0.0192132) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.54745,-0.00862365) , 
8, 2.33081, 1, 0, 0.603747,0.00928908) , 
7, 1.39043, 1, 0, 0.609787,0.00339598) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.517798,0.00991635) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.436107,-0.00673439) , 
8, -1.78174, 1, 0, 0.446974,-0.0031677) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.555576,0.0228798) , 
8, 2.12798, 1, 0, 0.455448,-0.0014008) , 
5, 56.9145, 1, 0, 0.5,-1.6149e-05)    );
  // itree = 43
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.58137,-0.0273197) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.486443,-0.00388757) , 
7, 1.22939, 1, 0, 0.502683,-0.0063555) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.564491,0.0241736) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.406258,-0.00976862) , 
8, -1.494, 1, 0, 0.487678,0.00741585) , 
0, 87.5352, 1, 0, 0.499152,-0.00311451) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.517502,0.0317489) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.409242,-0.0113059) , 
0, 65.1255, 1, 0, 0.464669,0.00808384) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.6314,0.0151455) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.503063,-0.00490842) , 
7, 1.22384, 1, 0, 0.525315,-0.00109283) , 
8, 1.02976, 1, 0, 0.500689,0.00263346) , 
8, -0.303988, 1, 0, 0.5,5.78602e-05)    );
  // itree = 44
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.530712,-0.0166527) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.668949,0.0333521) , 
0, 56.8265, 1, 0, 0.603025,0.00835653) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.557637,-0.0048791) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.358719,-0.0345733) , 
5, 70.2919, 1, 0, 0.482599,-0.0125359) , 
7, 1.95906, 1, 0, 0.533298,-0.00374017) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.601947,0.00705112) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.338258,-0.01832) , 
1, 66.39, 1, 0, 0.574158,0.00371969) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.246599,-0.0250244) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.210399,0.0439663) , 
9, 1.31746, 1, 0, 0.236137,-0.00477735) , 
1, 79.1244, 1, 0, 0.487228,0.0015345) , 
8, -1.31737, 1, 0, 0.5,7.22534e-05)    );
  // itree = 45
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.492794,0.00402741) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.453405,-0.00994972) , 
0, 78.3056, 1, 0, 0.480623,-0.000118613) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.759351,0.0370038) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.587683,-0.00432862) , 
7, 1.94136, 1, 0, 0.678351,0.0127976) , 
9, -0.140582, 1, 0, 0.519085,0.0023938) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.694417,0.00297284) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.356004,-0.0407193) , 
1, 53.3586, 1, 0, 0.5711,-0.0107916) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.507507,-0.00409212) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.240501,0.0223731) , 
5, 106.364, 1, 0, 0.407996,0.00267331) , 
7, 1.88291, 1, 0, 0.474413,-0.00280966) , 
9, 0.304065, 1, 0, 0.5,0.00017078)    );
  // itree = 46
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.703695,0.0060464) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.561125,-0.0102771) , 
7, 2.55653, 1, 0, 0.660272,0.000633583) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.458055,-0.0272021) , 
1, 46.0137, 1, 0, 0.63626,-0.00225689) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.432044,-0.0190584) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.241563,0.00944867) , 
7, 1.55785, 1, 0, 0.295319,-0.000518097) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.400077,0.0251624) , 
8, 1.72264, 1, 0, 0.31414,0.00342806) , 
1, 52.8076, 1, 0, 0.5,0.000147891)    );
  // itree = 47
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.80637,0.0236834) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.518151,-0.00114019) , 
1, 12.03, 1, 0, 0.541723,0.000468467) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.432454,-0.029421) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.492718,0.00758788) , 
0, 56.8286, 1, 0, 0.461695,-0.00928596) , 
9, 2.33087, 1, 0, 0.532326,-0.000676928) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.282198,0.023062) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.20648,-0.0042934) , 
5, 216.05, 1, 0, 0.245971,0.00581099) , 
5, 170.32, 1, 0, 0.5,5.54837e-05)    );
  // itree = 48
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.536072,-0.0138122) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.68549,0.0225837) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.563494,-0.00603903) , 
10, 1.44178, 1, 0, 0.631862,0.00779974) , 
10, -2.12808, 1, 0, 0.609787,0.00317756) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.681236,0.0134465) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.434946,-0.00560445) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.363759,0.0155652) , 
2, 124.54, 1, 0, 0.427593,-0.00261424) , 
7, 0.895212, 1, 0, 0.455448,-0.00119028) , 
5, 56.9145, 1, 0, 0.5,7.05532e-05)    );
  // itree = 49
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.391205,-0.0169766) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.509786,0.0013118) , 
9, -2.33075, 1, 0, 0.496492,-0.000514138) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.599601,0.0194226) , 
6, 136.895, 1, 0, 0.507101,0.00103441) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.503236,0.0147135) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.579234,-0.042587) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.31312,0.015344) , 
1, 52.8076, 1, 0, 0.449541,-0.0132308) , 
0, 52.1132, 1, 0, 0.46989,-0.00378711) , 
2, 95.1641, 1, 0, 0.5,0.000114322)    );
  // itree = 50
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.421049,0.0126939) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.464631,-0.0119384) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.495289,0.00388128) , 
10, -2.12794, 1, 0, 0.490949,0.00112702) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.662219,0.0019123) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.375059,-0.0244071) , 
7, 1.48935, 1, 0, 0.550657,-0.00591467) , 
6, 121.864, 1, 0, 0.50522,-0.000555938) , 
9, -2.73612, 1, 0, 0.5,6.45491e-05)    );
  // itree = 51
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.496525,0.0115864) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.763996,0.0218079) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.395365,-0.00234876) , 
1, 21.0041, 1, 0, 0.461551,0.00152777) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.537366,-0.00883598) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.538392,0.0127756) , 
10, 1.62442, 1, 0, 0.537601,-0.00265442) , 
6, 81.2447, 1, 0, 0.500233,-0.000599456) , 
10, -2.73611, 1, 0, 0.5,6.03428e-05)    );
  // itree = 52
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.550879,0.00174782) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.266091,0.0336881) , 
1, 57.8773, 1, 0, 0.426289,0.00981905) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.601376,0.00469363) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.25391,-0.0202059) , 
1, 82.2876, 1, 0, 0.525851,8.2927e-05) , 
9, -1.92532, 1, 0, 0.50602,0.00202216) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.609266,-0.0030912) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.469192,0.0201373) , 
4, 347.594, 1, 0, 0.562824,0.00393019) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.482692,-0.0164) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.324255,0.000532926) , 
4, 606.53, 1, 0, 0.432305,-0.00882251) , 
3, 277.632, 1, 0, 0.489657,-0.00321882) , 
10, 0.709404, 1, 0, 0.5,9.39653e-05)    );
  // itree = 53
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.781044,0.0184175) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.688647,-0.00752972) , 
1, 16.3639, 1, 0, 0.732591,0.00309591) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.827381,0.00262882) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.66075,-0.0334372) , 
7, 1.58156, 1, 0, 0.758904,-0.0102754) , 
6, 83.9923, 1, 0, 0.74603,-0.00373323) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.470934,-0.0102506) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.489417,0.00531841) , 
0, 50.0952, 1, 0, 0.480982,-0.00153826) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.495066,0.0159896) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.265288,0.00114538) , 
1, 51.9668, 1, 0, 0.336061,0.00467966) , 
4, 462.93, 1, 0, 0.411658,0.00143611) , 
1, 26.4908, 1, 0, 0.5,7.03619e-05)    );
  // itree = 54
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.652326,-0.00984779) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.507634,0.0120169) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.480217,0.000931274) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.546006,-0.0079361) , 
8, 2.12813, 1, 0, 0.489775,-0.000389792) , 
3, 190.727, 1, 0, 0.491236,0.000499491) , 
4, 256.186, 1, 0, 0.5,4.20802e-05)    );
  // itree = 55
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.636626,0.00646528) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.481093,-0.00247749) , 
5, 56.9145, 1, 0, 0.524192,0.000134973) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.542661,0.0110267) , 
10, 2.73618, 1, 0, 0.525342,0.000712194) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.328253,-0.016817) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.358658,0.00375276) , 
10, -0.101177, 1, 0, 0.343863,-0.00431922) , 
7, 3.05629, 1, 0, 0.5,9.58929e-06)    );
  // itree = 56
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.593238,-0.00391586) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.398863,0.00432156) , 
5, 85.2659, 1, 0, 0.498476,-0.000174369) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.551816,0.0215489) , 
10, 0.153649, 1, 0, 0.50444,0.00157043) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.468292,0.00616759) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.484664,-0.0105054) , 
8, 0.336687, 1, 0, 0.479826,-0.00435389) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.578128,0.0128423) , 
8, 2.53347, 1, 0, 0.493459,-0.00219965) , 
10, 0.506727, 1, 0, 0.5,4.59802e-05)    );
  // itree = 57
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.582156,0.0120366) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.622987,0.000102207) , 
6, 56.0517, 1, 0, 0.611944,0.00279539) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.287806,-0.0196256) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.283364,0.00300262) , 
0, 47.5591, 1, 0, 0.284862,-0.00342221) , 
1, 62.2022, 1, 0, 0.499761,0.000662861) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.50231,-0.00741181) , 
10, 2.5335, 1, 0, 0.5,2.27541e-05)    );
  // itree = 58
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.429713,-0.0110602) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.631453,0.0105992) , 
2, 39.4568, 1, 0, 0.569448,0.00312681) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.534365,-0.0148079) , 
2, 127.746, 1, 0, 0.566439,0.00180238) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.532495,-0.00271396) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.284459,-0.0372857) , 
1, 68.9896, 1, 0, 0.486803,-0.00704457) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.216855,0.00388011) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.219607,0.0237178) , 
9, 0.709242, 1, 0, 0.2181,0.00706027) , 
5, 113.912, 1, 0, 0.400842,-0.00253226) , 
7, 2.38995, 1, 0, 0.5,6.32867e-05)    );
  // itree = 59
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.691832,-0.00693763) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.565889,-0.0220296) , 
4, 378.759, 1, 0, 0.630919,-0.012195) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.659396,0.00604136) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.596643,-0.00928834) , 
0, 74.2211, 1, 0, 0.637625,0.000526872) , 
8, -1.92535, 1, 0, 0.63626,-0.00206366) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.400977,0.0247247) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.265032,-0.00871433) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.400656,0.0180804) , 
8, 1.7292, 1, 0, 0.294743,-0.000917712) , 
8, -1.72275, 1, 0, 0.31414,0.00303546) , 
1, 52.8076, 1, 0, 0.5,9.33128e-05)    );
  // itree = 60
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.609419,0.0120829) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.60833,-0.00407395) , 
0, 40.402, 1, 0, 0.608638,0.000341891) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.541803,-0.0167464) , 
9, 1.72282, 1, 0, 0.596283,-0.00235515) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.408564,0.00624727) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.326546,-0.0133308) , 
10, 0.507073, 1, 0, 0.383396,0.000254303) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.480812,0.0256727) , 
8, 1.51941, 1, 0, 0.394959,0.00268831) , 
5, 85.2659, 1, 0, 0.5,5.68853e-05)    );
  // itree = 61
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.603457,-0.00440889) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.609374,0.00836124) , 
8, -1.50703, 1, 0, 0.607363,0.00310806) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.428367,-0.0219732) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.239417,0.000903944) , 
7, 1.22683, 1, 0, 0.273121,-0.00290762) , 
1, 62.2053, 1, 0, 0.487119,0.0009439) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.617399,0.00932495) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.587197,0.000952856) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.429311,-0.0340336) , 
7, 2.22336, 1, 0, 0.511267,-0.012968) , 
3, 260.714, 1, 0, 0.556684,-0.00394937) , 
8, 1.92544, 1, 0, 0.5,3.78053e-05)    );
  // itree = 62
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.452756,-0.0107786) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.516332,0.0207051) , 
0, 50.1013, 1, 0, 0.490288,0.00688122) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.646731,0.0113466) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.639472,-0.0130297) , 
0, 36.1796, 1, 0, 0.640602,-0.00736216) , 
2, 42.6692, 1, 0, 0.581632,-0.00177433) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.578224,0.00290795) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.427986,0.0264711) , 
7, 1.56414, 1, 0, 0.53817,0.00710984) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.229378,0.016575) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.277156,-0.0131096) , 
9, -0.709331, 1, 0, 0.258797,-0.00184358) , 
7, 1.97243, 1, 0, 0.393672,0.00247894) , 
4, 458.339, 1, 0, 0.5,7.28914e-05)    );
  // itree = 63
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.591321,-0.0154084) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.464733,0.0109057) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.424462,-0.00499224) , 
0, 46.106, 1, 0, 0.436827,-3.97096e-05) , 
7, 1.23226, 1, 0, 0.465252,-0.00233254) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.761929,0.026221) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.584989,-0.00284293) , 
7, 1.94136, 1, 0, 0.67726,0.00866754) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.482793,-0.00226657) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.521847,0.0109091) , 
10, 2.33091, 1, 0, 0.489366,9.00137e-05) , 
9, 0.140618, 1, 0, 0.525601,0.00174415) , 
9, -0.303973, 1, 0, 0.5,1.47626e-05)    );
  // itree = 64
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.546512,-0.0123717) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.595694,0.0120902) , 
0, 56.8228, 1, 0, 0.565581,-0.00226556) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.503414,0.0223425) , 
5, 70.2919, 1, 0, 0.546761,0.0038968) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.495694,0.0118147) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.521184,-0.0104809) , 
8, 1.4154, 1, 0, 0.504866,0.00234058) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.430344,-0.0110693) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.562522,0.00497907) , 
8, 1.4155, 1, 0, 0.471994,-0.00390973) , 
0, 57.2937, 1, 0, 0.487308,-0.000997937) , 
8, -1.72272, 1, 0, 0.5,4.69741e-05)    );
  // itree = 65
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.564466,0.00724346) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.645314,0.00392097) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.460727,-0.005715) , 
7, 1.56351, 1, 0, 0.521659,-0.00190999) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.524071,-0.0060419) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.357936,0.0129694) , 
7, 2.04869, 1, 0, 0.429546,0.00307332) , 
9, 1.11478, 1, 0, 0.494874,-0.000460948) , 
5, 28.5632, 1, 0, 0.5,5.08437e-05)    );
  // itree = 66
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.465817,0.0231397) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.45643,0.00048289) , 
6, 21.2593, 1, 0, 0.457895,0.00309499) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.533309,0.0135565) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.521477,-0.00507825) , 
10, -2.53343, 1, 0, 0.522559,-0.00243103) , 
6, 65.5463, 1, 0, 0.498324,-0.000359979) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.529365,0.00866019) , 
6, 202.856, 1, 0, 0.5,2.05411e-05)    );
  // itree = 67
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.652326,-0.00876427) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.531403,0.00379171) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.512578,-0.00431726) , 
2, 95.1641, 1, 0, 0.527737,0.0016957) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.364962,-0.0120215) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.315365,0.00885358) , 
0, 88.267, 1, 0, 0.351006,-0.0045253) , 
7, 2.88971, 1, 0, 0.491236,0.000410827) , 
4, 256.186, 1, 0, 0.5,6.24931e-06)    );
  // itree = 68
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.597368,-0.0067915) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.610978,0.0129213) , 
0, 47.5491, 1, 0, 0.603972,0.00255901) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.459574,-0.0110389) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.321454,0.0187298) , 
4, 658.607, 1, 0, 0.432191,-0.00447066) , 
5, 65.1043, 1, 0, 0.499152,-0.00173049) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.404205,-0.0191103) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.521877,0.00342795) , 
9, -2.33076, 1, 0, 0.507342,0.000546004) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.439183,0.0127877) , 
2, 127.746, 1, 0, 0.500689,0.00143453) , 
8, -0.303988, 1, 0, 0.5,1.63158e-05)    );
  // itree = 69
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.651896,-0.0105268) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.495008,0.00108088) , 
7, 1.05725, 1, 0, 0.515569,-0.000319351) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.49534,0.0102677) , 
0, 122.274, 1, 0, 0.513904,0.000364467) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.276558,-0.00912264) , 
4, 862.646, 1, 0, 0.5,2.43449e-05)    );
  // itree = 70
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.41621,0.00556969) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.420098,-0.0218604) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.50043,0.000422602) , 
0, 44.3893, 1, 0, 0.479543,-0.00425963) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.613178,0.00486969) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.356097,-0.00667462) , 
5, 105.918, 1, 0, 0.517649,0.000807394) , 
10, -1.31726, 1, 0, 0.508473,-0.00041277) , 
9, -2.53344, 1, 0, 0.5,6.72872e-06)    );
  // itree = 71
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.595152,-0.00121026) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.648524,0.0166372) , 
0, 86.7905, 1, 0, 0.601155,0.000726131) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.574145,0.00360618) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.276469,-0.0373211) , 
7, 2.09015, 1, 0, 0.438101,-0.0107669) , 
4, 541.808, 1, 0, 0.572927,-0.00126352) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.556769,-0.00997197) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.375959,-0.00500288) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.175926,0.0279628) , 
7, 1.72286, 1, 0, 0.242716,0.007548) , 
1, 53.1482, 1, 0, 0.33109,0.0031179) , 
5, 113.617, 1, 0, 0.5,5.77143e-05)    );
  // itree = 72
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.580768,0.0110642) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.489267,0.000875827) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.550423,-0.0121104) , 
8, 2.33066, 1, 0, 0.493863,-0.000156357) , 
5, 28.5632, 1, 0, 0.499761,0.000523939) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.50231,-0.00652373) , 
10, 2.5335, 1, 0, 0.5,-3.34447e-05)    );
  // itree = 73
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.554122,0.00013867) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.637392,-0.019032) , 
2, 59.4235, 1, 0, 0.573316,-0.0033764) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.621535,0.0103224) , 
2, 80.6764, 1, 0, 0.581632,-0.00131249) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.339037,-0.0107802) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.450073,0.00739534) , 
9, -1.92532, 1, 0, 0.430483,0.00330881) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.184078,-0.0152484) , 
1, 131.758, 1, 0, 0.393672,0.00167795) , 
4, 458.339, 1, 0, 0.5,-1.37209e-05)    );
  // itree = 74
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.457261,8.22518e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.67823,0.0198702) , 
9, -0.526345, 1, 0, 0.519223,0.00437843) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.474333,0.00607516) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.477546,-0.0245686) , 
2, 61.3341, 1, 0, 0.475738,-0.00551571) , 
0, 78.3042, 1, 0, 0.505846,0.0013348) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.651498,0.0135231) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.466073,-0.00737949) , 
7, 1.22719, 1, 0, 0.499889,-0.0027311) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.466657,0.00497804) , 
2, 95.1641, 1, 0, 0.49353,-0.00146091) , 
9, 0.101385, 1, 0, 0.5,7.72274e-06)    );
  // itree = 75
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.553639,-0.0100178) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.420856,0.00886616) , 
7, 2.06385, 1, 0, 0.482743,-0.000272851) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.211286,0.0336102) , 
1, 98.9103, 1, 0, 0.439364,0.00249535) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.635097,0.0036481) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.461174,-0.00572144) , 
9, 1.52678, 1, 0, 0.574881,0.000327024) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.23442,-0.0195257) , 
1, 105.58, 1, 0, 0.532227,-0.00122267) , 
9, -0.709331, 1, 0, 0.5,6.76203e-05)    );
  // itree = 76
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.560976,-0.0451512) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.576174,0.0117104) , 
7, 1.10985, 1, 0, 0.568891,-0.0117606) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.701163,0.0280015) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.60848,-0.00106277) , 
7, 1.03032, 1, 0, 0.652153,0.00980613) , 
0, 51.5632, 1, 0, 0.622379,0.00209405) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.489264,0.012218) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.44634,-0.0026858) , 
0, 43.3447, 1, 0, 0.459276,0.00138405) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.375301,0.0194505) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.420079,-0.0221587) , 
9, -1.31739, 1, 0, 0.407073,-0.00763101) , 
6, 95.7195, 1, 0, 0.446169,-0.000879382) , 
7, 1.55701, 1, 0, 0.5,2.89803e-05)    );
  // itree = 77
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.584879,0.00552042) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.568839,-0.0150005) , 
2, 95.1646, 1, 0, 0.581978,0.00129986) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.434629,-0.0110085) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.370625,0.0185135) , 
2, 92.6658, 1, 0, 0.422212,-0.00409329) , 
7, 2.39509, 1, 0, 0.519701,-0.000802403) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.523877,-0.00730315) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.358115,0.00470271) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.334402,0.0268815) , 
8, -0.71059, 1, 0, 0.345657,0.0110122) , 
7, 2.04869, 1, 0, 0.424161,0.00350767) , 
9, 1.72282, 1, 0, 0.5,8.63655e-05)    );
  // itree = 78
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.561222,-0.000245482) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.623634,0.0177581) , 
0, 56.8261, 1, 0, 0.592604,0.00762105) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.437082,-0.010159) , 
3, 362.423, 1, 0, 0.546761,0.00293913) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.558772,-0.00989864) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.448158,0.00127912) , 
3, 283.687, 1, 0, 0.490525,-0.00240516) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.538709,-0.0013931) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.354221,0.0212327) , 
5, 96.7919, 1, 0, 0.477568,0.00418587) , 
10, 1.52011, 1, 0, 0.487308,-0.000768588) , 
8, -1.72272, 1, 0, 0.5,2.29239e-05)    );
  // itree = 79
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.587604,-0.000156606) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.689064,0.0204522) , 
9, -0.264956, 1, 0, 0.626716,0.0061823) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.570665,-0.00765952) , 
9, 0.911788, 1, 0, 0.609787,0.0023497) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.464755,-0.00416203) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.256281,0.0165481) , 
7, 3.21293, 1, 0, 0.446974,-0.00199059) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.555576,0.0136668) , 
8, 2.12798, 1, 0, 0.455448,-0.000947666) , 
5, 56.9145, 1, 0, 0.5,4.16185e-06)    );
  // itree = 80
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.489517,-0.0109249) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.641891,0.00859545) , 
6, 82.3254, 1, 0, 0.615092,0.0041222) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.491285,0.00699783) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.437472,-0.010491) , 
6, 67.47, 1, 0, 0.463893,-0.00141768) , 
7, 1.68059, 1, 0, 0.525342,0.000833805) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.414294,-0.0127092) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.222555,0.00664419) , 
3, 359.559, 1, 0, 0.343863,-0.00497073) , 
7, 3.05629, 1, 0, 0.5,2.32393e-05)    );
  // itree = 81
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.65279,0.00920898) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.600238,-0.00460158) , 
8, 1.31742, 1, 0, 0.634434,0.00341482) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.259391,-0.0232998) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.519762,0.00427727) , 
6, 105.485, 1, 0, 0.429049,-0.00318662) , 
5, 105.623, 1, 0, 0.566439,0.00122932) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.370754,0.0011395) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.535581,-0.023854) , 
9, -0.434963, 1, 0, 0.421231,-0.00557224) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.407149,0.0131444) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.311281,-0.00645688) , 
9, 2.20661, 1, 0, 0.369925,0.00425246) , 
9, 0.506716, 1, 0, 0.400842,-0.00166782) , 
7, 2.38995, 1, 0, 0.5,6.69697e-05)    );
  // itree = 82
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.46163,0.0156283) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.483723,-0.0123622) , 
6, 30.0998, 1, 0, 0.478239,-0.00407811) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.636119,-0.00642358) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.512048,0.0198859) , 
5, 43.4735, 1, 0, 0.54842,0.00927432) , 
2, 61.5138, 1, 0, 0.507985,0.00158126) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.532308,0.00848811) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.345607,-0.0125228) , 
7, 2.74905, 1, 0, 0.484862,0.0026518) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.515699,-0.00105017) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.477743,-0.0271371) , 
10, 1.11476, 1, 0, 0.504488,-0.00687769) , 
2, 62.5821, 1, 0, 0.492871,-0.0012371) , 
0, 57.2913, 1, 0, 0.5,9.22349e-05)    );
  // itree = 83
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.721072,0.00642379) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.418132,-0.0183019) , 
1, 39.1951, 1, 0, 0.620025,-0.00207211) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.691169,-0.00521609) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.501967,0.0229358) , 
1, 37.374, 1, 0, 0.595609,0.00866741) , 
0, 48.4909, 1, 0, 0.609787,0.00243115) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.58151,-0.00961811) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.392114,0.00086748) , 
5, 83.437, 1, 0, 0.446974,-0.00180889) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.555576,0.0120831) , 
8, 2.12798, 1, 0, 0.455448,-0.00088434) , 
5, 56.9145, 1, 0, 0.5,7.27196e-05)    );
  // itree = 84
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.436264,-0.0115527) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.518358,0.00132202) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.53192,0.0221492) , 
0, 52.0091, 1, 0, 0.520528,0.00357008) , 
10, -2.12799, 1, 0, 0.507985,0.00161759) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.44216,0.00230602) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.579833,-0.0105336) , 
9, -0.696411, 1, 0, 0.514213,-0.00351836) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.39631,0.0142937) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.490429,-0.00553157) , 
8, 0.304094, 1, 0, 0.431909,0.00483464) , 
9, 1.31745, 1, 0, 0.492871,-0.00135241) , 
0, 57.2913, 1, 0, 0.5,4.84544e-05)    );
  // itree = 85
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.630558,0.014919) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.595284,-0.00156128) , 
0, 44.3902, 1, 0, 0.604501,0.00222983) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.27288,-0.02129) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.284957,0.00225241) , 
0, 62.2058, 1, 0, 0.278492,-0.0072479) , 
1, 59.4158, 1, 0, 0.485203,-0.00123841) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.515325,0.00652777) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.475292,-0.00540628) , 
0, 52.1094, 1, 0, 0.490973,-0.000506133) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.564825,0.0178225) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.616645,-0.00363974) , 
2, 56.6227, 1, 0, 0.588671,0.00664558) , 
8, 1.52009, 1, 0, 0.513184,0.00111982) , 
9, -0.101294, 1, 0, 0.5,8.66568e-06)    );
  // itree = 86
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.596559,0.00309719) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.557728,-0.00573573) , 
8, 1.52009, 1, 0, 0.583608,4.27287e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.458681,-0.0127981) , 
5, 102.642, 1, 0, 0.572927,-0.000832597) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.371829,0.015763) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.303245,-0.00854082) , 
8, -0.918886, 1, 0, 0.320323,-0.00123261) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.373328,0.0222423) , 
8, 0.911225, 1, 0, 0.33109,0.00215991) , 
5, 113.617, 1, 0, 0.5,6.98073e-05)    );
  // itree = 87
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.532486,-0.00223526) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.431424,0.0108681) , 
5, 73.8132, 1, 0, 0.486269,0.00275862) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.600027,0.000483302) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.320327,-0.0175152) , 
5, 108.366, 1, 0, 0.505371,-0.00357503) , 
10, -1.72202, 1, 0, 0.499152,-0.00151283) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.653501,-0.0244396) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.627989,0.00805687) , 
8, 0.807216, 1, 0, 0.638166,-0.00286386) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.390657,0.0212728) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.469176,-0.000386849) , 
8, 0.474045, 1, 0, 0.452509,0.0027675) , 
7, 1.39043, 1, 0, 0.500689,0.0013061) , 
8, -0.303988, 1, 0, 0.5,4.29675e-05)    );
  // itree = 88
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.729992,-0.00505823) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.55595,0.00892113) , 
1, 30.0761, 1, 0, 0.667113,0.000396283) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.462362,-0.0129428) , 
1, 44.316, 1, 0, 0.63626,-0.00134001) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.454033,0.0188393) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.261955,-0.00041662) , 
7, 1.90306, 1, 0, 0.33941,0.00616735) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.314814,-0.030476) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.265999,0.00645109) , 
9, 1.12799, 1, 0, 0.280321,-0.00385322) , 
9, 0.304065, 1, 0, 0.31414,0.00188187) , 
1, 52.8076, 1, 0, 0.5,2.28745e-05)    );
  // itree = 89
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.601832,0.00180016) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.27354,-0.0102199) , 
1, 59.4158, 1, 0, 0.481683,-0.00152151) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.698531,0.0216608) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.543569,-2.93683e-05) , 
7, 1.33432, 1, 0, 0.584648,0.00420769) , 
9, -0.134183, 1, 0, 0.522476,0.000748306) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.575168,-0.0184822) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.357075,-0.00943758) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.415678,0.0144059) , 
2, 59.662, 1, 0, 0.383159,0.00118628) , 
7, 1.38557, 1, 0, 0.425905,-0.00248035) , 
9, 1.52014, 1, 0, 0.5,-3.13753e-06)    );
  // itree = 90
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.655309,-0.00417974) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.617917,0.00530674) , 
9, 0.303838, 1, 0, 0.639932,-0.000137869) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.600737,-0.0135808) , 
10, 2.53348, 1, 0, 0.63626,-0.00121077) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.401594,0.0127) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.265071,-0.00647219) , 
8, -1.72946, 1, 0, 0.295319,-0.000799846) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.400077,0.0163654) , 
8, 1.72264, 1, 0, 0.31414,0.00181986) , 
1, 52.8076, 1, 0, 0.5,7.12119e-05)    );
  // itree = 91
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.591132,0.00342444) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.508796,-0.0136611) , 
5, 51.4268, 1, 0, 0.546417,-0.00466834) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.633799,0.00699359) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.550337,-0.00290807) , 
8, 1.2717, 1, 0, 0.587283,0.00101949) , 
8, -1.31737, 1, 0, 0.572927,-0.00097864) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.556769,-0.00582094) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.188319,0.0247826) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.275396,0.00148654) , 
9, -0.709449, 1, 0, 0.242716,0.00517553) , 
1, 53.1482, 1, 0, 0.33109,0.00238205) , 
5, 113.617, 1, 0, 0.5,3.4791e-05)    );
  // itree = 92
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.497805,0.00299338) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.372837,-0.0131013) , 
9, 2.33086, 1, 0, 0.483571,0.000929894) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.552478,0.0116612) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.545242,-0.0123546) , 
10, -1.43509, 1, 0, 0.547027,-0.00447727) , 
6, 121.782, 1, 0, 0.498742,-0.000362891) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.518465,0.00574833) , 
10, 2.73618, 1, 0, 0.5,-2.96978e-05)    );
  // itree = 93
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.540001,-0.0131569) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.342833,0.00673718) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.44897,-0.0101803) , 
8, 1.5182, 1, 0, 0.372339,0.000917675) , 
7, 1.73135, 1, 0, 0.4283,-0.00303133) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.727604,0.010053) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.405247,-0.000917904) , 
1, 53.1495, 1, 0, 0.604213,0.00440899) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.466959,0.000529265) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.318364,-0.0208423) , 
6, 88.3982, 1, 0, 0.436437,-0.00270616) , 
7, 2.21447, 1, 0, 0.528421,0.00119475) , 
9, -1.11469, 1, 0, 0.5,-4.89785e-06)    );
  // itree = 94
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.568848,9.42431e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.527959,-0.0159882) , 
8, -2.39625, 1, 0, 0.553789,-0.00480523) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.570401,-0.00269055) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.601306,0.00778419) , 
0, 66.9838, 1, 0, 0.579062,0.000276611) , 
8, -1.92539, 1, 0, 0.572927,-0.000956946) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.493711,-0.00122387) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.2415,0.0169037) , 
7, 1.76017, 1, 0, 0.36749,0.0044868) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.213626,-0.0074039) , 
7, 2.88157, 1, 0, 0.33109,0.00243601) , 
5, 113.617, 1, 0, 0.5,6.62156e-05)    );
  // itree = 95
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.317025,-0.00363585) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.449227,-0.019452) , 
2, 38.1328, 1, 0, 0.385885,-0.00906204) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.457457,0.00680562) , 
2, 61.5146, 1, 0, 0.417525,-0.00267752) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.525286,0.00117079) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.47933,-0.0127617) , 
10, 1.80113, 1, 0, 0.521116,-0.00013169) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.520351,0.00846224) , 
10, 2.33082, 1, 0, 0.521029,0.000687475) , 
9, -1.72273, 1, 0, 0.5,3.81483e-06)    );
  // itree = 96
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.550308,0.00756716) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.477491,-0.00229943) , 
8, -1.6377, 1, 0, 0.49916,0.000749978) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.468439,-0.0152655) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.376075,0.00101358) , 
7, 2.55279, 1, 0, 0.426335,-0.0061903) , 
10, 1.11503, 1, 0, 0.48493,-0.000606166) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.547733,0.0210456) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.650426,-0.00259856) , 
2, 45.9459, 1, 0, 0.603233,0.00731772) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.573561,0.00485997) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.377162,-0.0175992) , 
7, 2.22336, 1, 0, 0.482826,-0.00404886) , 
3, 293.22, 1, 0, 0.545944,0.00190955) , 
8, 1.52009, 1, 0, 0.5,1.51908e-05)    );
  // itree = 97
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.572945,-0.000961879) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.589089,-0.0192437) , 
8, 1.8009, 1, 0, 0.574667,-0.00240066) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.623549,0.00841546) , 
8, 2.33079, 1, 0, 0.581632,-0.00101135) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.313499,-0.00941669) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.426708,0.00997462) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.389197,-0.00371578) , 
10, 0.50678, 1, 0, 0.411421,0.00308868) , 
9, -1.92541, 1, 0, 0.393672,0.00141122) , 
4, 458.339, 1, 0, 0.5,4.0788e-05)    );
  // itree = 98
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.5024,0.00747221) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.524786,-0.0076654) , 
10, -1.71983, 1, 0, 0.519268,-0.00269278) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.404124,-0.0133092) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.402852,0.0179886) , 
10, -1.11414, 1, 0, 0.403341,0.00398462) , 
9, 1.72284, 1, 0, 0.492873,-0.00117239) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.485417,-0.00998348) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.537062,0.0178523) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.507383,0.000812586) , 
10, 0.474539, 1, 0, 0.513363,0.00312991) , 
10, -1.72272, 1, 0, 0.509863,0.00168454) , 
8, 0.506714, 1, 0, 0.5,2.60948e-05)    );
  // itree = 99
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.579711,0.000726884) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.539441,-0.0100097) , 
9, 0.304259, 1, 0, 0.561727,-0.0034586) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.534037,0.0099131) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.427178,-0.00544715) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.49998,0.00105693) , 
6, 40.7077, 1, 0, 0.488499,2.0132e-05) , 
8, -1.97761, 1, 0, 0.491204,0.000502653) , 
8, -2.33074, 1, 0, 0.5,8.60429e-06)    );
   return;
};
 
// Clean up
inline void ReadBDT::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDT::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
