// Class: ReadBDT
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.10/04       [395780]
Creator        : marine5575
Date           : Wed Oct  9 19:51:57 2019
Host           : Linux htop.hanyang.ac.kr 2.6.32-696.el6.centos.plus.x86_64 #1 SMP Mon Apr 3 14:56:08 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/marine5575/work/Undergrad2018/mva
Training events: 50004
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "100" [Number of trees in the forest]
MaxDepth: "3" [Max depth of the decision tree allowed]
MinNodeSize: "5%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
nCuts: "10" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "Grad" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
Shrinkage: "5.000000e-01" [Learning rate for GradBoost algorithm]
SeparationType: "giniindex" [Separation criterion for node splitting]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
UseBaggedBoost: "False" [Use only a random subsample of all events for growing the trees in each boost iteration.]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "3" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Poisson distribution in each split with RandomisedTree option]
BaggedSampleFraction: "6.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "pray" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in training sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
RegressionLossFunctionBDTG: "huber" [Loss function for BDTG regression.]
HuberQuantile: "7.000000e-01" [In the Huber loss function this is the quantile that separates the core from the tails in the residuals distribution.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
SkipNormalization: "False" [Skip normalization at initialization, to keep expectation value of BDT output according to the fraction of events]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "6.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 11
lepton1_pt                    lepton1_pt                    lepton1_pt                    lepton1_pt                                                      'F'    [30.0003757477,715.323425293]
met_pt                        met_pt                        met_pt                        met_pt                                                          'F'    [0.19669675827,832.46496582]
tau1_pt                       tau1_pt                       tau1_pt                       tau1_pt                                                         'F'    [30.0003395081,1108.22265625]
jet_ht                        jet_ht                        jet_ht                        jet_ht                                                          'F'    [95.0174484253,2866.1184082]
jetlepmet_ht                  jetlepmet_ht                  jetlepmet_ht                  jetlepmet_ht                                                    'F'    [144.123748779,3074.10449219]
lep1met_pt                    lep1met_pt                    lep1met_pt                    lep1met_pt                                                      'F'    [0.211814135313,920.750061035]
lep1tau1_pt                   lep1tau1_pt                   lep1tau1_pt                   lep1tau1_pt                                                     'F'    [0.167901813984,1148.01318359]
tau1_lep1_dr                  tau1_lep1_dr                  tau1_lep1_dr                  tau1_lep1_dr                                                    'F'    [0.390903234482,5.5550994873]
lep1_met_dphi                 lep1_met_dphi                 lep1_met_dphi                 lep1_met_dphi                                                   'F'    [-3.14144611359,3.1415913105]
tau1_met_dphi                 tau1_met_dphi                 tau1_met_dphi                 tau1_met_dphi                                                   'F'    [-3.14137792587,3.14126992226]
tau1lep1_met_dphi             tau1lep1_met_dphi             tau1lep1_met_dphi             tau1lep1_met_dphi                                               'F'    [-3.14146351814,3.14153146744]
NSpec 2
njet                          njet                          njet                          njet                                                            'F'    [3,12]
nbjet                         nbjet                         nbjet                         nbjet                                                           'F'    [0,6]


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDTNode
   
#ifndef BDTNode__def
#define BDTNode__def
   
class BDTNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDTNode ( BDTNode* left,BDTNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDTNode();

   // test event if it descends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDTNode* GetRight( void )  {return fRight; };

   // test event if it descends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDTNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDTNode*   fLeft;     // pointer to the left daughter node
   BDTNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value applied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDTNode::~BDTNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDTNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDTNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT : public IClassifierReader {

 public:

   // constructor
   ReadBDT( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDT" ),
        fNvars( 11 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "lepton1_pt", "met_pt", "tau1_pt", "jet_ht", "jetlepmet_ht", "lep1met_pt", "lep1tau1_pt", "tau1_lep1_dr", "lep1_met_dphi", "tau1_met_dphi", "tau1lep1_met_dphi" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;
      fVmin[8] = 0;
      fVmax[8] = 0;
      fVmin[9] = 0;
      fVmax[9] = 0;
      fVmin[10] = 0;
      fVmax[10] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[11];
   double fVmax[11];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[11];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDTNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDTNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDTNode*)current->GetRight();
         else current=(BDTNode*)current->GetLeft();
      }
      myMVA += current->GetResponse();
   }
   return 2.0/(1.0+exp(-2.0*myMVA))-1.0;
};

void ReadBDT::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.485511,-0.0103719) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.626944,0.078592) , 
2, 38.7064, 1, 0, 0.53212,0.0321195) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.718829,0.124547) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.619755,0.074654) , 
4, 320.666, 1, 0, 0.660714,0.160714) , 
2, 45.9627, 1, 0, 0.601255,0.101255) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.557493,0.0381236) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.489748,-0.00730464) , 
7, 0.902989, 1, 0, 0.520334,0.020334) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.424041,-0.0583337) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.303399,-0.176166) , 
4, 652.639, 1, 0, 0.388912,-0.111087) , 
7, 1.32985, 1, 0, 0.417335,-0.0826654) , 
4, 410.486, 1, 0, 0.5,-4.28684e-15)    );
  // itree = 1
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.598297,0.0561978) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.47182,-0.0268954) , 
4, 313.624, 1, 0, 0.53212,0.022673) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.70318,0.0863708) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.606314,0.0438565) , 
4, 343.12, 1, 0, 0.660714,0.113247) , 
2, 45.9627, 1, 0, 0.601255,0.0713676) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.328118,-0.121505) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.35784,-0.0791606) , 
7, 2.56987, 1, 0, 0.342036,-0.117962) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.489542,0.0136703) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.368533,-0.0773816) , 
9, 1.06452, 1, 0, 0.441403,-0.0256539) , 
9, -1.42768, 1, 0, 0.417335,-0.0480122) , 
4, 410.486, 1, 0, 0.5,0.00564462)    );
  // itree = 2
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.566539,0.0108712) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.725958,0.101915) , 
8, -0.597103, 1, 0, 0.627135,0.0773865) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.453529,-0.0453754) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.627577,0.0303699) , 
2, 44.061, 1, 0, 0.554221,0.00194472) , 
8, 0.85685, 1, 0, 0.601255,0.0506093) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.386124,-0.0466118) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.525412,0.0550145) , 
8, -0.233688, 1, 0, 0.441665,-0.00284733) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.376747,-0.0543524) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.314986,-0.123227) , 
9, 0.285107, 1, 0, 0.355755,-0.0902193) , 
8, 0.856709, 1, 0, 0.417335,-0.0275917) , 
4, 410.486, 1, 0, 0.5,0.00755676)    );
  // itree = 3
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.415478,-0.052424) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.604666,0.0468097) , 
2, 40.6254, 1, 0, 0.497027,-0.00708353) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.59067,0.052509) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.525605,0.0166015) , 
8, 0.856688, 1, 0, 0.569113,0.0609088) , 
2, 59.2204, 1, 0, 0.527272,0.0214441) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.375245,-0.0346145) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.300622,-0.0983574) , 
8, 0.285464, 1, 0, 0.345789,-0.0657705) , 
4, 676.848, 1, 0, 0.5,0.00833803)    );
  // itree = 4
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.673193,0.0565991) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.56572,0.021365) , 
4, 296.12, 1, 0, 0.597311,0.0488655) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.35848,-0.0562981) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.431574,0.00172469) , 
8, -0.8569, 1, 0, 0.407013,-0.0205999) , 
3, 346.936, 1, 0, 0.535673,0.0263653) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.554392,0.0359245) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.421176,-0.0296276) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.293271,-0.0980498) , 
1, 144.643, 1, 0, 0.395369,-0.0502429) , 
7, 1.29133, 1, 0, 0.426697,-0.0298637) , 
1, 75.8574, 1, 0, 0.5,0.00795896)    );
  // itree = 5
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.403784,-0.0708622) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.523562,0.0200108) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.437965,-0.040854) , 
9, 1.32424, 1, 0, 0.488252,-0.00477447) , 
9, -0.856716, 1, 0, 0.46697,-0.025317) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.653022,0.0819207) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.413776,-0.0312356) , 
0, 81.0429, 1, 0, 0.584527,0.0812837) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.476744,-0.00778568) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.397426,-0.0661404) , 
9, 0.856702, 1, 0, 0.455892,-0.0283726) , 
8, 0.597261, 1, 0, 0.515728,0.0226351) , 
8, -0.856705, 1, 0, 0.5,0.00716718)    );
  // itree = 6
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.612516,0.0317192) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.554136,-0.00072427) , 
9, 1.42781, 1, 0, 0.597311,0.0351337) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.441237,0.00687893) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.335052,-0.0457615) , 
8, 0.856466, 1, 0, 0.407013,-0.0101678) , 
3, 346.936, 1, 0, 0.535673,0.0204603) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.394463,-0.0384907) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.343972,-0.0744584) , 
8, 0.28355, 1, 0, 0.370136,-0.0637147) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.523595,0.0325812) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.377986,-0.0421254) , 
9, 0.960994, 1, 0, 0.454392,0.000664031) , 
9, -0.856475, 1, 0, 0.426697,-0.0204975) , 
1, 75.8574, 1, 0, 0.5,0.00705293)    );
  // itree = 7
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.461717,-0.0273608) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.563877,0.0192868) , 
2, 54.5903, 1, 0, 0.508401,-0.00676787) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.30053,-0.0707811) , 
3, 425.858, 1, 0, 0.46697,-0.0199636) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.653022,0.0583061) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.413776,-0.0179461) , 
0, 81.0429, 1, 0, 0.584527,0.0577832) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.518845,0.0104456) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.407396,-0.0322432) , 
1, 47.3891, 1, 0, 0.455892,-0.015693) , 
8, 0.597261, 1, 0, 0.515728,0.0184852) , 
8, -0.856705, 1, 0, 0.5,0.00608275)    );
  // itree = 8
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.485351,-0.011112) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.275387,-0.11123) , 
4, 409.51, 1, 0, 0.382484,-0.0621214) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.508497,-0.00764802) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.566233,0.0253972) , 
9, -1.99908, 1, 0, 0.556502,0.0282663) , 
2, 38.9109, 1, 0, 0.502847,0.000397285) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.47453,0.0430134) , 
2, 128.021, 1, 0, 0.5,0.00589498)    );
  // itree = 9
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.485664,-0.015109) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.358958,-0.078755) , 
5, 92.2407, 1, 0, 0.4313,-0.0487763) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.582775,0.0406428) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.466934,-0.0116923) , 
9, 0.648808, 1, 0, 0.502352,0.00781619) , 
9, -0.28576, 1, 0, 0.47732,-0.0121221) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.727548,0.0856335) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.56807,0.0319903) , 
7, 2.15863, 1, 0, 0.655004,0.0957008) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.533958,0.00903263) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.417672,-0.0204071) , 
1, 46.9747, 1, 0, 0.466239,-0.00912996) , 
8, 0.337614, 1, 0, 0.517306,0.01923) , 
8, -0.28552, 1, 0, 0.5,0.00566099)    );
  // itree = 10
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.699699,0.044836) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.625677,0.0159495) , 
1, 30.4069, 1, 0, 0.650721,0.0388375) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.434956,-0.0156355) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.522157,0.0187212) , 
2, 65.6588, 1, 0, 0.471505,-0.000429622) , 
4, 328.088, 1, 0, 0.516531,0.00943575) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.334785,-0.0347653) , 
3, 598.854, 1, 0, 0.5,0.0053149)    );
  // itree = 11
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.420515,-0.0288268) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.502221,0.00175892) , 
8, -0.285604, 1, 0, 0.474199,-0.0102613) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.702887,0.0644777) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.536169,0.0202031) , 
7, 1.27061, 1, 0, 0.579408,0.046939) , 
9, -0.597197, 1, 0, 0.517575,0.0133215) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.412437,-0.0304669) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.558661,0.0198137) , 
10, 0.286077, 1, 0, 0.49239,-0.00149927) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.394874,-0.0498353) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.440249,-0.00683473) , 
10, 1.86651, 1, 0, 0.415901,-0.0344817) , 
8, 0.285209, 1, 0, 0.466339,-0.0127327) , 
9, 0.856671, 1, 0, 0.5,0.00438437)    );
  // itree = 12
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.530412,0.0128849) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.467379,-0.0078275) , 
8, 1.42804, 1, 0, 0.516146,0.0110538) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.349262,-0.0381599) , 
1, 151.518, 1, 0, 0.506332,0.00805597) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.44672,-0.0256187) , 
7, 3.20774, 1, 0, 0.5,0.00385015)    );
  // itree = 13
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.505011,-0.00257237) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.595872,0.0304809) , 
8, -1.06488, 1, 0, 0.53023,0.00939693) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.455101,-0.0126498) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.31541,-0.0662056) , 
1, 110.745, 1, 0, 0.415698,-0.0306017) , 
1, 58.1619, 1, 0, 0.47732,-0.00908135) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.727548,0.0577673) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.56807,0.0192905) , 
7, 2.15863, 1, 0, 0.655004,0.0596719) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.522907,0.0113219) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.440991,-0.0123065) , 
10, 0.285625, 1, 0, 0.466239,-0.00577523) , 
8, 0.337614, 1, 0, 0.517306,0.0119302) , 
8, -0.28552, 1, 0, 0.5,0.00283654)    );
  // itree = 14
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.436491,0.00213133) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.354857,-0.0457748) , 
7, 1.80573, 1, 0, 0.382484,-0.0323369) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.5748,0.0166111) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.52015,-0.00210301) , 
9, 0.856671, 1, 0, 0.556502,0.01433) , 
2, 38.9109, 1, 0, 0.502847,-5.8687e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.47453,0.0233663) , 
2, 128.021, 1, 0, 0.5,0.00291416)    );
  // itree = 15
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.569071,0.0202535) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.49556,-0.0114931) , 
0, 44.4825, 1, 0, 0.521686,0.000243432) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.425204,-0.000537229) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.526369,0.0669256) , 
7, 2.60776, 1, 0, 0.477292,0.0466702) , 
0, 109.665, 1, 0, 0.516531,0.00563487) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.334785,-0.027805) , 
3, 598.854, 1, 0, 0.5,0.0025928)    );
  // itree = 16
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.420307,-0.0181526) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.528295,0.0124714) , 
8, -0.235307, 1, 0, 0.477445,-0.00144002) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.44418,-0.0301577) , 
8, 1.42562, 1, 0, 0.46912,-0.0103586) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.53148,-0.00105942) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.589544,0.0259243) , 
10, -0.284795, 1, 0, 0.568045,0.0221878) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.461293,-0.00816682) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.47323,0.0113077) , 
2, 96.9685, 1, 0, 0.463721,-0.00507842) , 
9, 0.960634, 1, 0, 0.516171,0.00862991) , 
9, -0.856779, 1, 0, 0.5,0.00210368)    );
  // itree = 17
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.666258,0.024822) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.529722,-0.0075157) , 
4, 294.632, 1, 0, 0.563992,0.00160368) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.555566,0.0462114) , 
0, 105.586, 1, 0, 0.563083,0.00846702) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.465369,0.0257708) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.388644,-0.0194799) , 
0, 46.9933, 1, 0, 0.421241,0.00079638) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.340474,-0.0343116) , 
0, 92.3042, 1, 0, 0.400017,-0.00887779) , 
3, 346.936, 1, 0, 0.5,0.00175706)    );
  // itree = 18
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.46978,-0.00645708) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.631069,0.0309363) , 
8, -0.64902, 1, 0, 0.531159,0.0111613) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.501827,0.0008938) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.353325,-0.0269796) , 
1, 93.7526, 1, 0, 0.472544,-0.00472194) , 
8, 0.285665, 1, 0, 0.506332,0.00443381) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.44672,-0.0168511) , 
7, 3.20774, 1, 0, 0.5,0.00178729)    );
  // itree = 19
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.474813,0.00323655) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.421012,-0.0273046) , 
10, -1.42792, 1, 0, 0.449101,-0.0130611) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.528769,0.00324878) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.521501,0.0373209) , 
0, 105.586, 1, 0, 0.528073,0.00863239) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.446091,-0.0275663) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.359149,-0.00140159) , 
7, 2.1824, 1, 0, 0.405857,-0.0182216) , 
5, 167.582, 1, 0, 0.5109,0.00485914) , 
9, -1.99908, 1, 0, 0.5,0.00169827)    );
  // itree = 20
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.58554,0.0174889) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.373572,-0.0219624) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.543469,0.00246701) , 
2, 38.0276, 1, 0, 0.49462,-0.00464344) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.488922,0.0287658) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.480484,0.0197728) , 
10, 0.285146, 1, 0, 0.485032,0.0313799) , 
2, 118.302, 1, 0, 0.493491,-0.000402957) , 
7, 0.860376, 1, 0, 0.5,0.00127851)    );
  // itree = 21
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.628216,0.0181423) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.583265,0.00622279) , 
9, 1.42783, 1, 0, 0.61608,0.0211618) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.570834,-0.0161951) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.461152,0.00670119) , 
4, 406.547, 1, 0, 0.515893,-0.00676184) , 
3, 232.427, 1, 0, 0.563083,0.00639085) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.485486,0.0257556) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.392484,-0.0118718) , 
4, 517.249, 1, 0, 0.414745,-0.00215412) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.31792,-0.0369611) , 
4, 873.02, 1, 0, 0.400017,-0.00718496) , 
3, 346.936, 1, 0, 0.5,0.00113895)    );
  // itree = 22
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.531679,0.00219285) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.43318,-0.0251742) , 
1, 39.1639, 1, 0, 0.463949,-0.02004) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.543116,0.0399104) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.406722,-0.0149046) , 
8, -2.10292, 1, 0, 0.472668,0.0174354) , 
0, 70.1835, 1, 0, 0.46697,-0.00705267) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.653022,0.0236901) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.413776,-0.0179168) , 
0, 81.0429, 1, 0, 0.584527,0.0173006) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.457632,-0.00881744) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.448626,0.0137247) , 
0, 92.306, 1, 0, 0.455892,-0.0055542) , 
8, 0.597261, 1, 0, 0.515728,0.00507696) , 
8, -0.856705, 1, 0, 0.5,0.00116429)    );
  // itree = 23
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.621179,0.0115538) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.407456,-0.0129055) , 
4, 339.137, 1, 0, 0.471696,-0.00547054) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.536832,0.0103336) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.494211,-0.00414627) , 
6, 104.517, 1, 0, 0.523292,0.00752896) , 
10, -0.856738, 1, 0, 0.506332,0.00325588) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.44672,-0.0120461) , 
7, 3.20774, 1, 0, 0.5,0.0013675)    );
  // itree = 24
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.605829,0.0289126) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.446451,-0.00979992) , 
10, 0.856532, 1, 0, 0.560032,0.024336) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.452963,-0.0352251) , 
6, 140.861, 1, 0, 0.534043,0.00819274) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.564015,-0.00010558) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.345496,-0.0222873) , 
3, 318.474, 1, 0, 0.48195,-0.00884058) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.490741,0.0322882) , 
2, 118.302, 1, 0, 0.483085,-0.00235959) , 
7, 1.79932, 1, 0, 0.5,0.00114314)    );
  // itree = 25
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.550401,-0.0022705) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.340373,-0.0300598) , 
3, 273.521, 1, 0, 0.431263,-0.0188607) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.557649,0.0124565) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.460393,-0.0116682) , 
8, 1.27216, 1, 0, 0.514,0.00232122) , 
8, -0.285604, 1, 0, 0.485547,-0.00496328) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.672657,0.0337335) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.535777,0.00862035) , 
7, 1.70495, 1, 0, 0.589051,0.0254998) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.514033,0.00429034) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.445665,-0.00742193) , 
5, 84.4611, 1, 0, 0.475039,-0.00260703) , 
9, 0.648997, 1, 0, 0.511514,0.00638508) , 
9, -0.285629, 1, 0, 0.5,0.00135303)    );
  // itree = 26
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.58554,0.0133843) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.515775,0.00679479) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.481431,-0.00363251) , 
6, 74.6872, 1, 0, 0.498459,0.00207299) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.421711,-0.0243347) , 
7, 3.42116, 1, 0, 0.493491,0.000106637) , 
7, 0.860376, 1, 0, 0.5,0.00132942)    );
  // itree = 27
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.533955,0.0077212) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.613079,0.0348512) , 
8, -0.286483, 1, 0, 0.579149,0.0307552) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.545012,0.00290559) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.479558,-0.0107798) , 
7, 1.79932, 1, 0, 0.502188,-0.00745747) , 
0, 35.6642, 1, 0, 0.514769,-0.0012106) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.553781,0.0257935) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.345783,-0.0121244) , 
3, 330.028, 1, 0, 0.441554,0.00962221) , 
0, 92.3025, 1, 0, 0.5,0.000974659)    );
  // itree = 28
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.478821,-0.00539112) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.446957,0.0194935) , 
0, 110.367, 1, 0, 0.474848,-0.00302457) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.72434,0.0298474) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.567568,0.00540994) , 
7, 2.15863, 1, 0, 0.653146,0.0252076) , 
8, -0.337467, 1, 0, 0.522077,0.0044537) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.521199,0.0017064) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.42091,-0.0300414) , 
10, 0.59716, 1, 0, 0.48539,-0.0111171) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.427543,-0.00619356) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.47399,0.021025) , 
8, 2.10307, 1, 0, 0.447505,0.0071962) , 
10, 1.42799, 1, 0, 0.47021,-0.00377901) , 
8, 0.285665, 1, 0, 0.5,0.000949527)    );
  // itree = 29
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.426763,-0.0152281) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.56155,0.00569688) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.437788,-0.00666034) , 
1, 56.3181, 1, 0, 0.49824,-0.000270252) , 
8, -1.42792, 1, 0, 0.485547,-0.00343726) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.607147,0.00123206) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.572031,0.0231631) , 
1, 58.3055, 1, 0, 0.589051,0.0168217) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.503054,0.00276458) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.420342,-0.00945357) , 
8, 0.285209, 1, 0, 0.475039,-0.00141091) , 
9, 0.648997, 1, 0, 0.511514,0.00442217) , 
9, -0.285629, 1, 0, 0.5,0.000937165)    );
  // itree = 30
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.452925,-0.00281994) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.260205,-0.0425656) , 
3, 328.737, 1, 0, 0.382484,-0.0151567) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.583805,0.00225386) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.399897,0.0226141) , 
4, 636.862, 1, 0, 0.556502,0.00616753) , 
2, 38.9109, 1, 0, 0.502847,-0.000407303) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.47453,0.00942802) , 
2, 128.021, 1, 0, 0.5,0.000805264)    );
  // itree = 31
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.599268,0.0183257) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.504096,0.000370747) , 
7, 1.33706, 1, 0, 0.518964,0.00410827) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.428505,-0.0167968) , 
6, 149.207, 1, 0, 0.509772,0.00172843) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.344764,-0.0139476) , 
1, 151.518, 1, 0, 0.5,0.000826532)    );
  // itree = 32
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.636736,0.0193531) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.62355,0.00256769) , 
6, 37.6438, 1, 0, 0.626623,0.00916334) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.558736,-0.0130309) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.511118,-0.043445) , 
9, 0.284468, 1, 0, 0.537524,-0.0345066) , 
4, 362.055, 1, 0, 0.601255,-0.00327031) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.501479,0.0269681) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.425025,-0.000602961) , 
1, 74.0292, 1, 0, 0.463268,0.017297) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.444266,0.00314898) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.335307,-0.0117015) , 
7, 2.17371, 1, 0, 0.388791,-0.0042794) , 
3, 368.569, 1, 0, 0.417335,0.0039899) , 
4, 410.486, 1, 0, 0.5,0.000726703)    );
  // itree = 33
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.47451,-0.0299156) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.531469,0.00478809) , 
5, 27.0104, 1, 0, 0.527495,0.00307341) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.343108,-0.0355496) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.463083,0.00539065) , 
2, 56.7234, 1, 0, 0.395296,-0.0168272) , 
5, 147.605, 1, 0, 0.502847,-0.000636924) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.47453,0.0103192) , 
2, 128.021, 1, 0, 0.5,0.000707142)    );
  // itree = 34
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.49185,0.00486657) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.4128,-0.0145044) , 
10, 0.285907, 1, 0, 0.474746,0.00106375) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.437072,-0.0274887) , 
8, 1.9965, 1, 0, 0.46912,-0.00402345) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.483505,0.0145833) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.50356,-0.00882962) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.525955,0.00463445) , 
10, -0.128822, 1, 0, 0.519978,0.0013843) , 
10, -1.99827, 1, 0, 0.516171,0.0031632) , 
9, -0.856779, 1, 0, 0.5,0.000693194)    );
  // itree = 35
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.574714,0.0137071) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.485886,-0.00571488) , 
7, 2.17158, 1, 0, 0.519625,0.00228867) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.447802,0.0172821) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.489776,-0.0196637) , 
10, -1.47989, 1, 0, 0.477841,-0.0108597) , 
6, 104.517, 1, 0, 0.507474,-0.0015348) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.456053,-0.0176374) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.405837,0.00904605) , 
5, 66.3339, 1, 0, 0.431884,-0.00647898) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.520469,0.0227938) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.501816,0.00349911) , 
7, 2.86666, 1, 0, 0.510805,0.0164763) , 
7, 2.26879, 1, 0, 0.47741,0.00676277) , 
10, 1.42799, 1, 0, 0.5,0.000528095)    );
  // itree = 36
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.506659,0.0049462) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.445353,-0.00609027) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.393476,-0.018275) , 
10, -1.9991, 1, 0, 0.417429,-0.0140187) , 
6, 58.5703, 1, 0, 0.449101,-0.00690133) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.541958,0.00626882) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.392761,-0.020239) , 
1, 115.894, 1, 0, 0.523665,0.00446337) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.427495,-0.0223779) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.476228,0.00499292) , 
8, -0.2859, 1, 0, 0.453738,-0.0088667) , 
9, 2.20668, 1, 0, 0.5109,0.00203004) , 
9, -1.99908, 1, 0, 0.5,0.000454678)    );
  // itree = 37
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.671337,0.0151423) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.614496,-0.000226294) , 
4, 262.992, 1, 0, 0.626623,0.0042858) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.558736,-0.00942506) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.511118,-0.0301097) , 
9, 0.284468, 1, 0, 0.537524,-0.0243541) , 
4, 362.055, 1, 0, 0.601255,-0.00386851) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.381711,-0.00106449) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.529965,0.0173964) , 
2, 52.1899, 1, 0, 0.463268,0.0124473) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.424981,-0.00820102) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.351108,0.00787645) , 
4, 653.615, 1, 0, 0.388791,-0.00106852) , 
3, 368.569, 1, 0, 0.417335,0.00411152) , 
4, 410.486, 1, 0, 0.5,0.000524792)    );
  // itree = 38
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.505319,0.00346188) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.473285,-0.00929112) , 
6, 66.5324, 1, 0, 0.486254,-0.00484174) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.551753,0.0106127) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.497268,-0.00146444) , 
5, 68.184, 1, 0, 0.513298,0.00289152) , 
9, -0.28576, 1, 0, 0.501159,-0.000579512) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.487864,0.00845771) , 
10, 2.57035, 1, 0, 0.5,0.000400642)    );
  // itree = 39
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.564503,-5.19352e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.589544,0.0248692) , 
5, 60.5583, 1, 0, 0.579149,0.0185083) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.50383,-0.00564286) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.48476,0.00923008) , 
2, 128.021, 1, 0, 0.502188,-0.0053947) , 
0, 35.6642, 1, 0, 0.514769,-0.00148712) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.400562,-0.0141788) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.535875,0.0266239) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.38578,0.00439354) , 
1, 58.7237, 1, 0, 0.464346,0.0205213) , 
7, 2.16648, 1, 0, 0.441554,0.00747432) , 
0, 92.3025, 1, 0, 0.5,0.00032063)    );
  // itree = 40
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.500111,0.00164522) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.474416,-0.0131137) , 
8, 1.42805, 1, 0, 0.497078,-0.00017387) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.603266,0.0205766) , 
10, -0.026154, 1, 0, 0.510217,0.00314169) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.570291,0.00110537) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.388259,-0.0333472) , 
5, 124.947, 1, 0, 0.500534,-0.0127756) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.474837,-0.00273836) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.49024,0.0228672) , 
0, 92.3042, 1, 0, 0.477864,0.00285974) , 
10, 1.32415, 1, 0, 0.486811,-0.00331073) , 
10, 0.285625, 1, 0, 0.5,0.000325169)    );
  // itree = 41
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.430864,-0.0243288) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.493925,0.000968291) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.542076,0.0193108) , 
0, 70.1995, 1, 0, 0.51324,0.0109675) , 
7, 2.17054, 1, 0, 0.480394,-0.00502654) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.559847,0.013238) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.472689,-0.0117991) , 
6, 129.095, 1, 0, 0.537239,0.00866097) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.470817,-0.00838402) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.489453,0.0185033) , 
2, 118.302, 1, 0, 0.473705,-0.00482145) , 
7, 2.26879, 1, 0, 0.505908,0.00201241) , 
8, -1.42789, 1, 0, 0.5,0.000382432)    );
  // itree = 42
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.585521,0.0152459) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.522829,-0.00110455) , 
1, 20.0276, 1, 0, 0.53014,0.00112598) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.367029,-0.023464) , 
1, 109.273, 1, 0, 0.518578,-0.000707546) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.43065,-0.00221421) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.362233,0.0146332) , 
7, 2.1824, 1, 0, 0.392927,0.00718573) , 
5, 167.582, 1, 0, 0.5,0.000459525)    );
  // itree = 43
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.58554,0.00808494) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.533398,0.0261093) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.505495,0.000817349) , 
6, 20.491, 1, 0, 0.508951,0.00508888) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.468756,0.0116771) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.478961,-0.00860605) , 
10, -1.99918, 1, 0, 0.477252,-0.00613856) , 
6, 74.6872, 1, 0, 0.493491,-0.000386988) , 
7, 0.860376, 1, 0, 0.5,0.000363436)    );
  // itree = 44
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.428192,-0.0170539) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.50265,0.0059837) , 
7, 2.10091, 1, 0, 0.45916,-0.00869179) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.564187,0.0110942) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.444863,-0.0075805) , 
8, 1.06428, 1, 0, 0.522693,0.00583499) , 
8, -1.42806, 1, 0, 0.508859,0.00267171) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.521603,0.0132978) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.470242,-0.0154759) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.47218,0.00410646) , 
8, 0.856882, 1, 0, 0.470925,-0.0102318) , 
10, -1.9989, 1, 0, 0.481053,-0.00477008) , 
7, 2.73827, 1, 0, 0.5,0.000300816)    );
  // itree = 45
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.463241,-0.00362808) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.616853,0.0107497) , 
8, -0.649004, 1, 0, 0.52257,0.00251884) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.42435,-0.0206114) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.479588,-0.000841872) , 
9, -1.99855, 1, 0, 0.470667,-0.00467766) , 
8, 0.285691, 1, 0, 0.501159,-0.000449813) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.487864,0.0073925) , 
10, 2.57035, 1, 0, 0.5,0.000399859)    );
  // itree = 46
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.57325,0.00939494) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.49094,-0.00390564) , 
0, 39.564, 1, 0, 0.509572,-0.00099575) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.448497,0.0254144) , 
0, 135.204, 1, 0, 0.505202,0.00119702) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.45036,-0.00598805) , 
9, 2.57012, 1, 0, 0.5,0.000406849)    );
  // itree = 47
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.478063,-0.0123977) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.542343,0.0069419) , 
5, 40.4097, 1, 0, 0.532571,0.00503348) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.416689,-0.020429) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.409361,0.000130281) , 
1, 117.173, 1, 0, 0.413087,-0.0115992) , 
5, 147.605, 1, 0, 0.508859,0.00173259) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.537403,0.00509451) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.469157,-0.0149656) , 
5, 76.5909, 1, 0, 0.500353,-0.0067545) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.382405,0.0165244) , 
5, 167.859, 1, 0, 0.481053,-0.00275552) , 
7, 2.73827, 1, 0, 0.5,0.000302713)    );
  // itree = 48
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.620605,0.00976823) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.605702,-0.00198872) , 
6, 47.3805, 1, 0, 0.61044,0.00250306) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.554281,-0.0192192) , 
3, 270.612, 1, 0, 0.601255,-0.00206461) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.492641,0.0197479) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.41147,-0.000451892) , 
4, 454.514, 1, 0, 0.428281,0.00477572) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.315117,-0.0235997) , 
4, 894.786, 1, 0, 0.417335,0.00223518) , 
4, 410.486, 1, 0, 0.5,0.000302585)    );
  // itree = 49
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.560979,0.0156782) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.540992,-0.000909104) , 
6, 29.1029, 1, 0, 0.543443,0.0015505) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.392433,-0.0202833) , 
4, 579.985, 1, 0, 0.527272,-0.000969475) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.365832,0.0223236) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.324039,-0.00930043) , 
3, 641.246, 1, 0, 0.345789,0.00744096) , 
4, 676.848, 1, 0, 0.5,0.000294389)    );
  // itree = 50
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.585468,-0.0020303) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.571181,0.0119402) , 
0, 82.1982, 1, 0, 0.583017,0.000568716) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.426023,-0.017543) , 
4, 454.229, 1, 0, 0.563083,-0.00210329) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.456924,0.0151287) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.331639,-0.0117642) , 
0, 92.3042, 1, 0, 0.428348,0.0106677) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.348725,-0.0175187) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.346442,0.00605973) , 
0, 79.4799, 1, 0, 0.347791,-0.00828347) , 
7, 2.61942, 1, 0, 0.400017,0.00400271) , 
3, 346.936, 1, 0, 0.5,0.000258859)    );
  // itree = 51
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.632942,0.00671364) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.602837,-0.00251889) , 
3, 190.794, 1, 0, 0.617087,0.00259178) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.592151,0.000153913) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.52491,-0.023207) , 
0, 50.0894, 1, 0, 0.56376,-0.0128505) , 
3, 245.527, 1, 0, 0.601255,-0.00199283) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.404373,0.0238233) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.432126,-0.000285294) , 
6, 39.0498, 1, 0, 0.428281,0.00345641) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.315117,-0.0115833) , 
4, 894.786, 1, 0, 0.417335,0.00211586) , 
4, 410.486, 1, 0, 0.5,0.000269155)    );
  // itree = 52
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.487447,-0.00175795) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.532416,0.00667032) , 
10, -0.285568, 1, 0, 0.513452,0.00388426) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.478728,-0.00915798) , 
7, 2.52485, 1, 0, 0.508859,0.00189513) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.549524,0.0100319) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.50893,-0.010253) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.386055,0.00292641) , 
1, 76.3329, 1, 0, 0.465672,-0.00724156) , 
8, -1.99883, 1, 0, 0.481053,-0.00347512) , 
7, 2.73827, 1, 0, 0.5,0.000184214)    );
  // itree = 53
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.583569,0.00993309) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.492733,-0.00504281) , 
0, 46.9918, 1, 0, 0.532828,0.00212452) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.447575,-0.0264645) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.457009,0.00384343) , 
0, 46.995, 1, 0, 0.452886,-0.0114706) , 
8, 1.42804, 1, 0, 0.514769,-0.000946594) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.491787,0.0132681) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.383418,-0.018266) , 
8, -0.960296, 1, 0, 0.428095,-0.00498776) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.473209,0.0219995) , 
8, 0.856721, 1, 0, 0.441554,0.00448205) , 
0, 92.3025, 1, 0, 0.5,0.000148503)    );
  // itree = 54
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.518058,0.00270668) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.404237,-0.0142355) , 
1, 58.1619, 1, 0, 0.467486,-0.0052035) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.54745,0.0157358) , 
8, -0.545404, 1, 0, 0.47732,-0.00220527) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.69188,-0.00710671) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.609838,0.030445) , 
1, 77.5433, 1, 0, 0.655004,0.0131405) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.522907,0.00509541) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.440991,-0.00478349) , 
10, 0.285625, 1, 0, 0.466239,-0.00189398) , 
8, 0.337614, 1, 0, 0.517306,0.0021733) , 
8, -0.28552, 1, 0, 0.5,0.000278283)    );
  // itree = 55
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.538473,0.00542244) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.505909,-0.00871173) , 
2, 90.3227, 1, 0, 0.532571,0.00361586) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.37259,-0.0165654) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.443261,0.00149175) , 
9, -0.284907, 1, 0, 0.413087,-0.00624747) , 
5, 147.605, 1, 0, 0.508859,0.00165841) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.492975,-0.00142312) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.479026,0.0122334) , 
0, 70.191, 1, 0, 0.487057,0.00532306) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.441941,-0.0171431) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.511054,0.0020259) , 
10, 1.58375, 1, 0, 0.475852,-0.00897742) , 
10, -0.285588, 1, 0, 0.481053,-0.00233928) , 
7, 2.73827, 1, 0, 0.5,0.000384774)    );
  // itree = 56
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.560979,0.012097) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.540992,-0.000583063) , 
6, 29.1029, 1, 0, 0.543443,0.00132711) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.392433,-0.0137693) , 
4, 579.985, 1, 0, 0.527272,-0.000399576) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.362623,0.0109955) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.315117,-0.00759799) , 
4, 894.806, 1, 0, 0.345789,0.00464689) , 
4, 676.848, 1, 0, 0.5,0.000358774)    );
  // itree = 57
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.650353,0.012044) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.570372,-0.00134379) , 
1, 20.025, 1, 0, 0.579912,0.000411437) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.400092,-0.017409) , 
1, 109.273, 1, 0, 0.563083,-0.00143009) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.443821,0.0111188) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.396888,-0.00266318) , 
5, 148.348, 1, 0, 0.428348,0.00751759) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.339013,-0.014333) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.358478,0.00577521) , 
10, 0.285515, 1, 0, 0.347791,-0.00533506) , 
7, 2.61942, 1, 0, 0.400017,0.00299742) , 
3, 346.936, 1, 0, 0.5,0.000282725)    );
  // itree = 58
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.462232,-0.0128143) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.542164,0.0031484) , 
10, -2.57028, 1, 0, 0.533665,0.00193198) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.507495,0.00245386) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.449297,-0.0186327) , 
10, 0.287237, 1, 0, 0.483224,-0.00732834) , 
5, 106.711, 1, 0, 0.518578,-0.000837727) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.415119,0.000953497) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.352427,0.0170869) , 
8, 0.290924, 1, 0, 0.392927,0.00663474) , 
5, 167.582, 1, 0, 0.5,0.000267124)    );
  // itree = 59
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.475775,0.00669849) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.467566,-0.00529138) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.525295,0.00132353) , 
8, -0.545439, 1, 0, 0.502866,-0.00150143) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.492751,0.0105718) , 
8, 2.57029, 1, 0, 0.502213,-0.000538411) , 
10, -2.57028, 1, 0, 0.5,0.00020232)    );
  // itree = 60
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.581294,0.00840066) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.545504,0.000521786) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.475219,-0.0125052) , 
9, 1.42781, 1, 0, 0.527499,-0.00341406) , 
1, 20.8299, 1, 0, 0.535673,-0.00122981) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.39851,0.00686617) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.362546,-0.0221117) , 
8, -1.06461, 1, 0, 0.382674,-0.00552372) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.609793,0.0225306) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.369739,-0.00271007) , 
8, 0.337567, 1, 0, 0.456448,0.00873853) , 
8, -0.285636, 1, 0, 0.426697,0.00298691) , 
1, 75.8574, 1, 0, 0.5,0.00015052)    );
  // itree = 61
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.600354,0.0114348) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.509742,-0.000829687) , 
0, 35.6642, 1, 0, 0.52458,0.00150862) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.448609,-0.018204) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.465896,-0.00179879) , 
0, 52.6608, 1, 0, 0.456521,-0.0131032) , 
8, 1.99922, 1, 0, 0.514769,-0.000597674) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.437286,-0.0115815) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.457796,0.0108581) , 
0, 118.046, 1, 0, 0.44483,-0.0037327) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.432151,0.0222197) , 
0, 148.941, 1, 0, 0.441554,0.00374866) , 
0, 92.3025, 1, 0, 0.5,0.000279094)    );
  // itree = 62
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.475775,0.00468476) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.499945,-0.00647289) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.563893,0.00823677) , 
8, -1.42792, 1, 0, 0.540652,0.00372516) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.473746,-0.00531602) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.479646,0.0167488) , 
10, 2.10306, 1, 0, 0.474407,-0.00315343) , 
5, 83.8971, 1, 0, 0.502213,-0.000266184) , 
10, -2.57028, 1, 0, 0.5,0.000242244)    );
  // itree = 63
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.482596,-0.000785421) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.612073,0.00926618) , 
10, -0.285008, 1, 0, 0.532415,0.00399644) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.468364,-0.00665132) , 
7, 3.06987, 1, 0, 0.522077,0.00207047) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.622704,0.018449) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.403281,-0.00808351) , 
5, 106.056, 1, 0, 0.487526,0.00403549) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.413277,-0.0207434) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.473411,-0.000479138) , 
7, 1.79932, 1, 0, 0.456627,-0.00721813) , 
8, 1.32424, 1, 0, 0.47021,-0.00227114) , 
8, 0.285665, 1, 0, 0.5,0.000222504)    );
  // itree = 64
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.480704,-0.0144339) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.552428,-0.00116983) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.493193,0.00744153) , 
0, 92.3025, 1, 0, 0.540919,0.000584912) , 
9, -2.57023, 1, 0, 0.535673,-0.000969275) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.448197,0.00417749) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.437869,-0.0150127) , 
8, 0.129723, 1, 0, 0.44556,-0.000732727) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.372025,0.0135392) , 
8, 0.856688, 1, 0, 0.426697,0.0031402) , 
1, 75.8574, 1, 0, 0.5,0.000375945)    );
  // itree = 65
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.463838,-0.00936873) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.487119,0.0234316) , 
5, 80.5946, 1, 0, 0.473241,0.00471281) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.579549,0.0108376) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.468266,-0.0142449) , 
6, 140.861, 1, 0, 0.552009,0.0059644) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.481995,-0.00679759) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.476095,0.00487894) , 
9, 1.42782, 1, 0, 0.480313,-0.00424433) , 
7, 1.79932, 1, 0, 0.505237,-0.000695374) , 
10, -1.9991, 1, 0, 0.5,0.000189863)    );
  // itree = 66
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.483852,0.000463572) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.647066,0.0148488) , 
10, -0.337685, 1, 0, 0.529734,0.00570579) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.469239,-0.0176349) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.478395,0.00100866) , 
7, 2.85415, 1, 0, 0.475857,-0.00496121) , 
7, 2.61284, 1, 0, 0.510217,0.00184167) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.493919,-0.0143076) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.485171,-0.00169073) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.486078,0.0101356) , 
8, 1.99917, 1, 0, 0.485373,0.00123779) , 
7, 1.32985, 1, 0, 0.486811,-0.0018644) , 
10, 0.285625, 1, 0, 0.5,0.000223952)    );
  // itree = 67
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.58554,0.00492121) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.498796,-0.00300567) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.431145,0.0204943) , 
0, 135.204, 1, 0, 0.49462,-0.00201616) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.488922,0.0146381) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.480484,0.00626541) , 
10, 0.285146, 1, 0, 0.485032,0.0134407) , 
2, 118.302, 1, 0, 0.493491,-0.000196653) , 
7, 0.860376, 1, 0, 0.5,0.000244083)    );
  // itree = 68
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.53228,0.000402742) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.521351,0.0175123) , 
0, 67.7931, 1, 0, 0.530177,0.00484345) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.526736,-0.0138943) , 
5, 76.2785, 1, 0, 0.529718,0.00190605) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.488291,0.0167794) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.477878,-0.00146965) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.455544,-0.0186335) , 
2, 128.021, 1, 0, 0.475406,-0.00396003) , 
10, -1.99826, 1, 0, 0.476835,-0.00124296) , 
5, 83.8971, 1, 0, 0.5,0.000136424)    );
  // itree = 69
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.58554,0.00410016) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.521349,0.00724951) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.47004,-0.00935182) , 
8, 1.42811, 1, 0, 0.508951,0.00401357) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.477228,-0.00807957) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.477348,0.0111383) , 
2, 118.304, 1, 0, 0.477252,-0.00472236) , 
6, 74.6872, 1, 0, 0.493491,-0.000247129) , 
7, 0.860376, 1, 0, 0.5,0.000125905)    );
  // itree = 70
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.534265,0.00448824) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.537923,-0.00508447) , 
2, 81.6568, 1, 0, 0.535032,0.00304238) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.370971,-0.00697653) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.347796,-0.00841457) , 
3, 641.246, 1, 0, 0.359261,-0.0074508) , 
4, 676.848, 1, 0, 0.508859,0.00147988) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.537839,0.0144708) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.48858,-0.00330748) , 
6, 22.5631, 1, 0, 0.504487,0.00327064) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.428556,-0.0193623) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.449195,-0.00323218) , 
10, 0.285515, 1, 0, 0.437972,-0.013738) , 
6, 61.7577, 1, 0, 0.481053,-0.00272159) , 
7, 2.73827, 1, 0, 0.5,0.000141323)    );
  // itree = 71
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.489618,-0.0143809) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.486323,-0.00332145) , 
7, 1.16384, 1, 0, 0.487679,-0.00949498) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.731372,0.0304149) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.478476,-0.00363543) , 
10, 0.337503, 1, 0, 0.565482,0.0106465) , 
10, -0.285735, 1, 0, 0.534043,0.00250759) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.448804,-0.0085096) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.545459,0.00738595) , 
2, 62.1093, 1, 0, 0.48195,-0.00315375) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.490741,0.0110602) , 
2, 118.302, 1, 0, 0.483085,-0.000940822) , 
7, 1.79932, 1, 0, 0.5,0.00020384)    );
  // itree = 72
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.45101,-0.0115756) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.499945,-0.00360716) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.563893,0.00764294) , 
8, -1.42792, 1, 0, 0.540652,0.00454391) , 
10, -2.57028, 1, 0, 0.529718,0.00227471) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.452826,0.0114327) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.485638,-0.00449346) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.435947,0.0129175) , 
8, 1.47962, 1, 0, 0.479856,-0.00287646) , 
8, -1.42783, 1, 0, 0.476835,-0.00106045) , 
5, 83.8971, 1, 0, 0.5,0.000400476)    );
  // itree = 73
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.438006,0.00556391) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.460183,-0.0115123) , 
7, 2.56987, 1, 0, 0.447745,-0.00226324) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.497859,0.0158165) , 
9, -1.8953, 1, 0, 0.461036,0.00340574) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.504689,0.00471794) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.498139,-0.0154343) , 
6, 67.7354, 1, 0, 0.500807,-0.00857283) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.568704,0.0124123) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.510221,-0.000737061) , 
9, -0.256964, 1, 0, 0.516239,0.000832435) , 
9, -0.597011, 1, 0, 0.513583,-0.000786564) , 
9, -1.42793, 1, 0, 0.5,0.000297101)    );
  // itree = 74
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.599268,0.0115444) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.504096,-0.000780273) , 
7, 1.33706, 1, 0, 0.518964,0.00141857) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.428505,-0.00610484) , 
6, 149.207, 1, 0, 0.509772,0.000570324) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.344764,-0.00567756) , 
1, 151.518, 1, 0, 0.5,0.000221013)    );
  // itree = 75
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.491513,0.00938083) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.574907,0.00459132) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.480197,-0.00257002) , 
5, 83.8971, 1, 0, 0.512454,5.11064e-05) , 
10, -2.56972, 1, 0, 0.510857,0.000946243) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.51692,-0.00427154) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.475888,-0.0173999) , 
1, 30.3934, 1, 0, 0.496655,-0.0135717) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.450344,-0.0015109) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.412649,0.0154357) , 
5, 70.9746, 1, 0, 0.431645,0.00781506) , 
1, 47.3891, 1, 0, 0.462313,-0.00227388) , 
8, 1.42804, 1, 0, 0.5,0.000226037)    );
  // itree = 76
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.553279,-0.00197493) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.505133,0.00344567) , 
1, 49.7739, 1, 0, 0.53014,0.00073965) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.367029,-0.0155495) , 
1, 109.273, 1, 0, 0.518578,-0.000454568) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.415119,-0.00239602) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.352427,0.0155898) , 
8, 0.290924, 1, 0, 0.392927,0.00374598) , 
5, 167.582, 1, 0, 0.5,0.00016651)    );
  // itree = 77
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.473457,-0.00721528) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.56378,0.0168487) , 
7, 2.13617, 1, 0, 0.525724,0.00893465) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.404938,0.00814522) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.386514,-0.0142763) , 
9, -2.51812, 1, 0, 0.394212,-0.00516112) , 
1, 56.3181, 1, 0, 0.461036,0.00200118) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.611957,0.00193969) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.513174,-0.0091516) , 
3, 255.38, 1, 0, 0.571218,-0.00323059) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.385364,0.0160457) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.437472,-0.00020773) , 
8, -1.42792, 1, 0, 0.426737,0.00347963) , 
3, 346.99, 1, 0, 0.513583,-0.000553822) , 
9, -1.42793, 1, 0, 0.5,0.000106619)    );
  // itree = 78
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.585908,0.0132694) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.490893,-0.0165416) , 
7, 1.54483, 1, 0, 0.560032,0.00651715) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.452963,-0.0101868) , 
6, 140.861, 1, 0, 0.534043,0.00206946) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.512018,0.010422) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.468083,-0.000892478) , 
9, -1.42801, 1, 0, 0.485097,0.0041946) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.448913,-0.0280806) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.488744,0.00098708) , 
10, 0.337724, 1, 0, 0.481403,-0.0050833) , 
10, -0.28547, 1, 0, 0.483085,-0.000857447) , 
7, 1.79932, 1, 0, 0.5,0.000114109)    );
  // itree = 79
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.573593,0.000725056) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.422202,-0.00848861) , 
4, 471.492, 1, 0, 0.534134,-0.00174773) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.376937,0.00772285) , 
4, 658.563, 1, 0, 0.514769,-0.00059475) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.553781,0.00957157) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.345783,-0.00446553) , 
3, 330.028, 1, 0, 0.441554,0.00339949) , 
0, 92.3025, 1, 0, 0.5,0.00021099)    );
  // itree = 80
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.639685,-0.00494513) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.59507,0.00293079) , 
0, 43.9743, 1, 0, 0.61044,0.000392873) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.554281,-0.00978862) , 
3, 270.612, 1, 0, 0.601255,-0.0017824) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.468683,0.00240029) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.447612,0.0165604) , 
5, 160.282, 1, 0, 0.463268,0.00711093) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.444266,0.00532542) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.335307,-0.00845383) , 
7, 2.17371, 1, 0, 0.388791,-0.00143314) , 
3, 368.569, 1, 0, 0.417335,0.00184143) , 
4, 410.486, 1, 0, 0.5,0.000212655)    );
  // itree = 81
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.587396,0.0155803) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.568254,-0.000183643) , 
10, -0.285481, 1, 0, 0.577191,0.00965637) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.581022,-0.00116246) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.4233,-0.0196758) , 
4, 454.229, 1, 0, 0.558591,-0.00449999) , 
6, 42.9127, 1, 0, 0.563083,-0.0010807) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.313357,-0.00593848) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.385282,0.0132353) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.437424,0.00168405) , 
8, -1.42792, 1, 0, 0.42668,0.00450397) , 
9, -1.42768, 1, 0, 0.400017,0.00215128) , 
3, 346.936, 1, 0, 0.5,0.000169611)    );
  // itree = 82
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.461575,-0.0221138) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.472012,0.0131954) , 
0, 48.2607, 1, 0, 0.465915,-0.00919548) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.507014,0.00623999) , 
0, 70.1853, 1, 0, 0.480394,-0.00319724) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.652224,0.0109538) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.454221,-0.00309809) , 
5, 112.905, 1, 0, 0.534831,0.00363697) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.448136,-0.00658825) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.487351,0.0143073) , 
0, 92.306, 1, 0, 0.455602,-0.00309519) , 
8, 1.06456, 1, 0, 0.505908,0.0011794) , 
8, -1.42789, 1, 0, 0.5,0.00016592)    );
  // itree = 83
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.480704,-0.0110432) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.546531,0.000878651) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.482812,-0.00756185) , 
9, 2.62205, 1, 0, 0.540919,0.000193955) , 
9, -2.57023, 1, 0, 0.535673,-0.000963488) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.40152,0.00891424) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.368562,-0.0152203) , 
6, 67.8539, 1, 0, 0.382674,-0.00477091) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.568528,0.0195585) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.398385,0.000160787) , 
7, 1.71945, 1, 0, 0.456448,0.00807291) , 
8, -0.285636, 1, 0, 0.426697,0.00289331) , 
1, 75.8574, 1, 0, 0.5,0.00029902)    );
  // itree = 84
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.641121,0.0152731) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.527011,-0.00915651) , 
10, 0.28539, 1, 0, 0.5967,0.00701652) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.455205,-0.0267317) , 
6, 151.476, 1, 0, 0.558983,-0.00313644) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.515596,0.000873106) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.31686,-0.0167044) , 
1, 116.73, 1, 0, 0.493202,-0.000793815) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.393725,0.0235296) , 
6, 149.207, 1, 0, 0.486073,0.00108104) , 
7, 1.32985, 1, 0, 0.5,0.000275446)    );
  // itree = 85
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.581294,0.00388569) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.545504,0.00040471) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.475219,-0.00834857) , 
9, 1.42781, 1, 0, 0.527499,-0.00221577) , 
1, 20.8299, 1, 0, 0.535673,-0.00111945) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.430248,-0.0135109) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.49813,0.00592364) , 
8, -0.287404, 1, 0, 0.468604,-0.00284912) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.423594,0.0116566) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.327432,-0.00100143) , 
9, 0.856844, 1, 0, 0.393405,0.00808882) , 
3, 329.531, 1, 0, 0.426697,0.0032464) , 
1, 75.8574, 1, 0, 0.5,0.000309697)    );
  // itree = 86
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.524567,0.00755594) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.518745,-0.000853311) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.468128,-0.012557) , 
2, 128.021, 1, 0, 0.514008,-0.00234897) , 
8, -2.57021, 1, 0, 0.514889,-0.00134963) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.416027,-0.0110303) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.508033,0.0143351) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.43088,0.00067441) , 
6, 74.8559, 1, 0, 0.467675,0.00880829) , 
10, -1.42718, 1, 0, 0.457686,0.00464182) , 
9, 1.42782, 1, 0, 0.5,0.000209855)    );
  // itree = 87
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.454117,0.00726022) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.573065,0.00221761) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.490888,-0.00358456) , 
7, 1.80692, 1, 0, 0.521062,-0.00179005) , 
9, -2.72601, 1, 0, 0.514889,-0.000852887) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.419025,-0.00617643) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.405941,-0.00292744) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.493075,0.00819664) , 
10, -0.856094, 1, 0, 0.470509,0.0065073) , 
7, 1.72801, 1, 0, 0.457686,0.00310436) , 
9, 1.42782, 1, 0, 0.5,0.000177124)    );
  // itree = 88
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.591241,0.0038788) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.516751,-0.0135598) , 
10, 1.99922, 1, 0, 0.578309,0.00112432) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.659969,0.00132372) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.645218,-0.0113784) , 
9, -0.285493, 1, 0, 0.652068,-0.00741654) , 
2, 61.9226, 1, 0, 0.601255,-0.00153271) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.463075,0.0148541) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.463332,0.00264665) , 
5, 80.8245, 1, 0, 0.463268,0.00696007) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.392444,-0.00595769) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.38424,0.00375415) , 
1, 76.1177, 1, 0, 0.388791,-0.00187794) , 
3, 368.569, 1, 0, 0.417335,0.00150928) , 
4, 410.486, 1, 0, 0.5,0.000142022)    );
  // itree = 89
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.470989,-0.00579021) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.561934,0.00387358) , 
10, -1.99917, 1, 0, 0.539658,0.00205373) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.516901,0.00104718) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.454503,-0.0104825) , 
10, 0.286099, 1, 0, 0.496763,-0.00302652) , 
5, 80.1111, 1, 0, 0.514889,-0.000879824) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.579111,-0.00240241) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.548808,0.0127735) , 
0, 46.3374, 1, 0, 0.56154,0.00870044) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.338013,-0.0101373) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.366197,0.00509523) , 
7, 2.61942, 1, 0, 0.350542,-0.00323976) , 
4, 425.093, 1, 0, 0.457686,0.00282346) , 
9, 1.42782, 1, 0, 0.5,8.40867e-05)    );
  // itree = 90
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.48596,-0.00161448) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.64324,0.00772105) , 
8, -0.167664, 1, 0, 0.526065,0.000971115) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.465475,-0.0185068) , 
8, 0.49333, 1, 0, 0.520208,-0.00118578) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.454316,0.0166648) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.453698,-0.00550695) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.466379,0.0125837) , 
2, 84.298, 1, 0, 0.456652,-0.00148534) , 
8, 1.27236, 1, 0, 0.456144,0.0030755) , 
8, 0.85685, 1, 0, 0.5,0.000158376)    );
  // itree = 91
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.48748,0.00757001) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.517197,0.000708032) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.469801,-0.00463114) , 
7, 2.73827, 1, 0, 0.50284,-0.00107783) , 
10, -2.57014, 1, 0, 0.501685,-0.000284897) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.478652,0.00476607) , 
8, 2.57041, 1, 0, 0.5,0.000168983)    );
  // itree = 92
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.558065,0.00509064) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.663837,-0.0107482) , 
2, 45.9627, 1, 0, 0.612897,-0.00423385) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.391011,-0.00173018) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.476259,0.0056934) , 
10, -0.233645, 1, 0, 0.428644,0.00183826) , 
4, 409.51, 1, 0, 0.507474,-0.000759627) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.491353,-0.00944303) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.510906,0.00320941) , 
9, 1.99921, 1, 0, 0.501779,-0.00329514) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.480072,0.00162053) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.422596,0.0142809) , 
1, 47.3891, 1, 0, 0.450657,0.00943192) , 
8, 1.42743, 1, 0, 0.47741,0.00277177) , 
10, 1.42799, 1, 0, 0.5,0.000118328)    );
  // itree = 93
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.616271,0.00971872) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.567303,-0.00719262) , 
7, 1.07613, 1, 0, 0.5967,0.00361719) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.455205,-0.0178849) , 
6, 151.476, 1, 0, 0.558983,-0.00288254) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.362669,-0.00968875) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.535973,0.00195763) , 
2, 38.0276, 1, 0, 0.485657,-0.0011217) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.489155,0.010893) , 
2, 118.302, 1, 0, 0.486073,0.000639129) , 
7, 1.32985, 1, 0, 0.5,-3.35588e-05)    );
  // itree = 94
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.547405,0.0103872) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.509052,-0.00108163) , 
7, 2.28566, 1, 0, 0.519699,0.00259053) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.503255,-0.00364229) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.484768,0.00959714) , 
10, 1.99885, 1, 0, 0.500244,-0.00165184) , 
6, 74.6872, 1, 0, 0.509772,0.000425791) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.344764,-0.0050482) , 
1, 151.518, 1, 0, 0.5,0.000122454)    );
  // itree = 95
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.539383,0.0211635) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.510056,0.00211837) , 
7, 2.62963, 1, 0, 0.516682,0.00811689) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.505758,-0.00637427) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.529084,0.00835773) , 
2, 96.4465, 1, 0, 0.50861,-0.00528537) , 
6, 47.5973, 1, 0, 0.511287,-0.000840237) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.446689,0.01355) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.495977,-0.0077227) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.44411,0.0104718) , 
10, 1.4277, 1, 0, 0.481913,-0.00312741) , 
8, -0.8569, 1, 0, 0.471632,0.00251345) , 
6, 104.517, 1, 0, 0.5,0.000114352)    );
  // itree = 96
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.53228,-0.000188738) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.521166,0.0112397) , 
0, 67.7931, 1, 0, 0.530141,0.00263162) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.545318,0.00301201) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.477889,-0.00733556) , 
7, 2.17054, 1, 0, 0.50929,-0.00302086) , 
5, 76.2829, 1, 0, 0.518578,-0.000502956) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.416783,-0.0052689) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.372015,0.0107774) , 
0, 92.3255, 1, 0, 0.392927,0.00337844) , 
5, 167.582, 1, 0, 0.5,7.09332e-05)    );
  // itree = 97
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.455791,0.00651452) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.442618,-0.00709782) , 
9, -2.68829, 1, 0, 0.447745,-0.00198104) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.497859,0.0112968) , 
9, -1.8953, 1, 0, 0.461036,0.00213055) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.601209,0.00572493) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.426849,-0.0102918) , 
0, 81.0386, 1, 0, 0.562728,0.00285151) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.505209,0.00143913) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.454419,-0.00863561) , 
6, 74.8524, 1, 0, 0.486682,-0.00260078) , 
7, 1.79932, 1, 0, 0.513583,-0.000672043) , 
9, -1.42793, 1, 0, 0.5,5.23968e-05)    );
  // itree = 98
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.586055,0.00762557) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.509461,-0.00290526) , 
0, 34.6344, 1, 0, 0.520831,-0.00160916) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.447506,0.00897422) , 
0, 80.9747, 1, 0, 0.514769,-0.000594046) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.553781,0.0066051) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.345783,-0.00189669) , 
3, 330.028, 1, 0, 0.441554,0.00297446) , 
0, 92.3025, 1, 0, 0.5,0.000125814)    );
  // itree = 99
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.590724,0.0100831) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.556379,-0.00316089) , 
6, 31.2511, 1, 0, 0.577191,0.00663332) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.624834,0.00472259) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.541201,-0.00466484) , 
3, 186.624, 1, 0, 0.558591,-0.00336492) , 
6, 42.9127, 1, 0, 0.563083,-0.000949972) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.450321,0.0129096) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.453659,0.000207869) , 
1, 58.5825, 1, 0, 0.452222,0.00640333) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.36278,0.0110877) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.344168,-0.00909508) , 
8, -0.856761, 1, 0, 0.350037,-0.00260412) , 
7, 2.17371, 1, 0, 0.400017,0.00180152) , 
3, 346.936, 1, 0, 0.5,0.000114464)    );
   return;
};
 
// Clean up
inline void ReadBDT::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDT::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
