// Class: ReadBDT
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.10/04       [395780]
Creator        : marine5575
Date           : Wed Oct  9 19:52:22 2019
Host           : Linux htop.hanyang.ac.kr 2.6.32-696.el6.centos.plus.x86_64 #1 SMP Mon Apr 3 14:56:08 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/marine5575/work/Undergrad2018/mva
Training events: 50004
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "100" [Number of trees in the forest]
MaxDepth: "3" [Max depth of the decision tree allowed]
MinNodeSize: "5%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
nCuts: "30" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "Grad" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
Shrinkage: "5.000000e-01" [Learning rate for GradBoost algorithm]
SeparationType: "giniindex" [Separation criterion for node splitting]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
UseBaggedBoost: "False" [Use only a random subsample of all events for growing the trees in each boost iteration.]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "3" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Poisson distribution in each split with RandomisedTree option]
BaggedSampleFraction: "6.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "pray" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in training sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
RegressionLossFunctionBDTG: "huber" [Loss function for BDTG regression.]
HuberQuantile: "7.000000e-01" [In the Huber loss function this is the quantile that separates the core from the tails in the residuals distribution.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
SkipNormalization: "False" [Skip normalization at initialization, to keep expectation value of BDT output according to the fraction of events]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "6.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 11
lepton1_pt                    lepton1_pt                    lepton1_pt                    lepton1_pt                                                      'F'    [30.0003757477,715.323425293]
met_pt                        met_pt                        met_pt                        met_pt                                                          'F'    [0.19669675827,832.46496582]
tau1_pt                       tau1_pt                       tau1_pt                       tau1_pt                                                         'F'    [30.0003395081,1108.22265625]
jet_ht                        jet_ht                        jet_ht                        jet_ht                                                          'F'    [95.0174484253,2866.1184082]
jetlepmet_ht                  jetlepmet_ht                  jetlepmet_ht                  jetlepmet_ht                                                    'F'    [144.123748779,3074.10449219]
lep1met_pt                    lep1met_pt                    lep1met_pt                    lep1met_pt                                                      'F'    [0.211814135313,920.750061035]
lep1tau1_pt                   lep1tau1_pt                   lep1tau1_pt                   lep1tau1_pt                                                     'F'    [0.167901813984,1148.01318359]
tau1_lep1_dr                  tau1_lep1_dr                  tau1_lep1_dr                  tau1_lep1_dr                                                    'F'    [0.390903234482,5.5550994873]
lep1_met_dphi                 lep1_met_dphi                 lep1_met_dphi                 lep1_met_dphi                                                   'F'    [-3.14144611359,3.1415913105]
tau1_met_dphi                 tau1_met_dphi                 tau1_met_dphi                 tau1_met_dphi                                                   'F'    [-3.14137792587,3.14126992226]
tau1lep1_met_dphi             tau1lep1_met_dphi             tau1lep1_met_dphi             tau1lep1_met_dphi                                               'F'    [-3.14146351814,3.14153146744]
NSpec 2
njet                          njet                          njet                          njet                                                            'F'    [3,12]
nbjet                         nbjet                         nbjet                         nbjet                                                           'F'    [0,6]


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDTNode
   
#ifndef BDTNode__def
#define BDTNode__def
   
class BDTNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDTNode ( BDTNode* left,BDTNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDTNode();

   // test event if it descends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDTNode* GetRight( void )  {return fRight; };

   // test event if it descends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDTNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDTNode*   fLeft;     // pointer to the left daughter node
   BDTNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value applied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDTNode::~BDTNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDTNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDTNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT : public IClassifierReader {

 public:

   // constructor
   ReadBDT( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDT" ),
        fNvars( 11 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "lepton1_pt", "met_pt", "tau1_pt", "jet_ht", "jetlepmet_ht", "lep1met_pt", "lep1tau1_pt", "tau1_lep1_dr", "lep1_met_dphi", "tau1_met_dphi", "tau1lep1_met_dphi" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;
      fVmin[8] = 0;
      fVmax[8] = 0;
      fVmin[9] = 0;
      fVmax[9] = 0;
      fVmin[10] = 0;
      fVmax[10] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[11];
   double fVmax[11];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[11];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDTNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDTNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDTNode*)current->GetRight();
         else current=(BDTNode*)current->GetLeft();
      }
      myMVA += current->GetResponse();
   }
   return 2.0/(1.0+exp(-2.0*myMVA))-1.0;
};

void ReadBDT::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.564448,0.0424338) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.430251,-0.0531729) , 
4, 317.907, 1, 0, 0.491353,-0.00864697) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.712706,0.121716) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.602326,0.0648765) , 
4, 333.925, 1, 0, 0.654454,0.154454) , 
2, 41.3291, 1, 0, 0.593356,0.0933559) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.48775,-0.00874722) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.551211,0.0341776) , 
1, 78.0899, 1, 0, 0.517636,0.0176364) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.315098,-0.163046) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.440858,-0.044531) , 
2, 61.3331, 1, 0, 0.379229,-0.120771) , 
7, 1.33982, 1, 0, 0.410092,-0.0899085) , 
4, 427.67, 1, 0, 0.5,3.47623e-15)    );
  // itree = 1
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.514512,0.00740311) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.34846,-0.0889597) , 
4, 363.642, 1, 0, 0.437124,-0.0428642) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.694846,0.0837624) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.550043,0.0335474) , 
4, 325.472, 1, 0, 0.595159,0.0786653) , 
2, 37.1642, 1, 0, 0.556495,0.0489328) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.520345,0.00900956) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.37338,-0.0656807) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.28521,-0.159532) , 
4, 769.151, 1, 0, 0.348176,-0.105854) , 
7, 1.18167, 1, 0, 0.382135,-0.0823993) , 
4, 522.186, 1, 0, 0.5,0.00637939)    );
  // itree = 2
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.532861,0.0252262) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.420011,-0.0618775) , 
8, 0.709711, 1, 0, 0.491353,-0.00600583) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.673473,0.059914) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.571098,0.00633473) , 
1, 72.6746, 1, 0, 0.654454,0.0819402) , 
2, 41.3291, 1, 0, 0.593356,0.0489955) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.293844,-0.137474) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.362174,-0.0546045) , 
8, -0.102718, 1, 0, 0.335107,-0.0972999) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.492053,0.0307151) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.35744,-0.0661807) , 
9, 0.984048, 1, 0, 0.435947,-0.00755385) , 
9, -1.31714, 1, 0, 0.410092,-0.0305652) , 
4, 427.67, 1, 0, 0.5,0.00846682)    );
  // itree = 3
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.506632,-0.00722246) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.29739,-0.101073) , 
3, 447.198, 1, 0, 0.467918,-0.027944) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.698168,0.116967) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.451332,0.00181924) , 
0, 66.2266, 1, 0, 0.598884,0.11794) , 
8, -0.532787, 1, 0, 0.522846,0.03324) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.633582,0.0394258) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.511837,-0.0177332) , 
1, 53.3766, 1, 0, 0.580683,0.0239878) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.413148,-0.0365843) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.33014,-0.116288) , 
9, 0.506139, 1, 0, 0.387125,-0.0724304) , 
3, 239.156, 1, 0, 0.455983,-0.0381297) , 
8, 0.709448, 1, 0, 0.5,0.0088543)    );
  // itree = 4
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.36039,-0.0868265) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.439895,-0.0122254) , 
10, -1.11489, 1, 0, 0.416593,-0.0410404) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.610781,0.0455287) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.536221,0.00687267) , 
8, 0.912046, 1, 0, 0.586656,0.0501509) , 
2, 39.0652, 1, 0, 0.536115,0.0230497) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.29519,-0.0788515) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.438665,0.00481333) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.372065,-0.0317586) , 
0, 74.2239, 1, 0, 0.404749,-0.0158738) , 
2, 64.7817, 1, 0, 0.357006,-0.0438922) , 
4, 616.701, 1, 0, 0.5,0.00955174)    );
  // itree = 5
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.514196,0.00469448) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.368189,-0.0610046) , 
1, 82.416, 1, 0, 0.476162,-0.0136166) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.771384,0.113205) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.547195,0.0434705) , 
0, 48.1178, 1, 0, 0.635045,0.114101) , 
8, -0.317256, 1, 0, 0.525813,0.0262949) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.545861,0.0123157) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.332293,-0.0528973) , 
3, 383.295, 1, 0, 0.493297,-0.00095888) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.346352,-0.0735851) , 
1, 83.1899, 1, 0, 0.457775,-0.0208408) , 
8, 0.506769, 1, 0, 0.5,0.00841191)    );
  // itree = 6
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.413305,-0.0529585) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.498311,0.00303686) , 
8, -0.709366, 1, 0, 0.475607,-0.0142425) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.659866,0.0728225) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.519785,0.0275622) , 
7, 1.50041, 1, 0, 0.56374,0.0622536) , 
9, -0.552586, 1, 0, 0.51587,0.0207044) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.329188,-0.0785653) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.51927,-0.00380228) , 
2, 39.2011, 1, 0, 0.406436,-0.052757) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.478364,-0.0199379) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.521664,0.0114191) , 
7, 2.13058, 1, 0, 0.505803,0.000331222) , 
2, 53.7656, 1, 0, 0.458184,-0.0251097) , 
9, 1.31728, 1, 0, 0.5,0.00810045)    );
  // itree = 7
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.702629,0.0556895) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.642354,0.027362) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.586994,-0.00518852) , 
9, 0.910682, 1, 0, 0.623401,0.024707) , 
1, 26.9961, 1, 0, 0.645333,0.0422832) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.32221,-0.073067) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.439944,-0.0164691) , 
2, 61.3343, 1, 0, 0.38298,-0.0479677) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.506152,0.0182757) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.416896,-0.0193241) , 
9, 0.853122, 1, 0, 0.468938,0.0047305) , 
9, -1.92538, 1, 0, 0.453505,-0.00473093) , 
4, 333.155, 1, 0, 0.5,0.00666424)    );
  // itree = 8
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.478785,-0.00726099) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.605344,0.0435211) , 
8, -0.65718, 1, 0, 0.536778,0.0237597) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.406421,-0.0362337) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.514827,0.00515333) , 
2, 51.4049, 1, 0, 0.464119,-0.0164932) , 
8, 0.912126, 1, 0, 0.513664,0.0109545) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.354246,-0.0477932) , 
1, 134.434, 1, 0, 0.5,0.00552262)    );
  // itree = 9
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.502676,0.00433605) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.290477,-0.0659947) , 
4, 436.757, 1, 0, 0.419479,-0.0215959) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.562835,0.0133244) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.541792,0.0618851) , 
0, 121.101, 1, 0, 0.560876,0.0251215) , 
2, 43.0178, 1, 0, 0.510172,0.00836891) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.313148,-0.0614937) , 
4, 900.248, 1, 0, 0.5,0.00473213)    );
  // itree = 10
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.430216,-0.0295426) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.50402,0.00771293) , 
9, -0.304183, 1, 0, 0.478244,-0.00584371) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.728577,0.0806282) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.567747,0.0277805) , 
7, 2.33603, 1, 0, 0.6652,0.0920686) , 
8, -0.251718, 1, 0, 0.523157,0.0176778) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.603888,0.0362466) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.494112,-0.0091838) , 
8, 1.21949, 1, 0, 0.531064,0.00944084) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.442959,-0.0144544) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.359562,-0.0598879) , 
9, 0.506648, 1, 0, 0.416669,-0.0331194) , 
1, 49.9926, 1, 0, 0.468181,-0.0139548) , 
8, 0.304091, 1, 0, 0.5,0.00435367)    );
  // itree = 11
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.464474,-0.0229802) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.58498,0.0319857) , 
8, -1.11466, 1, 0, 0.55115,0.023523) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.526476,0.0328119) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.461197,-0.00933433) , 
8, -2.12811, 1, 0, 0.470333,-0.00377126) , 
0, 52.1076, 1, 0, 0.505413,0.00807629) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.42199,-0.0427454) , 
7, 3.38947, 1, 0, 0.5,0.00424143)    );
  // itree = 12
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.65033,0.0236839) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.689557,0.0352733) , 
5, 59.5731, 1, 0, 0.670198,0.044129) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.617293,0.00182523) , 
4, 290.466, 1, 0, 0.645333,0.0246172) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.426114,-0.0110089) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.370611,-0.0463327) , 
8, 1.31513, 1, 0, 0.412369,-0.023005) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.548582,0.0279507) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.425279,-0.0123175) , 
9, 0.657089, 1, 0, 0.476433,0.00748372) , 
9, -0.709385, 1, 0, 0.453505,-0.00342788) , 
4, 333.155, 1, 0, 0.5,0.00336963)    );
  // itree = 13
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.592991,0.0291441) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.50887,-0.00451342) , 
0, 38.5557, 1, 0, 0.526688,0.00390952) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.477624,0.0321478) , 
0, 118.429, 1, 0, 0.521882,0.00758312) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.322087,-0.0466195) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.421172,-0.00450158) , 
8, -0.303885, 1, 0, 0.383495,-0.021435) , 
1, 107.586, 1, 0, 0.5,0.0029948)    );
  // itree = 14
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.446545,-0.0125928) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.532192,0.0133135) , 
10, -0.303431, 1, 0, 0.473085,-0.00510727) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.745759,0.0590216) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.508432,0.00727694) , 
0, 65.1176, 1, 0, 0.65205,0.0566304) , 
8, -0.362862, 1, 0, 0.523157,0.0121661) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.455416,-0.0259629) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.506104,0.00199909) , 
9, -1.92538, 1, 0, 0.495602,-0.00454358) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.334228,-0.0417517) , 
1, 99.7885, 1, 0, 0.468181,-0.0111879) , 
8, 0.304091, 1, 0, 0.5,0.00232905)    );
  // itree = 15
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.530138,0.00864774) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.402315,-0.022759) , 
1, 59.9388, 1, 0, 0.472831,-0.00529202) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.679499,0.0376725) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.526607,0.0128968) , 
7, 1.48077, 1, 0, 0.576214,0.0297361) , 
9, -0.657138, 1, 0, 0.517806,0.00994653) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.568312,0.0224995) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.37087,-0.0444553) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.469913,-0.00854123) , 
10, 0.101856, 1, 0, 0.443154,-0.0210899) , 
1, 27.4351, 1, 0, 0.464562,-0.0122807) , 
9, 0.911943, 1, 0, 0.5,0.00251311)    );
  // itree = 16
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.456212,-0.00363682) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.233319,-0.0782554) , 
3, 426.748, 1, 0, 0.417637,-0.014588) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.569031,0.00950193) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.544371,0.0469932) , 
0, 105.505, 1, 0, 0.566131,0.0191643) , 
2, 43.1065, 1, 0, 0.509481,0.00628794) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.45707,-0.0565889) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.393203,0.0111745) , 
7, 1.39484, 1, 0, 0.425281,-0.0285178) , 
6, 148.277, 1, 0, 0.5,0.00236869)    );
  // itree = 17
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.46353,-0.0154051) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.485303,0.0223611) , 
0, 87.0345, 1, 0, 0.468267,-0.00897169) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.648986,0.0375579) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.404889,-0.0324225) , 
0, 84.3354, 1, 0, 0.584784,0.0283182) , 
8, -0.905629, 1, 0, 0.525813,0.00944521) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.558008,0.00950985) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.434617,-0.0192088) , 
1, 30.3059, 1, 0, 0.460549,-0.0155782) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.44477,0.0154066) , 
0, 96.3255, 1, 0, 0.457775,-0.00953935) , 
8, 0.506769, 1, 0, 0.5,0.0022426)    );
  // itree = 18
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.482201,0.000502207) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.585688,0.0179915) , 
9, -0.526357, 1, 0, 0.523836,0.0103967) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.52977,0.00491615) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.409746,-0.0177736) , 
1, 54.2694, 1, 0, 0.468396,-0.00725775) , 
9, 0.911974, 1, 0, 0.505413,0.00453009) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.42199,-0.0256891) , 
7, 3.38947, 1, 0, 0.5,0.00228664)    );
  // itree = 19
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.502387,0.00365553) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.450739,-0.0231966) , 
7, 2.6405, 1, 0, 0.484714,-0.00691255) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.675748,0.0220449) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.626527,0.000377077) , 
9, 1.1146, 1, 0, 0.660204,0.0222075) , 
2, 40.5332, 1, 0, 0.595522,0.0114744) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.29379,-0.038229) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.486607,0.00118702) , 
2, 40.0968, 1, 0, 0.425407,-0.0100633) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.461391,0.0189377) , 
2, 134.344, 1, 0, 0.430593,-0.00520271) , 
3, 273.798, 1, 0, 0.5,0.00181553)    );
  // itree = 20
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.634998,0.0386744) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.449634,-0.0151234) , 
10, 0.709141, 1, 0, 0.579525,0.0315929) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.486604,-0.00554322) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.522986,0.0334375) , 
2, 121.743, 1, 0, 0.489581,-0.00258385) , 
7, 1.56383, 1, 0, 0.509481,0.00497788) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.45314,-0.0379661) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.391176,0.00699319) , 
7, 1.53826, 1, 0, 0.425281,-0.0219244) , 
6, 148.277, 1, 0, 0.5,0.00194859)    );
  // itree = 21
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.535268,0.0259773) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.509167,0.00644823) , 
6, 22.8594, 1, 0, 0.520833,0.0198593) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.585923,0.0209804) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.489383,-0.00599763) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.464102,0.0292645) , 
2, 155.332, 1, 0, 0.487719,-0.00451915) , 
7, 0.861666, 1, 0, 0.496019,-0.00180694) , 
6, 37.1952, 1, 0, 0.5,0.00166877)    );
  // itree = 22
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.595642,0.0286654) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.503687,-0.0021902) , 
0, 33.358, 1, 0, 0.511834,0.000849916) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.484797,0.0296532) , 
0, 134.116, 1, 0, 0.510172,0.00314289) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.313148,-0.037105) , 
4, 900.248, 1, 0, 0.5,0.00115878)    );
  // itree = 23
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.480922,-0.0212971) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.559027,0.0213055) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.49146,-0.00175454) , 
7, 2.06274, 1, 0, 0.514166,0.00771805) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.469443,-0.0156416) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.443341,0.0166024) , 
10, 1.51942, 1, 0, 0.463922,-0.0108135) , 
6, 111.25, 1, 0, 0.501379,0.00300199) , 
5, 29.9066, 1, 0, 0.5,0.000966746)    );
  // itree = 24
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.569182,0.0320332) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.474346,0.00154975) , 
10, 0.709537, 1, 0, 0.535995,0.0279386) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.66448,0.0174232) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.437115,-0.00972379) , 
4, 318.476, 1, 0, 0.49674,-0.00201496) , 
7, 2.40619, 1, 0, 0.509712,0.00788319) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.576832,0.0115539) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.47052,-0.0139913) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.475905,0.0137315) , 
2, 124.001, 1, 0, 0.471535,-0.0104466) , 
7, 1.01859, 1, 0, 0.491119,-0.00569635) , 
6, 74.2224, 1, 0, 0.5,0.000790126)    );
  // itree = 25
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.547583,-0.00758909) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.360069,-0.0386263) , 
3, 258.771, 1, 0, 0.439655,-0.0286473) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.542063,0.0232764) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.440036,-0.0155212) , 
8, -2.13459, 1, 0, 0.487301,0.00466324) , 
7, 2.12774, 1, 0, 0.468224,-0.00867437) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.633037,0.0250713) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.382171,-0.0240402) , 
0, 100.226, 1, 0, 0.587358,0.0221939) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.612409,0.0141549) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.43661,-0.00981367) , 
3, 184.408, 1, 0, 0.462545,-0.00690861) , 
8, 0.395781, 1, 0, 0.514484,0.00520205) , 
8, -0.911981, 1, 0, 0.5,0.000857366)    );
  // itree = 26
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.476642,-0.0117694) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.609993,0.0223587) , 
10, -0.506823, 1, 0, 0.564616,0.0141946) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.515056,0.00760275) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.47093,-0.0116292) , 
6, 45.6877, 1, 0, 0.485483,-0.00632279) , 
7, 1.55701, 1, 0, 0.50641,-0.000897048) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.552739,0.0424989) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.336376,-0.0198721) , 
4, 614.607, 1, 0, 0.446046,0.0197348) , 
0, 118.429, 1, 0, 0.5,0.0012937)    );
  // itree = 27
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.564285,0.00725946) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.459127,-0.0130043) , 
8, 1.31748, 1, 0, 0.532102,0.00165464) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.528757,0.0360107) , 
0, 97.052, 1, 0, 0.531834,0.00536004) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.399752,-0.0131625) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.546572,0.0259739) , 
8, -0.101409, 1, 0, 0.456023,0.00395218) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.392046,-0.0371634) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.419768,-0.00198026) , 
9, 1.72291, 1, 0, 0.403584,-0.0246377) , 
10, 0.304513, 1, 0, 0.435485,-0.0072454) , 
5, 118.991, 1, 0, 0.5,0.00119522)    );
  // itree = 28
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.593273,0.0189102) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.50197,-0.000398953) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.43344,-0.0204786) , 
7, 3.22288, 1, 0, 0.495075,-0.00285402) , 
0, 33.5659, 1, 0, 0.50405,-0.000363499) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.440264,0.0198855) , 
0, 140.536, 1, 0, 0.5,0.00115939)    );
  // itree = 29
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.624887,0.025647) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.503797,0.00165895) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.418606,-0.0228072) , 
6, 137.508, 1, 0, 0.497191,-0.000165944) , 
7, 0.898624, 1, 0, 0.505722,0.00207726) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.402615,-0.0180768) , 
6, 185.304, 1, 0, 0.5,0.000827199)    );
  // itree = 30
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.577303,-0.000577059) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.373971,-0.0208916) , 
4, 367.164, 1, 0, 0.463426,-0.0133209) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.485472,0.0130893) , 
0, 87.0345, 1, 0, 0.468224,-0.00685573) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.71624,0.0339856) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.500165,0.0021851) , 
0, 47.5633, 1, 0, 0.578748,0.0178587) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.502529,0.00406802) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.451661,-0.0125474) , 
9, 0.101321, 1, 0, 0.48282,-0.00259228) , 
8, 0.134275, 1, 0, 0.514484,0.00415821) , 
8, -0.911981, 1, 0, 0.5,0.000709762)    );
  // itree = 31
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.474541,0.00140156) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.421465,-0.01985) , 
10, -1.52005, 1, 0, 0.448093,-0.010201) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.526101,0.00229388) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.4448,-0.0173642) , 
6, 148.435, 1, 0, 0.516718,0.000166419) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.485439,0.000631947) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.506867,0.0353092) , 
0, 70.7467, 1, 0, 0.492771,0.0160926) , 
10, 1.72281, 1, 0, 0.511851,0.00340333) , 
9, -1.92538, 1, 0, 0.5,0.000874615)    );
  // itree = 32
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.448706,-0.0158382) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.540728,0.00890106) , 
8, -1.3178, 1, 0, 0.519367,0.0039928) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.533955,0.0142882) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.46739,-0.0112098) , 
6, 22.0223, 1, 0, 0.479596,-0.00774567) , 
7, 2.55653, 1, 0, 0.50405,-0.000527947) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.440264,0.0155764) , 
0, 140.536, 1, 0, 0.5,0.000676321)    );
  // itree = 33
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.478697,-0.0154982) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.542935,0.00583342) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.367646,-0.016305) , 
1, 103.408, 1, 0, 0.529819,0.00563571) , 
5, 33.737, 1, 0, 0.524328,0.00291507) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.341911,-0.0482638) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.448746,-0.00125745) , 
9, -0.505951, 1, 0, 0.408953,-0.0189672) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.39444,0.0109554) , 
7, 2.76892, 1, 0, 0.404134,-0.00865328) , 
5, 148.686, 1, 0, 0.5,0.000573548)    );
  // itree = 34
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.381675,-0.00967269) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.3952,-0.0319872) , 
2, 36.5121, 1, 0, 0.386106,-0.0182286) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.589117,0.023652) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.554931,0.00148814) , 
2, 49.2174, 1, 0, 0.562228,0.00814003) , 
2, 40.0969, 1, 0, 0.502516,-0.000799982) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.474127,0.0121362) , 
2, 134.344, 1, 0, 0.5,0.000619061)    );
  // itree = 35
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.398573,-0.00802756) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.573296,0.00394292) , 
2, 40.0782, 1, 0, 0.514048,0.000482) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.514226,0.0157107) , 
2, 134.14, 1, 0, 0.51406,0.00187208) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.329721,-0.0137593) , 
3, 631.36, 1, 0, 0.5,0.000735039)    );
  // itree = 36
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.602394,0.00448926) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.447317,0.0339824) , 
3, 284.076, 1, 0, 0.535995,0.0197223) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.492359,-0.00814714) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.511609,0.0182295) , 
0, 80.3501, 1, 0, 0.49674,-0.00237268) , 
7, 2.40619, 1, 0, 0.509712,0.00492861) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.515897,0.00163453) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.453988,-0.015506) , 
8, 0.303768, 1, 0, 0.492285,-0.00580804) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.482589,0.0127641) , 
10, 2.33048, 1, 0, 0.491119,-0.00316768) , 
6, 74.2224, 1, 0, 0.5,0.000699637)    );
  // itree = 37
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.536465,0.0165944) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.50734,0.00102556) , 
7, 2.99442, 1, 0, 0.520833,0.0105833) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.456022,-0.00661043) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.540779,0.00566658) , 
9, -0.931753, 1, 0, 0.507784,0.00137261) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.33608,-0.0382221) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.499145,-0.00147504) , 
2, 53.7656, 1, 0, 0.434328,-0.0161073) , 
9, 2.12794, 1, 0, 0.496019,-0.001427) , 
6, 37.1952, 1, 0, 0.5,0.000499702)    );
  // itree = 38
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.478201,0.0110575) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.533602,0.00852711) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.498428,-0.003065) , 
6, 86.8284, 1, 0, 0.515619,0.00326146) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.475535,-0.0154004) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.468366,0.00502845) , 
8, 0.70949, 1, 0, 0.472909,-0.00948205) , 
7, 2.72312, 1, 0, 0.502129,-0.000763726) , 
10, -2.53343, 1, 0, 0.5,0.000527871)    );
  // itree = 39
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.520809,0.00304652) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.39262,-0.0158447) , 
5, 109.298, 1, 0, 0.477493,-0.0032024) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.671947,0.024943) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.509839,0.000327687) , 
8, 0.143577, 1, 0, 0.56256,0.010642) , 
8, -0.264742, 1, 0, 0.51373,0.00269509) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.459581,-0.0437736) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.427393,-0.00582907) , 
10, 1.11459, 1, 0, 0.443648,-0.0307301) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.427625,-0.0083943) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.497371,0.0225601) , 
8, 2.14109, 1, 0, 0.466263,0.0115582) , 
0, 52.1117, 1, 0, 0.456384,-0.00691375) , 
8, 1.31748, 1, 0, 0.5,0.000394471)    );
  // itree = 40
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.524292,0.0135028) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.515066,-0.00337674) , 
10, 0.709242, 1, 0, 0.520833,0.00921573) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.622085,0.00804577) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.48616,-0.00103204) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.388465,-0.0190767) , 
7, 3.21548, 1, 0, 0.479026,-0.00268142) , 
3, 184.408, 1, 0, 0.496019,-0.00104432) , 
6, 37.1952, 1, 0, 0.5,0.0006016)    );
  // itree = 41
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.593273,0.0117595) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.511065,0.00081525) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.467553,-0.00612427) , 
9, 0.709277, 1, 0, 0.495075,-0.00203828) , 
0, 33.5659, 1, 0, 0.50405,-0.000502822) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.440264,0.0129428) , 
0, 140.536, 1, 0, 0.5,0.000492537)    );
  // itree = 42
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.474541,0.00260458) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.421465,-0.0138826) , 
10, -1.52005, 1, 0, 0.448093,-0.00608971) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.535854,0.00451705) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.46451,-0.00912386) , 
6, 132.532, 1, 0, 0.525366,0.00326077) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.364885,-0.0137323) , 
1, 134.434, 1, 0, 0.511851,0.00183104) , 
9, -1.92538, 1, 0, 0.5,0.000358764)    );
  // itree = 43
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.605993,-0.00246562) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.609629,0.0196583) , 
0, 82.4836, 1, 0, 0.606499,0.0010374) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.509182,-0.0250392) , 
4, 400.228, 1, 0, 0.593356,-0.00341441) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.48691,0.0208921) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.437247,-0.00232618) , 
1, 67.4606, 1, 0, 0.465566,0.0138566) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.38108,-0.0106357) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.382881,0.00948785) , 
1, 81.8316, 1, 0, 0.381968,-0.000964827) , 
4, 513.051, 1, 0, 0.410092,0.00402131) , 
4, 427.67, 1, 0, 0.5,0.000373384)    );
  // itree = 44
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.427098,-0.00417747) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.213512,-0.0457471) , 
3, 426.748, 1, 0, 0.386106,-0.00982236) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.57961,0.00772957) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.531331,-0.00557329) , 
9, 0.709277, 1, 0, 0.562228,0.00392659) , 
2, 40.0969, 1, 0, 0.502516,-0.000734847) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.474127,0.00855368) , 
2, 134.344, 1, 0, 0.5,0.000274958)    );
  // itree = 45
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.433825,0.000894327) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.464013,-0.028229) , 
9, -1.49431, 1, 0, 0.446226,-0.0134375) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.555101,0.0122801) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.460032,-0.00848794) , 
8, 1.25861, 1, 0, 0.509314,0.00282157) , 
8, -0.10136, 1, 0, 0.485051,-0.00343136) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.64295,0.0245733) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.499077,0.00101216) , 
7, 1.8264, 1, 0, 0.533297,0.00853052) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.496824,-0.013749) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.457233,0.00960664) , 
10, 1.52116, 1, 0, 0.478917,-0.00391464) , 
8, 0.101412, 1, 0, 0.51174,0.00359709) , 
9, -0.304053, 1, 0, 0.5,0.000505307)    );
  // itree = 46
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.526689,0.006702) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.429222,0.00276574) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.405426,-0.0201674) , 
9, -2.70998, 1, 0, 0.414648,-0.0121731) , 
1, 39.0905, 1, 0, 0.448093,-0.00604424) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.565522,0.00785213) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.486615,-0.00437724) , 
7, 1.89019, 1, 0, 0.517426,0.000516427) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.465814,0.0118419) , 
0, 118.429, 1, 0, 0.511851,0.00200183) , 
9, -1.92538, 1, 0, 0.5,0.00050626)    );
  // itree = 47
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.563158,0.0134719) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.483528,0.000647913) , 
5, 72.5475, 1, 0, 0.520833,0.00882607) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.515302,0.00152048) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.411735,-0.0162652) , 
6, 180.528, 1, 0, 0.507784,0.000401754) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.40758,-0.0242639) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.451903,0.00234089) , 
8, -0.506975, 1, 0, 0.434328,-0.00943433) , 
9, 2.12794, 1, 0, 0.496019,-0.00117361) , 
6, 37.1952, 1, 0, 0.5,0.000430545)    );
  // itree = 48
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.478201,0.00818468) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.490108,-0.00472511) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.564548,0.00578713) , 
8, -1.1147, 1, 0, 0.539499,0.0028247) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.464448,-0.000627279) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.372373,-0.0170342) , 
8, 0.303679, 1, 0, 0.430639,-0.00704948) , 
5, 118.991, 1, 0, 0.502129,-0.000565024) , 
10, -2.53343, 1, 0, 0.5,0.000385965)    );
  // itree = 49
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.583331,0.0232795) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.508322,0.00167925) , 
7, 2.14768, 1, 0, 0.525723,0.00828454) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.462668,0.0130333) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.511976,-0.00550806) , 
10, -1.92436, 1, 0, 0.503259,-0.00260372) , 
6, 74.2224, 1, 0, 0.51373,0.00247164) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.459581,-0.0297724) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.427393,-0.00485031) , 
10, 1.11459, 1, 0, 0.443648,-0.021429) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.490964,-0.0075421) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.437874,0.0193556) , 
1, 50.4044, 1, 0, 0.466263,0.00561649) , 
0, 52.1117, 1, 0, 0.456384,-0.00619723) , 
8, 1.31748, 1, 0, 0.5,0.000396072)    );
  // itree = 50
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.649306,-0.000416341) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.564797,0.0180119) , 
4, 317.884, 1, 0, 0.626424,0.00625328) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.498575,-0.0240825) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.585522,-0.00354987) , 
8, -1.31626, 1, 0, 0.562106,-0.011981) , 
3, 217.931, 1, 0, 0.593356,-0.00312159) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.362516,-0.00868061) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.471658,0.0170711) , 
10, -0.506823, 1, 0, 0.432118,0.00923678) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.449964,0.0101241) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.334775,-0.0146808) , 
3, 372.413, 1, 0, 0.37997,-0.00404177) , 
0, 74.2165, 1, 0, 0.410092,0.00362814) , 
4, 427.67, 1, 0, 0.5,0.000316762)    );
  // itree = 51
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.583867,0.00853691) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.491619,-0.00181874) , 
7, 1.66387, 1, 0, 0.520256,0.00174761) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.41399,-0.0242496) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.467046,-0.000369251) , 
7, 1.7236, 1, 0, 0.453047,-0.00778895) , 
8, 1.31748, 1, 0, 0.50405,-0.00055188) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.440264,0.0114516) , 
0, 140.536, 1, 0, 0.5,0.000325063)    );
  // itree = 52
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.606096,0.0153897) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.538585,-0.00552692) , 
5, 64.7012, 1, 0, 0.573852,0.00725342) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.56363,-0.000680721) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.41883,-0.0204348) , 
8, 1.11472, 1, 0, 0.524575,-0.00707352) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.506809,0.0171778) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.444003,-0.000453946) , 
8, -1.7226, 1, 0, 0.455554,0.00362784) , 
0, 52.1076, 1, 0, 0.48569,-0.00104452) , 
1, 27.0441, 1, 0, 0.5,0.0003024)    );
  // itree = 53
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.422018,-0.00934897) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.473212,0.0141343) , 
7, 1.91727, 1, 0, 0.454098,0.00674509) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.553609,0.0049605) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.437582,-0.0145783) , 
1, 41.3705, 1, 0, 0.476625,-0.00913822) , 
10, -1.72193, 1, 0, 0.468815,-0.00363132) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.70585,0.024623) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.514716,-0.000708641) , 
7, 1.6545, 1, 0, 0.57454,0.00910106) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.483851,-0.0208004) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.477646,0.00361028) , 
7, 1.39043, 1, 0, 0.478977,-0.00184232) , 
10, 0.30405, 1, 0, 0.519719,0.00282326) , 
8, -0.506624, 1, 0, 0.5,0.000322918)    );
  // itree = 54
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.524674,0.0106154) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.512404,-0.00114905) , 
6, 37.1952, 1, 0, 0.514317,0.000933421) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.459761,-0.0166756) , 
10, 0.741513, 1, 0, 0.50787,-0.00148249) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.422803,-0.00405793) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.516801,0.0185453) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.492924,-0.00719082) , 
7, 2.95979, 1, 0, 0.507828,0.011348) , 
7, 2.05677, 1, 0, 0.478208,0.00576818) , 
10, 1.31744, 1, 0, 0.5,0.000441346)    );
  // itree = 55
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.38362,-0.0139344) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.388799,0.000174477) , 
9, 0.101173, 1, 0, 0.386106,-0.00749089) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.585702,4.36721e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.410147,0.0202568) , 
3, 499.181, 1, 0, 0.562228,0.00294719) , 
2, 40.0969, 1, 0, 0.502516,-0.00059173) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.474127,0.00815624) , 
2, 134.344, 1, 0, 0.5,0.000354384)    );
  // itree = 56
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.424105,-0.0215525) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.542781,0.0113914) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.484929,7.07391e-06) , 
9, 0.710917, 1, 0, 0.516123,0.00814304) , 
7, 2.12774, 1, 0, 0.48115,-0.00463517) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.642712,0.0188546) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.46836,-0.00403806) , 
8, 1.63785, 1, 0, 0.556241,0.00980288) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.390309,-0.0161183) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.500741,0.000917315) , 
8, -0.467459, 1, 0, 0.471809,-0.0037577) , 
5, 89.8565, 1, 0, 0.505271,0.00161673) , 
8, -1.52002, 1, 0, 0.5,0.000250417)    );
  // itree = 57
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.522806,0.00203159) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.445443,-0.00726481) , 
6, 132.38, 1, 0, 0.511579,0.000912034) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.342219,-0.0163093) , 
1, 144.924, 1, 0, 0.500111,-0.000186995) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.498318,0.0083403) , 
10, 2.73618, 1, 0, 0.5,0.000478661)    );
  // itree = 58
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.571775,0.00279699) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.455309,0.0317864) , 
3, 345.491, 1, 0, 0.532609,0.0136847) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.593046,0.00735704) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.474795,-0.0220423) , 
0, 48.1151, 1, 0, 0.525434,-0.0115492) , 
2, 64.783, 1, 0, 0.529925,0.00424598) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.515306,0.00344183) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.465602,-0.00841331) , 
6, 45.6877, 1, 0, 0.484702,-0.00452994) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.471516,0.0151575) , 
0, 118.429, 1, 0, 0.483084,-0.00176315) , 
7, 1.89019, 1, 0, 0.5,0.000406994)    );
  // itree = 59
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.604038,0.0134089) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.500279,-0.000611048) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.438163,-0.0132679) , 
9, 2.53327, 1, 0, 0.494297,-0.00211711) , 
7, 0.898624, 1, 0, 0.502516,-0.000727606) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.474127,0.00891919) , 
2, 134.344, 1, 0, 0.5,0.000310591)    );
  // itree = 60
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.560607,-0.00366311) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.592492,0.00884121) , 
2, 81.4231, 1, 0, 0.566177,-0.00172001) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.470174,0.00598209) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.621356,0.0202068) , 
2, 60.1357, 1, 0, 0.533842,0.0163927) , 
0, 83.6416, 1, 0, 0.559318,0.00212209) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.476898,0.0154191) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.340064,-0.0119053) , 
7, 2.13058, 1, 0, 0.4093,0.0028418) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.332546,-0.0215778) , 
0, 96.3237, 1, 0, 0.390021,-0.00324345) , 
3, 363.189, 1, 0, 0.5,0.000242122)    );
  // itree = 61
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.411318,0.00108841) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.350765,-0.0145786) , 
6, 71.3886, 1, 0, 0.386106,-0.00523593) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.583765,0.00703683) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.545311,-0.00247503) , 
2, 61.3765, 1, 0, 0.562228,0.00215218) , 
2, 40.0969, 1, 0, 0.502516,-0.000352682) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.474127,0.00662677) , 
2, 134.344, 1, 0, 0.5,0.000399971)    );
  // itree = 62
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.472719,-0.00869048) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.528006,0.00201523) , 
9, -2.53338, 1, 0, 0.522866,0.00133697) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.372018,-0.0174734) , 
1, 116.31, 1, 0, 0.510593,-0.000202875) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.372005,0.00742203) , 
5, 208.075, 1, 0, 0.5,0.00038517)    );
  // itree = 63
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.478201,0.0056763) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.513698,0.000203346) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.415416,-0.0190495) , 
7, 3.2276, 1, 0, 0.504539,-0.00174647) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.457553,-0.000403555) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.509254,0.0156891) , 
0, 57.171, 1, 0, 0.484309,0.0100963) , 
8, 2.12809, 1, 0, 0.502129,-0.000335279) , 
10, -2.53343, 1, 0, 0.5,0.000314625)    );
  // itree = 64
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.646126,0.0125398) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.467144,-0.0172409) , 
10, 0.506477, 1, 0, 0.586723,0.00335496) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.447676,-0.0224824) , 
6, 155.405, 1, 0, 0.553379,-0.00373188) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.597717,0.0115458) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.482396,-0.00181009) , 
1, 20.872, 1, 0, 0.494671,-0.000333305) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.411165,0.0135861) , 
6, 132.38, 1, 0, 0.485935,0.00129832) , 
7, 1.39043, 1, 0, 0.5,0.000249292)    );
  // itree = 65
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.518008,0.00162767) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.474291,-0.0112858) , 
8, 1.92553, 1, 0, 0.514317,0.000588787) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.459761,-0.0109747) , 
10, 0.741513, 1, 0, 0.50787,-0.000992578) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.429781,-0.00890278) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.609355,0.0143562) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.410477,-0.000636327) , 
3, 255.636, 1, 0, 0.491635,0.00763039) , 
9, -1.11466, 1, 0, 0.478208,0.00376378) , 
10, 1.31744, 1, 0, 0.5,0.000269437)    );
  // itree = 66
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.473999,-0.0224588) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.498293,-0.00185123) , 
0, 43.4125, 1, 0, 0.490007,-0.0112311) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.442956,0.010849) , 
5, 84.3079, 1, 0, 0.47615,-0.00424195) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.556626,0.00925) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.477126,-0.00396209) , 
7, 2.56165, 1, 0, 0.52119,0.00406873) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.508475,0.00273338) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.426235,-0.0121699) , 
10, 0.303835, 1, 0, 0.469606,-0.00486231) , 
6, 111.25, 1, 0, 0.507888,0.00176567) , 
8, -1.31734, 1, 0, 0.5,0.000272562)    );
  // itree = 67
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.535082,0.0154157) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.520726,0.00139089) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.506812,-0.00310281) , 
6, 29.1016, 1, 0, 0.513791,-0.00103195) , 
6, 19.2766, 1, 0, 0.520833,0.0057536) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.468117,0.00520245) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.516096,-0.00446097) , 
10, -1.99095, 1, 0, 0.505516,-0.0027108) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.514945,0.00669122) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.314188,-0.00922941) , 
3, 414.078, 1, 0, 0.469327,0.00464953) , 
10, 1.31744, 1, 0, 0.496019,-0.000779362) , 
6, 37.1952, 1, 0, 0.5,0.00026866)    );
  // itree = 68
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.668741,0.00502489) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.526285,-0.00504936) , 
4, 290.47, 1, 0, 0.555672,-0.00365981) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.564633,0.0114196) , 
0, 102.895, 1, 0, 0.556495,-0.00195024) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.374481,-0.00638765) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.404938,0.0141041) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.321428,-0.00837952) , 
4, 850.087, 1, 0, 0.385433,0.00962359) , 
1, 55.0233, 1, 0, 0.382135,0.0047226) , 
4, 522.186, 1, 0, 0.5,0.000211853)    );
  // itree = 69
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.604038,0.00967386) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.508058,0.00193963) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.476424,-0.00561741) , 
6, 76.0139, 1, 0, 0.494297,-0.00153028) , 
7, 0.898624, 1, 0, 0.502516,-0.000539061) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.474127,0.00586942) , 
2, 134.344, 1, 0, 0.5,0.000147744)    );
  // itree = 70
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.54823,-0.000839572) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.581251,0.0197289) , 
2, 112.948, 1, 0, 0.551056,0.00136896) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.376155,-0.0228015) , 
1, 116.31, 1, 0, 0.53525,-0.000882395) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.31558,0.00679001) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.407453,-0.0145417) , 
2, 72.8095, 1, 0, 0.361635,-0.0053283) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.374229,0.0156821) , 
1, 81.779, 1, 0, 0.367332,0.00394307) , 
3, 452.579, 1, 0, 0.5,0.000130587)    );
  // itree = 71
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.480336,-0.00225517) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.675208,0.0125711) , 
8, -0.220237, 1, 0, 0.519056,0.000862382) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.543952,-0.0109551) , 
8, 0.212544, 1, 0, 0.522846,-0.00123794) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.427797,-0.00659298) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.396901,-0.00164869) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.525081,0.0105442) , 
2, 51.4049, 1, 0, 0.466459,0.00670087) , 
7, 1.7236, 1, 0, 0.455983,0.00281052) , 
8, 0.709448, 1, 0, 0.5,0.000145345)    );
  // itree = 72
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.456929,-0.00568384) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.523315,0.00162679) , 
9, -1.92544, 1, 0, 0.511579,0.00050041) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.342219,-0.0116782) , 
1, 144.924, 1, 0, 0.500111,-0.000264961) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.498318,0.0058658) , 
10, 2.73618, 1, 0, 0.5,0.000207636)    );
  // itree = 73
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.427635,-0.000698548) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.457778,0.024545) , 
2, 34.8529, 1, 0, 0.437124,0.00865912) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.610225,0.000147411) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.561247,-0.0108582) , 
5, 101.965, 1, 0, 0.595159,-0.00412323) , 
2, 37.1642, 1, 0, 0.556495,-0.000995995) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.332291,0.00566834) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.396981,-0.0143748) , 
10, -1.17977, 1, 0, 0.363805,-0.00452079) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.415434,0.0149444) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.360712,-0.00525418) , 
0, 96.3237, 1, 0, 0.398065,0.00897196) , 
10, -0.101174, 1, 0, 0.382135,0.00269812) , 
4, 522.186, 1, 0, 0.5,0.00020095)    );
  // itree = 74
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.561301,-0.00198281) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.458983,0.0127426) , 
3, 328.579, 1, 0, 0.550751,-0.000780499) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.629181,0.0177861) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.565733,-0.000185603) , 
6, 94.4896, 1, 0, 0.598571,0.0129556) , 
2, 82.7338, 1, 0, 0.559318,0.00168039) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.460417,0.0134235) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.42593,-0.0106543) , 
6, 140.479, 1, 0, 0.44723,0.00441809) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.349347,-0.0203376) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.32115,0.00684203) , 
1, 80.9974, 1, 0, 0.337726,-0.00972128) , 
7, 2.13058, 1, 0, 0.390021,-0.00296886) , 
3, 363.189, 1, 0, 0.5,5.13951e-05)    );
  // itree = 75
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.595771,-0.00121569) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.387084,0.0155074) , 
4, 428.69, 1, 0, 0.522886,0.00478839) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.552128,0.00343679) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.480244,-0.00460601) , 
7, 1.64044, 1, 0, 0.506681,-0.00200018) , 
6, 46.695, 1, 0, 0.510593,-0.000361257) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.372005,0.00627913) , 
5, 208.075, 1, 0, 0.5,0.000149291)    );
  // itree = 76
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.509791,-0.00839175) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.600177,0.00173016) , 
8, -1.11466, 1, 0, 0.573431,-0.00174976) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.493246,0.0190706) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.541081,0.00229083) , 
9, -1.52005, 1, 0, 0.529076,0.00828241) , 
0, 70.2313, 1, 0, 0.559318,0.00144228) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.438612,0.00897002) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.378081,-0.0086957) , 
5, 120.036, 1, 0, 0.40558,-0.000147098) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.313225,-0.0149722) , 
8, 1.51999, 1, 0, 0.390021,-0.00254984) , 
3, 363.189, 1, 0, 0.5,4.35311e-05)    );
  // itree = 77
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.61635,0.0129232) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.578575,2.80791e-05) , 
6, 26.8836, 1, 0, 0.583195,0.00219006) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.488394,-0.0163825) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.459025,0.00493569) , 
9, 0.911789, 1, 0, 0.478328,-0.0108785) , 
3, 305.046, 1, 0, 0.556495,-0.00113729) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.348266,-0.015975) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.37402,0.00684081) , 
5, 114.856, 1, 0, 0.363805,-0.00216355) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.444491,0.0136039) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.340703,-0.00233352) , 
9, 0.912113, 1, 0, 0.398065,0.0071699) , 
10, -0.101174, 1, 0, 0.382135,0.00283004) , 
4, 522.186, 1, 0, 0.5,0.000148179)    );
  // itree = 78
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.606273,0.0115631) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.530458,-0.00419784) , 
0, 34.5298, 1, 0, 0.544099,-0.00163167) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.524132,0.00875366) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.34447,-0.00303732) , 
3, 406.832, 1, 0, 0.462677,0.00641533) , 
0, 65.1096, 1, 0, 0.510614,0.00167761) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.520135,0.000469192) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.408757,-0.0150581) , 
0, 74.2165, 1, 0, 0.48726,-0.00450463) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.48139,0.00740683) , 
8, 2.12809, 1, 0, 0.486105,-0.0018271) , 
10, 0.30405, 1, 0, 0.5,0.000159778)    );
  // itree = 79
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.381982,0.000640951) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.392522,-0.0136927) , 
2, 35.8609, 1, 0, 0.386106,-0.00519927) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.600497,-0.000684972) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.427955,0.0116589) , 
3, 420.186, 1, 0, 0.562228,0.0021234) , 
2, 40.0969, 1, 0, 0.502516,-0.000359274) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.474127,0.00480788) , 
2, 134.344, 1, 0, 0.5,0.000193056)    );
  // itree = 80
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.461935,0.00504444) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.624051,-0.00383396) , 
2, 41.9074, 1, 0, 0.550751,-9.88635e-05) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.64646,0.0127644) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.542916,-0.00106973) , 
3, 286.72, 1, 0, 0.598571,0.00894488) , 
2, 82.7338, 1, 0, 0.559318,0.00152137) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.47557,0.0126654) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.37718,-0.00541181) , 
0, 44.1363, 1, 0, 0.404083,-0.000225538) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.315407,-0.0164096) , 
3, 686.153, 1, 0, 0.390021,-0.00249702) , 
3, 363.189, 1, 0, 0.5,0.000113414)    );
  // itree = 81
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.467022,-0.00492407) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.454633,-0.00925607) , 
8, -2.51414, 1, 0, 0.460762,-0.00875405) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.529488,0.000498299) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.46275,0.0131981) , 
9, 1.92529, 1, 0, 0.518163,0.00311001) , 
8, -1.9255, 1, 0, 0.50957,0.00133395) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.665241,0.00843565) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.451501,-0.00904745) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.384899,0.00720963) , 
5, 149.613, 1, 0, 0.43366,-0.00582093) , 
4, 318.476, 1, 0, 0.480104,-0.00232486) , 
7, 2.72312, 1, 0, 0.5,0.000145607)    );
  // itree = 82
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.525203,0.00915004) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.52206,8.19246e-05) , 
8, -2.128, 1, 0, 0.522528,0.00186102) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.363609,-0.00825086) , 
1, 123.358, 1, 0, 0.505777,0.000822501) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.448178,-0.0051717) , 
9, 2.53327, 1, 0, 0.5,0.000140397)    );
  // itree = 83
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.59017,0.00544504) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.617216,-0.00341806) , 
10, -0.709103, 1, 0, 0.606499,0.000186103) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.509182,-0.0116136) , 
4, 400.228, 1, 0, 0.593356,-0.00181938) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.389137,0.0136053) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.328405,0.0135905) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.42468,-0.00123175) , 
9, -2.33041, 1, 0, 0.412842,0.000390879) , 
6, 37.1952, 1, 0, 0.410092,0.00205761) , 
4, 427.67, 1, 0, 0.5,0.00015558)    );
  // itree = 84
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.654183,0.0134022) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.662546,-0.00450012) , 
5, 54.4709, 1, 0, 0.659737,0.00246571) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.599909,-0.0156081) , 
10, 1.72286, 1, 0, 0.645333,-0.00321987) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.463581,0.00127798) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.408904,-0.0198298) , 
8, 1.92543, 1, 0, 0.458674,-0.000753255) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.446574,-0.00110818) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.410828,0.0209687) , 
8, 1.72225, 1, 0, 0.432129,0.00860608) , 
10, 1.72279, 1, 0, 0.453505,0.00106917) , 
4, 333.155, 1, 0, 0.5,2.96038e-05)    );
  // itree = 85
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.565096,0.00128408) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.347095,-0.0221592) , 
3, 277.366, 1, 0, 0.469645,-0.00893406) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.393057,-0.0040298) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.567799,0.00274206) , 
2, 40.0969, 1, 0, 0.507873,0.00085937) , 
10, -2.12808, 1, 0, 0.502516,-0.000513019) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.474127,0.00432499) , 
2, 134.344, 1, 0, 0.5,-1.7646e-07)    );
  // itree = 86
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.489978,-0.014289) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.720784,0.0159293) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.424635,-0.0102581) , 
8, 0.708935, 1, 0, 0.593075,0.00573899) , 
10, -0.304159, 1, 0, 0.553379,-0.00296099) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.497532,0.00281958) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.479601,-0.00269135) , 
7, 2.46524, 1, 0, 0.487952,-0.000133096) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.457783,0.0141935) , 
0, 140.536, 1, 0, 0.485935,0.00095834) , 
7, 1.39043, 1, 0, 0.5,0.000140979)    );
  // itree = 87
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.519297,0.00203438) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.552501,-0.00759864) , 
2, 74.1892, 1, 0, 0.526189,-8.62585e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.508662,0.00902496) , 
2, 115.619, 1, 0, 0.524328,0.00113369) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.369453,-0.0144199) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.511332,0.0104574) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.366812,-0.000814671) , 
10, 0.304888, 1, 0, 0.431515,0.0051793) , 
8, -0.0949297, 1, 0, 0.404134,-0.00349116) , 
5, 148.686, 1, 0, 0.5,0.000197586)    );
  // itree = 88
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.556461,-0.00136714) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.61208,0.00676267) , 
2, 80.1463, 1, 0, 0.566617,0.000279172) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.485526,0.0110665) , 
3, 337.229, 1, 0, 0.559318,0.0014507) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.365617,0.00210733) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.439846,-0.0124734) , 
2, 76.6182, 1, 0, 0.398096,-0.00527262) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.367107,0.00690491) , 
1, 107.835, 1, 0, 0.390021,-0.00216858) , 
3, 363.189, 1, 0, 0.5,0.000182585)    );
  // itree = 89
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.543323,-0.012606) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.472806,0.00204243) , 
7, 1.18607, 1, 0, 0.485586,-0.000732921) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.504244,-0.00296511) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.620438,0.0176476) , 
10, -0.840109, 1, 0, 0.55556,0.00786957) , 
8, 0.10144, 1, 0, 0.504225,0.00155855) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.643845,-0.00198278) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.496355,0.0160288) , 
4, 467.026, 1, 0, 0.580697,0.00681225) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.484577,-0.019803) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.446035,0.00164738) , 
8, 0.88596, 1, 0, 0.457219,-0.00512468) , 
8, 0.101348, 1, 0, 0.495359,-0.00143751) , 
10, 0.101373, 1, 0, 0.5,0.000130759)    );
  // itree = 90
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.506941,-0.00246069) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.619661,0.0121722) , 
5, 65.1774, 1, 0, 0.583669,0.00885749) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.40849,-0.0164528) , 
0, 84.3312, 1, 0, 0.548932,0.00341889) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.506618,0.00139889) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.468201,-0.00730353) , 
6, 68.4027, 1, 0, 0.491096,-0.00246964) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.409279,0.010922) , 
6, 132.38, 1, 0, 0.483081,-0.00103212) , 
7, 1.55701, 1, 0, 0.5,0.000111466)    );
  // itree = 91
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.450871,-0.00975703) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.527501,0.00636968) , 
7, 2.86446, 1, 0, 0.478878,-0.00440523) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.456706,0.0208364) , 
6, 103.937, 1, 0, 0.472915,0.00346429) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.51432,-0.00811752) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.552177,0.0088277) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.496834,-0.00142085) , 
5, 60.1818, 1, 0, 0.506012,0.000498637) , 
8, -1.9254, 1, 0, 0.506898,-0.000682768) , 
10, -1.72272, 1, 0, 0.5,0.000159029)    );
  // itree = 92
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.522638,0.00808826) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.537837,0.00279176) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.465525,-0.00349773) , 
8, 0.303742, 1, 0, 0.507783,0.000221257) , 
6, 50.2358, 1, 0, 0.50957,0.00139485) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.498821,-0.00170227) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.464493,0.0121779) , 
10, -1.31096, 1, 0, 0.487095,0.00348624) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.484096,-0.0119976) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.46282,6.54694e-05) , 
0, 65.124, 1, 0, 0.474109,-0.00767427) , 
10, -0.30401, 1, 0, 0.480104,-0.00252183) , 
7, 2.72312, 1, 0, 0.5,0.000122758)    );
  // itree = 93
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.592317,-0.00194263) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.447312,0.00905302) , 
4, 428.956, 1, 0, 0.566177,-0.00023497) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.511747,0.0154306) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.547149,-0.000208017) , 
9, -0.709487, 1, 0, 0.533842,0.00726155) , 
0, 83.6416, 1, 0, 0.559318,0.0013552) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.452833,-0.00211887) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.497716,0.0116258) , 
1, 78.0899, 1, 0, 0.472213,0.00420381) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.339943,0.00409218) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.338373,-0.0115622) , 
8, -0.709366, 1, 0, 0.338904,-0.0061783) , 
7, 1.81428, 1, 0, 0.390021,-0.00219733) , 
3, 363.189, 1, 0, 0.5,0.000110475)    );
  // itree = 94
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.47752,-0.00964831) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.556074,0.00330066) , 
9, -2.35692, 1, 0, 0.544066,0.0018093) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.431365,-0.00107298) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.423363,-0.0239708) , 
9, 0.310463, 1, 0, 0.429223,-0.00771322) , 
1, 82.3043, 1, 0, 0.511907,-0.000857274) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.490932,-0.00863291) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.419137,0.0232664) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.444883,0.00283786) , 
10, 1.11415, 1, 0, 0.432203,0.014234) , 
5, 89.8565, 1, 0, 0.457496,0.00357485) , 
9, 1.72261, 1, 0, 0.5,0.000112609)    );
  // itree = 95
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.623872,0.0094275) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.536355,-0.0015512) , 
7, 1.49996, 1, 0, 0.558465,0.00137845) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.411413,-0.0209295) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.419421,0.00322637) , 
9, 0.10159, 1, 0, 0.415538,-0.00884472) , 
5, 148.686, 1, 0, 0.522846,-0.0011693) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.520658,0.00355825) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.331783,-0.0195074) , 
3, 354.999, 1, 0, 0.48221,-0.000314945) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.315197,0.0204303) , 
4, 625.915, 1, 0, 0.455983,0.00264727) , 
8, 0.709448, 1, 0, 0.5,0.000134753)    );
  // itree = 96
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.510464,-0.000231496) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.537624,0.0126111) , 
2, 100.732, 1, 0, 0.51289,0.00123265) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.435774,0.00922346) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.470017,-0.00868593) , 
10, -1.24549, 1, 0, 0.460998,-0.00456375) , 
6, 111.25, 1, 0, 0.500111,-0.00019475) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.498318,0.00462623) , 
10, 2.73618, 1, 0, 0.5,0.00017945)    );
  // itree = 97
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.478151,0.00209875) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.439065,-0.0120614) , 
8, -2.31774, 1, 0, 0.455981,-0.00701254) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.53769,0.00121976) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.466233,0.0135295) , 
9, 1.92529, 1, 0, 0.525962,0.00380552) , 
8, -1.31752, 1, 0, 0.50957,0.00127155) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.665241,0.00700431) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.460714,-0.00805007) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.386725,0.00221485) , 
1, 80.9974, 1, 0, 0.43366,-0.00521003) , 
4, 318.476, 1, 0, 0.480104,-0.0022377) , 
7, 2.72312, 1, 0, 0.5,0.000131784)    );
  // itree = 98
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.533856,0.00223925) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.440269,-0.00647671) , 
6, 139.749, 1, 0, 0.522528,0.00152976) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.363609,-0.00652518) , 
1, 123.358, 1, 0, 0.505777,0.000705423) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.448178,-0.00422244) , 
9, 2.53327, 1, 0, 0.5,0.000143122)    );
  // itree = 99
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.628261,0.00732349) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.574178,-8.69005e-06) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.44239,-0.0116453) , 
4, 451.137, 1, 0, 0.547656,-0.00268093) , 
1, 19.3516, 1, 0, 0.556495,-0.00132074) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.404406,0.00159013) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.358109,0.0185742) , 
7, 2.90669, 1, 0, 0.393477,0.00564095) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.334945,-0.00673675) , 
10, 1.51998, 1, 0, 0.382135,0.00327014) , 
4, 522.186, 1, 0, 0.5,0.000166769)    );
   return;
};
 
// Clean up
inline void ReadBDT::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDT::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
