// Class: ReadBDT
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.10/04       [395780]
Creator        : marine5575
Date           : Wed Oct  9 19:51:14 2019
Host           : Linux htop.hanyang.ac.kr 2.6.32-696.el6.centos.plus.x86_64 #1 SMP Mon Apr 3 14:56:08 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/marine5575/work/Undergrad2018/mva
Training events: 50004
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "50" [Number of trees in the forest]
MaxDepth: "4" [Max depth of the decision tree allowed]
MinNodeSize: "5%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
nCuts: "30" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "Grad" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
Shrinkage: "5.000000e-01" [Learning rate for GradBoost algorithm]
SeparationType: "giniindex" [Separation criterion for node splitting]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
UseBaggedBoost: "False" [Use only a random subsample of all events for growing the trees in each boost iteration.]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "3" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Poisson distribution in each split with RandomisedTree option]
BaggedSampleFraction: "6.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "pray" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in training sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
RegressionLossFunctionBDTG: "huber" [Loss function for BDTG regression.]
HuberQuantile: "7.000000e-01" [In the Huber loss function this is the quantile that separates the core from the tails in the residuals distribution.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
SkipNormalization: "False" [Skip normalization at initialization, to keep expectation value of BDT output according to the fraction of events]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "6.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 11
lepton1_pt                    lepton1_pt                    lepton1_pt                    lepton1_pt                                                      'F'    [30.0003757477,715.323425293]
met_pt                        met_pt                        met_pt                        met_pt                                                          'F'    [0.19669675827,832.46496582]
tau1_pt                       tau1_pt                       tau1_pt                       tau1_pt                                                         'F'    [30.0003395081,1108.22265625]
jet_ht                        jet_ht                        jet_ht                        jet_ht                                                          'F'    [95.0174484253,2866.1184082]
jetlepmet_ht                  jetlepmet_ht                  jetlepmet_ht                  jetlepmet_ht                                                    'F'    [144.123748779,3074.10449219]
lep1met_pt                    lep1met_pt                    lep1met_pt                    lep1met_pt                                                      'F'    [0.211814135313,920.750061035]
lep1tau1_pt                   lep1tau1_pt                   lep1tau1_pt                   lep1tau1_pt                                                     'F'    [0.167901813984,1148.01318359]
tau1_lep1_dr                  tau1_lep1_dr                  tau1_lep1_dr                  tau1_lep1_dr                                                    'F'    [0.390903234482,5.5550994873]
lep1_met_dphi                 lep1_met_dphi                 lep1_met_dphi                 lep1_met_dphi                                                   'F'    [-3.14144611359,3.1415913105]
tau1_met_dphi                 tau1_met_dphi                 tau1_met_dphi                 tau1_met_dphi                                                   'F'    [-3.14137792587,3.14126992226]
tau1lep1_met_dphi             tau1lep1_met_dphi             tau1lep1_met_dphi             tau1lep1_met_dphi                                               'F'    [-3.14146351814,3.14153146744]
NSpec 2
njet                          njet                          njet                          njet                                                            'F'    [3,12]
nbjet                         nbjet                         nbjet                         nbjet                                                           'F'    [0,6]


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDTNode
   
#ifndef BDTNode__def
#define BDTNode__def
   
class BDTNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDTNode ( BDTNode* left,BDTNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDTNode();

   // test event if it descends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDTNode* GetRight( void )  {return fRight; };

   // test event if it descends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDTNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDTNode*   fLeft;     // pointer to the left daughter node
   BDTNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value applied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDTNode::~BDTNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDTNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDTNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT : public IClassifierReader {

 public:

   // constructor
   ReadBDT( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDT" ),
        fNvars( 11 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "lepton1_pt", "met_pt", "tau1_pt", "jet_ht", "jetlepmet_ht", "lep1met_pt", "lep1tau1_pt", "tau1_lep1_dr", "lep1_met_dphi", "tau1_met_dphi", "tau1lep1_met_dphi" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;
      fVmin[8] = 0;
      fVmax[8] = 0;
      fVmin[9] = 0;
      fVmax[9] = 0;
      fVmin[10] = 0;
      fVmax[10] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[11];
   double fVmax[11];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[11];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDTNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDTNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDTNode*)current->GetRight();
         else current=(BDTNode*)current->GetLeft();
      }
      myMVA += current->GetResponse();
   }
   return 2.0/(1.0+exp(-2.0*myMVA))-1.0;
};

void ReadBDT::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.564448,0.0424338) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.430251,-0.0531729) , 
4, 317.907, 1, 0, 0.491353,-0.00864697) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.740226,0.134203) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.677383,0.104771) , 
1, 43.097, 1, 0, 0.712706,0.212706) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.628595,0.0794887) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.548413,0.0324039) , 
8, 0.912655, 1, 0, 0.602326,0.102326) , 
4, 333.925, 1, 0, 0.654454,0.154454) , 
2, 41.3291, 1, 0, 0.593356,0.0933559) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.48775,-0.00874722) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.551211,0.0341776) , 
1, 78.0899, 1, 0, 0.517636,0.0176364) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.247201,-0.245606) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.409652,-0.0705869) , 
2, 40.1071, 1, 0, 0.315098,-0.184902) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.498438,-0.00110249) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.373145,-0.103673) , 
4, 598.421, 1, 0, 0.440858,-0.0591415) , 
2, 61.3331, 1, 0, 0.379229,-0.120771) , 
7, 1.33982, 1, 0, 0.410092,-0.0899085) , 
4, 427.67, 1, 0, 0.5,3.47623e-15)    );
  // itree = 1
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.446878,-0.0372656) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.617262,0.0780497) , 
8, -1.15379, 1, 0, 0.532861,0.0382491) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.420011,-0.0589062) , 
8, 0.709711, 1, 0, 0.491353,-0.00383384) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.723213,0.0935159) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.572807,0.019656) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.635501,0.0635838) , 
8, -0.910919, 1, 0, 0.613413,0.0772197) , 
4, 316.881, 1, 0, 0.654454,0.10908) , 
2, 41.3291, 1, 0, 0.593356,0.0667822) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.38139,-0.0661259) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.27614,-0.156787) , 
4, 586.699, 1, 0, 0.335107,-0.117854) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.614836,0.0725005) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.419846,-0.0217992) , 
7, 1.48202, 1, 0, 0.492053,0.0252492) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.387455,-0.05148) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.298133,-0.150345) , 
8, 0.303754, 1, 0, 0.35744,-0.0971335) , 
9, 0.984048, 1, 0, 0.435947,-0.0257591) , 
9, -1.31714, 1, 0, 0.410092,-0.0493726) , 
4, 427.67, 1, 0, 0.5,0.00761228)    );
  // itree = 2
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.514512,0.0111836) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.34846,-0.0663984) , 
4, 363.642, 1, 0, 0.437124,-0.0267108) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.647246,0.0642909) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.565531,0.0179743) , 
8, 1.31741, 1, 0, 0.624486,0.0820384) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.465503,-0.0368028) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.561911,0.0319583) , 
8, -0.508362, 1, 0, 0.524738,0.0101353) , 
1, 67.2389, 1, 0, 0.595159,0.0608978) , 
2, 37.1642, 1, 0, 0.556495,0.0394641) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.267642,-0.144813) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.392258,-0.048577) , 
2, 73.8092, 1, 0, 0.32657,-0.106254) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.509008,0.0425986) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.287271,-0.111262) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.382296,-0.0449243) , 
2, 72.8095, 1, 0, 0.332377,-0.0864148) , 
8, 0.434914, 1, 0, 0.411284,-0.0213654) , 
8, -0.506553, 1, 0, 0.382135,-0.0505745) , 
4, 522.186, 1, 0, 0.5,0.0102904)    );
  // itree = 3
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.533681,0.0125264) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.730805,0.0678697) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.674219,0.0419637) , 
4, 289.364, 1, 0, 0.702263,0.089915) , 
2, 38.8518, 1, 0, 0.645333,0.0657345) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.352311,-0.0868721) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.451025,-0.00628414) , 
9, -0.50684, 1, 0, 0.420412,-0.0365113) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.670319,0.105551) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.44445,-0.0163169) , 
0, 66.2266, 1, 0, 0.5684,0.0851742) , 
8, -0.408583, 1, 0, 0.480439,0.0128471) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.249376,-0.120665) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.374164,-0.0570673) , 
2, 36.9049, 1, 0, 0.313431,-0.089907) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.482143,0.00151845) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.414821,-0.0459744) , 
9, 0.100887, 1, 0, 0.458161,-0.0192127) , 
2, 51.4049, 1, 0, 0.398015,-0.0485913) , 
8, 0.709394, 1, 0, 0.453505,-0.00722926) , 
4, 333.155, 1, 0, 0.5,0.0104555)    );
  // itree = 4
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.385366,-0.0324256) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.485057,0.0296445) , 
9, -0.840244, 1, 0, 0.43576,0.00122392) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.362545,-0.0594304) , 
9, 1.3171, 1, 0, 0.415633,-0.0177818) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.5359,0.0113782) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.651496,0.0637594) , 
8, -0.65718, 1, 0, 0.589398,0.0550114) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.507031,-0.0185877) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.539947,0.0267067) , 
0, 61.4003, 1, 0, 0.521485,0.00251354) , 
8, 0.912046, 1, 0, 0.56795,0.0384315) , 
2, 41.9392, 1, 0, 0.515337,0.0190144) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.326257,-0.0798333) , 
4, 805.732, 1, 0, 0.5,0.0104492)    );
  // itree = 5
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.541141,-0.00107905) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.607093,0.0408381) , 
9, -1.93854, 1, 0, 0.590567,0.0457995) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.50151,-0.0267877) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.56103,0.0137276) , 
8, -0.711122, 1, 0, 0.535712,-0.00428262) , 
9, 1.51993, 1, 0, 0.576773,0.033206) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.456627,0.0223951) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.265999,-0.0797427) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.421189,-0.0124365) , 
2, 53.3093, 1, 0, 0.361659,-0.0380283) , 
0, 52.1094, 1, 0, 0.398149,-0.0124778) , 
3, 363.189, 1, 0, 0.521882,0.0191673) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.327633,-0.0709257) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.496875,0.0203292) , 
9, -0.65697, 1, 0, 0.409706,-0.0256101) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.327,-0.0833385) , 
9, 0.912171, 1, 0, 0.383495,-0.0462747) , 
1, 107.586, 1, 0, 0.5,0.00881968)    );
  // itree = 6
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.495984,-0.00727296) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.594563,0.0399633) , 
8, -0.863912, 1, 0, 0.520121,0.00694997) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.422456,-0.0168611) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.318098,-0.0748129) , 
5, 153.827, 1, 0, 0.378822,-0.0450185) , 
1, 82.416, 1, 0, 0.482123,-0.00702529) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.739383,0.0922461) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.489989,0.0168809) , 
0, 66.2266, 1, 0, 0.642954,0.102095) , 
8, -0.199581, 1, 0, 0.525813,0.0226175) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.569941,0.0363129) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.464831,-0.0173787) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.519357,0.00755617) , 
7, 2.22336, 1, 0, 0.494593,-0.00452079) , 
8, 1.35697, 1, 0, 0.519577,0.0139849) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.389743,-0.0507422) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.495094,0.0173907) , 
9, -0.788218, 1, 0, 0.430906,-0.0268486) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.34702,-0.0740221) , 
9, 0.506648, 1, 0, 0.40497,-0.0435432) , 
1, 49.9926, 1, 0, 0.457775,-0.0170369) , 
8, 0.506769, 1, 0, 0.5,0.00757285)    );
  // itree = 7
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.425961,-0.0303121) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.51297,0.0117822) , 
8, -0.305237, 1, 0, 0.482201,-0.00285238) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.62478,0.0539583) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.5159,0.0126527) , 
8, 0.506897, 1, 0, 0.585688,0.0583733) , 
9, -0.526357, 1, 0, 0.523836,0.0217804) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.536251,0.00884375) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.409808,-0.0305029) , 
8, 0.911091, 1, 0, 0.504886,0.000130833) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.285577,-0.0622792) , 
4, 630.178, 1, 0, 0.468396,-0.00992493) , 
9, 0.911974, 1, 0, 0.505413,0.0112447) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.42199,-0.0419525) , 
7, 3.38947, 1, 0, 0.5,0.00722991)    );
  // itree = 8
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.702629,0.0462421) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.581869,-0.00869801) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.647024,0.0227746) , 
8, -0.912733, 1, 0, 0.623401,0.0172446) , 
1, 26.9961, 1, 0, 0.645333,0.0323645) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.567535,0.0334018) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.503468,0.0204925) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.428073,-0.0204209) , 
0, 38.5574, 1, 0, 0.442422,-0.0150027) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.44546,0.0331238) , 
0, 118.431, 1, 0, 0.442845,-0.00718974) , 
7, 0.890664, 1, 0, 0.453505,-0.00257928) , 
4, 333.155, 1, 0, 0.5,0.00589031)    );
  // itree = 9
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.506721,-0.00899861) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.273594,-0.077843) , 
4, 363.547, 1, 0, 0.378552,-0.0463059) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.568158,0.0455043) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.367047,-0.0309002) , 
8, 0.408897, 1, 0, 0.442473,0.00262212) , 
8, -0.709137, 1, 0, 0.419479,-0.0149787) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.587347,0.0193967) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.508651,-0.00687361) , 
8, 0.912046, 1, 0, 0.562835,0.0160375) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.541792,0.0456134) , 
0, 121.101, 1, 0, 0.560876,0.0206051) , 
2, 43.0178, 1, 0, 0.510172,0.00784493) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.313148,-0.0546594) , 
4, 900.248, 1, 0, 0.5,0.00460364)    );
  // itree = 10
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.611144,0.00929306) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.461227,-0.0191378) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.305752,-0.0518988) , 
4, 476.819, 1, 0, 0.381582,-0.0383861) , 
4, 351.719, 1, 0, 0.461954,-0.0202311) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.567748,0.0258605) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.482612,-0.0209382) , 
6, 140.199, 1, 0, 0.556714,0.0279364) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.415259,-0.0320927) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.500922,0.00456922) , 
10, 0.101856, 1, 0, 0.476957,-0.00643902) , 
9, 1.01656, 1, 0, 0.525366,0.0144255) , 
9, -1.92538, 1, 0, 0.513664,0.00802977) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.354246,-0.0326706) , 
1, 134.434, 1, 0, 0.5,0.00438379)    );
  // itree = 11
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.577303,-0.00535969) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.410394,-0.0482741) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.346632,-0.0281278) , 
3, 345.692, 1, 0, 0.373971,-0.0425761) , 
4, 367.164, 1, 0, 0.463426,-0.0272138) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.485472,0.0299381) , 
0, 87.0345, 1, 0, 0.468224,-0.0128809) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.724227,0.0679118) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.560326,0.0196888) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.385768,-0.0436016) , 
0, 98.5291, 1, 0, 0.508225,0.00383667) , 
0, 47.5633, 1, 0, 0.587358,0.0402247) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.598676,0.0124403) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.403564,-0.0131824) , 
3, 273.798, 1, 0, 0.498647,0.000930064) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.353136,-0.0376706) , 
1, 83.1899, 1, 0, 0.462545,-0.00930373) , 
8, 0.395781, 1, 0, 0.514484,0.0113069) , 
8, -0.911981, 1, 0, 0.5,0.00373376)    );
  // itree = 12
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.454704,0.00442433) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.37943,-0.0399841) , 
7, 2.56165, 1, 0, 0.427098,-0.0131925) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.213512,-0.0868767) , 
3, 426.748, 1, 0, 0.386106,-0.0230956) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.639561,0.0407569) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.662531,0.0154991) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.473602,-0.00283962) , 
3, 262.197, 1, 0, 0.552562,0.00739019) , 
7, 1.03261, 1, 0, 0.562228,0.0130911) , 
2, 40.0969, 1, 0, 0.502516,0.000822422) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.474127,0.0288229) , 
2, 134.344, 1, 0, 0.5,0.0040104)    );
  // itree = 13
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.488514,-0.00974039) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.324345,-0.0584899) , 
1, 66.4223, 1, 0, 0.428499,-0.0296354) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.581036,0.0279177) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.534122,0.0093129) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.422482,-0.0222301) , 
1, 39.0127, 1, 0, 0.457219,-0.0143168) , 
9, 0.807322, 1, 0, 0.502233,0.00523984) , 
9, -0.304183, 1, 0, 0.476568,-0.00689946) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.662378,0.0464046) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.463978,-0.00948478) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.556269,0.0211477) , 
9, -1.02353, 1, 0, 0.50512,0.00644197) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.498606,0.0115805) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.392811,-0.037188) , 
5, 72.802, 1, 0, 0.433627,-0.0194105) , 
9, 0.506648, 1, 0, 0.482076,-0.00189099) , 
8, 0.140867, 1, 0, 0.517596,0.0115864) , 
8, -0.303945, 1, 0, 0.5,0.00365817)    );
  // itree = 14
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.475235,-0.0110227) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.444966,-0.0320567) , 
0, 38.1773, 1, 0, 0.460169,-0.0266393) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.737036,0.0656723) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.600437,0.027553) , 
7, 1.8221, 1, 0, 0.659357,0.062256) , 
8, -1.12784, 1, 0, 0.585474,0.0292831) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.522268,0.0285192) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.428768,-0.0224915) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.49067,-0.00092761) , 
8, -0.241387, 1, 0, 0.460288,-0.0136239) , 
8, -2.13456, 1, 0, 0.471674,-0.00410704) , 
0, 48.1095, 1, 0, 0.51373,0.00823261) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.458693,-0.0417334) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.462358,-0.0195804) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.428173,-0.00603128) , 
10, 1.76826, 1, 0, 0.443391,-0.0149375) , 
10, 0.303835, 1, 0, 0.448192,-0.0267427) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.47455,0.0169231) , 
0, 74.2188, 1, 0, 0.456384,-0.0118082) , 
8, 1.31748, 1, 0, 0.5,0.00343428)    );
  // itree = 15
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.600374,0.0247593) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.510809,-0.000464955) , 
0, 35.7039, 1, 0, 0.524131,0.00448061) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.474594,0.0287724) , 
0, 118.429, 1, 0, 0.519206,0.00764691) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.35753,-0.0213989) , 
1, 134.434, 1, 0, 0.505413,0.00513418) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.42199,-0.0217377) , 
7, 3.38947, 1, 0, 0.5,0.00315698)    );
  // itree = 16
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.490149,0.0072431) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.758708,0.0578315) , 
10, -0.657262, 1, 0, 0.634998,0.0493874) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.449634,-0.0122447) , 
10, 0.709141, 1, 0, 0.579525,0.0301767) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.502531,0.00132488) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.450405,-0.0209493) , 
6, 76.6072, 1, 0, 0.486604,-0.00650447) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.522986,0.0352944) , 
2, 121.743, 1, 0, 0.489581,-0.00203253) , 
7, 1.56383, 1, 0, 0.509481,0.00509388) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.45707,-0.0445036) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.393203,0.0138339) , 
7, 1.39484, 1, 0, 0.425281,-0.019798) , 
6, 148.277, 1, 0, 0.5,0.00229096)    );
  // itree = 17
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.478528,-0.00889004) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.683711,0.0306699) , 
8, -0.944718, 1, 0, 0.567977,0.0121246) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.615719,0.00783221) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.401297,-0.0206381) , 
4, 312.591, 1, 0, 0.462539,-0.0139132) , 
8, 1.11481, 1, 0, 0.532102,0.00326541) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.528757,0.0354194) , 
0, 97.052, 1, 0, 0.531834,0.00681893) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.342725,-0.0530446) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.43928,0.00467095) , 
9, 0.101131, 1, 0, 0.40067,-0.0182767) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.610558,0.034085) , 
8, -0.140853, 1, 0, 0.468616,0.00289241) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.378954,-0.0398347) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.37537,-0.00198842) , 
8, 0.944584, 1, 0, 0.377421,-0.0255251) , 
8, 0.303886, 1, 0, 0.435485,-0.00743166) , 
5, 118.991, 1, 0, 0.5,0.00211055)    );
  // itree = 18
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.593273,0.0227133) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.586958,0.0186297) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.532731,0.0194263) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.483286,-0.00561276) , 
6, 23.4315, 1, 0, 0.487417,-0.00418539) , 
7, 0.890664, 1, 0, 0.495075,-0.00199) , 
0, 33.5659, 1, 0, 0.50405,0.000918901) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.440264,0.0203277) , 
0, 140.536, 1, 0, 0.5,0.0024164)    );
  // itree = 19
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.436686,0.0050341) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.444254,-0.00241232) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.334422,-0.0398517) , 
7, 2.04296, 1, 0, 0.397238,-0.0189335) , 
6, 42.8037, 1, 0, 0.407863,-0.0122194) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.617885,0.024423) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.569385,0.00224632) , 
2, 49.3625, 1, 0, 0.579204,0.00918045) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.572529,0.0247668) , 
0, 110.617, 1, 0, 0.578525,0.0118666) , 
2, 40.3687, 1, 0, 0.523181,0.00405577) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.380622,0.00823846) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.310425,-0.0342047) , 
0, 74.2239, 1, 0, 0.342271,-0.0143439) , 
4, 711.217, 1, 0, 0.5,0.0016981)    );
  // itree = 20
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.480408,-0.0170841) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.469411,-0.00593201) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.574864,0.0145731) , 
8, -0.709723, 1, 0, 0.539761,0.0100162) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.420937,-0.021301) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.461837,0.00952704) , 
7, 2.1306, 1, 0, 0.444594,-0.00381743) , 
0, 74.2148, 1, 0, 0.508422,0.00546077) , 
5, 29.9066, 1, 0, 0.506554,0.00364027) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.442884,-0.00788936) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.441555,-0.0183942) , 
10, -0.101281, 1, 0, 0.442211,-0.0156729) , 
7, 3.22288, 1, 0, 0.5,0.00167317)    );
  // itree = 21
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.659454,0.0176502) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.438176,-0.0036575) , 
3, 311.121, 1, 0, 0.573852,0.0136388) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.417671,-0.0367774) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.455551,-0.0016722) , 
5, 56.9145, 1, 0, 0.448838,-0.00934827) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.559432,0.0316293) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.552009,0.00647379) , 
8, -2.12782, 1, 0, 0.553393,0.0149975) , 
9, -0.84023, 1, 0, 0.504152,0.00353167) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.472489,0.000908529) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.386711,-0.0342507) , 
6, 53.2261, 1, 0, 0.418484,-0.0229513) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.469392,0.00368783) , 
10, 1.92565, 1, 0, 0.436717,-0.0131027) , 
9, 1.31728, 1, 0, 0.48569,-0.00102253) , 
1, 27.0441, 1, 0, 0.5,0.00135729)    );
  // itree = 22
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.447365,-0.0110967) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.542867,0.013692) , 
8, -1.52043, 1, 0, 0.524002,0.0110111) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.487519,-0.0225187) , 
2, 93.9335, 1, 0, 0.519884,0.00660766) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.645132,0.0169875) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.570482,-0.00773769) , 
5, 78.8439, 1, 0, 0.607769,0.00698813) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.391221,-0.023157) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.381726,-0.00127419) , 
0, 100.226, 1, 0, 0.389202,-0.0205926) , 
3, 253.656, 1, 0, 0.481334,-0.00896653) , 
7, 2.39535, 1, 0, 0.502516,-0.000409162) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.474127,0.0150372) , 
2, 134.344, 1, 0, 0.5,0.00129755)    );
  // itree = 23
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.441891,0.00482289) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.48699,0.0294888) , 
0, 72.7813, 1, 0, 0.45846,0.0172433) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.553271,0.00145168) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.385111,-0.0254314) , 
5, 109.298, 1, 0, 0.487421,-0.00961414) , 
10, -1.72193, 1, 0, 0.478244,-0.00110416) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.728577,0.0354825) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.567747,-0.00307761) , 
7, 2.33603, 1, 0, 0.6652,0.0272213) , 
8, -0.251718, 1, 0, 0.523157,0.00570047) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.476254,-0.0184557) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.51363,0.00203356) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.399933,-0.0198697) , 
5, 88.2304, 1, 0, 0.469225,-0.00695632) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.453929,0.0205012) , 
0, 96.3259, 1, 0, 0.466311,-0.000958687) , 
7, 1.39043, 1, 0, 0.468181,-0.00496975) , 
8, 0.304091, 1, 0, 0.5,0.00120601)    );
  // itree = 24
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.501667,0.00772653) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.728351,0.0356142) , 
9, -0.911179, 1, 0, 0.633364,0.0311492) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.47684,-0.00561587) , 
10, 0.506477, 1, 0, 0.579525,0.0181024) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.587611,0.0136912) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.472481,-0.00662232) , 
1, 20.872, 1, 0, 0.484933,-0.0051681) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.524272,0.0194359) , 
2, 108.637, 1, 0, 0.489581,-0.00147586) , 
7, 1.56383, 1, 0, 0.509481,0.00285589) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.45314,-0.0252618) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.391176,0.0108871) , 
7, 1.53826, 1, 0, 0.425281,-0.0113427) , 
6, 148.277, 1, 0, 0.5,0.00125708)    );
  // itree = 25
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.524292,0.0143963) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.515066,0.00039551) , 
10, 0.709242, 1, 0, 0.520833,0.0118174) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.474179,0.011686) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.575627,0.0117808) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.409221,-0.0240187) , 
0, 84.3312, 1, 0, 0.542162,0.0062115) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.456773,-0.0143302) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.490536,0.00745826) , 
10, 1.31105, 1, 0, 0.467933,-0.00830159) , 
7, 1.80319, 1, 0, 0.498128,-0.00239802) , 
10, -2.53343, 1, 0, 0.496019,-0.000900138) , 
6, 37.1952, 1, 0, 0.5,0.00114001)    );
  // itree = 26
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.476184,-0.000580198) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.416065,-0.0205493) , 
9, 1.92509, 1, 0, 0.464209,-0.00541943) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.596663,0.0166742) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.518749,-0.00478273) , 
10, 0.304513, 1, 0, 0.562655,0.00929502) , 
8, -0.840083, 1, 0, 0.520256,0.00295773) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.38255,-0.0300706) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.491683,-0.00593887) , 
2, 49.2675, 1, 0, 0.442493,-0.0191801) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.472297,0.00537915) , 
0, 65.6571, 1, 0, 0.453047,-0.010037) , 
8, 1.31748, 1, 0, 0.50405,-0.000175598) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.440264,0.0147712) , 
0, 140.536, 1, 0, 0.5,0.00095004)    );
  // itree = 27
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.524729,0.00136529) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.503729,0.020435) , 
0, 105.505, 1, 0, 0.522806,0.00393152) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.465388,-0.0229779) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.418699,0.00373476) , 
7, 1.61139, 1, 0, 0.445443,-0.0139697) , 
6, 132.38, 1, 0, 0.511579,0.00133369) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.342219,-0.0236784) , 
1, 144.924, 1, 0, 0.500111,-0.00028818) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.498318,0.0142876) , 
10, 2.73618, 1, 0, 0.5,0.000861635)    );
  // itree = 28
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.557506,0.0161887) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.468439,-0.00313531) , 
5, 84.7802, 1, 0, 0.515365,0.00944459) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.422504,-0.00952798) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.501832,0.0210317) , 
7, 2.0942, 1, 0, 0.459781,0.00647148) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.535391,-0.00290276) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.42106,-0.0262639) , 
7, 2.0775, 1, 0, 0.482862,-0.0154875) , 
10, -1.72272, 1, 0, 0.475457,-0.00844225) , 
6, 47.2653, 1, 0, 0.485051,-0.00414196) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.604002,-0.000157232) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.575207,0.0238827) , 
1, 58.4891, 1, 0, 0.589121,0.0162913) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.575122,0.0159298) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.466899,9.91725e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.431026,-0.0180861) , 
7, 2.92134, 1, 0, 0.458138,-0.00505338) , 
1, 27.4351, 1, 0, 0.477995,-0.000648242) , 
9, 0.585143, 1, 0, 0.51174,0.00449578) , 
9, -0.304053, 1, 0, 0.5,0.000696077)    );
  // itree = 29
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.681643,0.019839) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.557945,-0.00974194) , 
1, 52.5223, 1, 0, 0.627134,0.010005) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.532928,0.0204014) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.507907,0.00187091) , 
6, 37.1952, 1, 0, 0.510838,0.0050699) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.41898,-0.0202574) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.431077,0.00118499) , 
0, 52.1113, 1, 0, 0.425732,-0.00972123) , 
8, 1.11472, 1, 0, 0.489088,0.00128973) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.405271,-0.0167146) , 
7, 3.22288, 1, 0, 0.480718,-0.000708924) , 
3, 184.408, 1, 0, 0.5,0.000702012)    );
  // itree = 30
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.677222,0.0115311) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.490109,-0.000467105) , 
4, 290.44, 1, 0, 0.51694,0.00181393) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.449334,-0.0156411) , 
9, 2.53327, 1, 0, 0.51052,-0.000102183) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.504187,0.0225817) , 
2, 147.158, 1, 0, 0.510172,0.00151828) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.313148,-0.0156564) , 
4, 900.248, 1, 0, 0.5,0.000691233)    );
  // itree = 31
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.490549,-0.00201719) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.638511,0.0164899) , 
10, -0.260609, 1, 0, 0.544458,0.00614588) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.461457,-0.0118591) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.51118,0.0142911) , 
2, 92.6686, 1, 0, 0.472999,-0.00638602) , 
7, 2.44163, 1, 0, 0.514317,0.000860072) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.459761,-0.0160401) , 
10, 0.741513, 1, 0, 0.50787,-0.00146633) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.429781,-0.0158229) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.418543,-0.00255406) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.539608,0.0268433) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.522384,0.00562894) , 
7, 2.82953, 1, 0, 0.531645,0.0220943) , 
7, 1.97243, 1, 0, 0.491635,0.0132485) , 
9, -1.11466, 1, 0, 0.478208,0.00641356) , 
10, 1.31744, 1, 0, 0.5,0.000624461)    );
  // itree = 32
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.456197,0.00458228) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.62531,0.0237027) , 
2, 39.5868, 1, 0, 0.535995,0.0177123) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.534618,0.0136146) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.536775,0.00851178) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.469633,-0.0114558) , 
8, -1.72223, 1, 0, 0.484382,-0.00818905) , 
6, 24.0539, 1, 0, 0.49674,-0.00185993) , 
7, 2.40619, 1, 0, 0.509712,0.00460772) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.463021,0.00942735) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.609665,0.00877624) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.470156,-0.0136031) , 
7, 1.01859, 1, 0, 0.499374,-0.0102976) , 
10, -1.90594, 1, 0, 0.492285,-0.00603041) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.482589,0.0153739) , 
10, 2.33048, 1, 0, 0.491119,-0.00297503) , 
6, 74.2224, 1, 0, 0.5,0.000646987)    );
  // itree = 33
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.480922,-0.00992629) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.538117,0.0175113) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.512387,0.00289202) , 
6, 20.4709, 1, 0, 0.521749,0.0104856) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.557867,0.0200073) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.517495,-0.00171333) , 
6, 73.1844, 1, 0, 0.526127,0.00360616) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.46562,-0.00839653) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.472779,0.019) , 
0, 118.429, 1, 0, 0.466905,-0.00405924) , 
7, 2.11703, 1, 0, 0.497636,-8.16278e-05) , 
6, 37.1952, 1, 0, 0.501379,0.0015588) , 
5, 29.9066, 1, 0, 0.5,0.000608188)    );
  // itree = 34
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.424478,0.00105987) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.431157,-0.0184484) , 
2, 35.861, 1, 0, 0.427098,-0.00754593) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.213512,-0.0453928) , 
3, 426.748, 1, 0, 0.386106,-0.0118417) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.636462,0.022482) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.606006,0.00475717) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.456069,-0.0175785) , 
5, 102.666, 1, 0, 0.553863,-0.00308319) , 
7, 1.81431, 1, 0, 0.583055,0.00821414) , 
2, 40.0976, 1, 0, 0.482477,-0.00202795) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.465521,-0.026137) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.556961,0.00296182) , 
8, -0.304323, 1, 0, 0.520671,-0.0104211) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.615622,0.00771326) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.626234,0.0260486) , 
0, 60.2388, 1, 0, 0.620961,0.0245099) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.416852,0.00656735) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.40109,-0.0120852) , 
7, 2.8296, 1, 0, 0.409102,-0.00302769) , 
3, 362.955, 1, 0, 0.53037,0.0127348) , 
7, 1.97243, 1, 0, 0.526847,0.00432271) , 
2, 64.7817, 1, 0, 0.5,0.000480149)    );
  // itree = 35
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.468423,-0.0208542) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.704545,0.00791628) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.592444,-0.00473594) , 
4, 291.315, 1, 0, 0.623641,-0.00161534) , 
2, 35.6682, 1, 0, 0.592208,-0.00650622) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.601432,0.0182194) , 
0, 87.9445, 1, 0, 0.593356,-0.00253186) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.36725,-0.0202377) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.357471,0.0086593) , 
0, 48.535, 1, 0, 0.362516,-0.00659503) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.488753,0.0243791) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.434552,0.00473137) , 
1, 103.27, 1, 0, 0.471658,0.0211782) , 
10, -0.506823, 1, 0, 0.432118,0.0111165) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.349372,0.00269885) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.398541,-0.0309893) , 
2, 73.8158, 1, 0, 0.368752,-0.0125753) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.406309,0.011109) , 
7, 2.90669, 1, 0, 0.37997,-0.00512798) , 
0, 74.2165, 1, 0, 0.410092,0.00425511) , 
4, 427.67, 1, 0, 0.5,0.00092546)    );
  // itree = 36
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.460839,0.00914769) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.479871,-0.00654671) , 
10, -1.69642, 1, 0, 0.472294,-0.000250352) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.719738,0.0264822) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.529486,0.00421138) , 
7, 2.09461, 1, 0, 0.616419,0.0182879) , 
8, -0.160146, 1, 0, 0.514643,0.00519683) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.4728,-0.0130331) , 
8, 1.72285, 1, 0, 0.510614,0.00312013) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.519005,-0.00593598) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.613486,0.0138771) , 
8, -1.47474, 1, 0, 0.571108,0.00645736) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.479275,-0.00373626) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.365934,-0.0306502) , 
0, 74.2184, 1, 0, 0.440254,-0.0139159) , 
8, 0.0879124, 1, 0, 0.48726,-0.00659737) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.48139,0.0121613) , 
8, 2.12809, 1, 0, 0.486105,-0.0023343) , 
10, 0.30405, 1, 0, 0.5,0.000757912)    );
  // itree = 37
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.473999,-0.023925) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.526808,0.0111246) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.465221,-0.0173726) , 
8, -2.37667, 1, 0, 0.498293,-0.00214286) , 
0, 43.4125, 1, 0, 0.490007,-0.0116871) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.442956,0.0122481) , 
5, 84.3079, 1, 0, 0.47615,-0.00401243) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.543449,0.0220362) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.576329,0.0101774) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.489074,-0.00285908) , 
8, 0.120858, 1, 0, 0.523675,0.002815) , 
6, 50.2358, 1, 0, 0.525962,0.0057111) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.534491,-0.022139) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.479643,-0.00141331) , 
8, 0.696583, 1, 0, 0.501423,-0.0118565) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.380445,0.0123124) , 
5, 149.613, 1, 0, 0.46802,-0.0049898) , 
7, 2.72312, 1, 0, 0.507888,0.00237307) , 
8, -1.31734, 1, 0, 0.5,0.000786045)    );
  // itree = 38
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.606271,0.0134216) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.549525,-0.00594679) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.486291,0.00148629) , 
1, 39.168, 1, 0, 0.50747,-0.00133524) , 
0, 33.5659, 1, 0, 0.516562,0.000359457) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.467096,0.0143521) , 
0, 140.536, 1, 0, 0.513664,0.00135524) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.354246,-0.00827499) , 
1, 134.434, 1, 0, 0.5,0.000562956)    );
  // itree = 39
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.52167,0.0116387) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.484137,-0.00403046) , 
6, 31.328, 1, 0, 0.493914,0.000287925) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.523401,0.00220719) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.606201,0.0249126) , 
9, -1.92431, 1, 0, 0.574395,0.020149) , 
8, -0.264763, 1, 0, 0.525723,0.00813778) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.433302,-0.0190547) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.503643,0.00101335) , 
0, 54.8466, 1, 0, 0.463615,-0.0123081) , 
8, 1.31756, 1, 0, 0.509712,0.00286696) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.592493,-0.00596919) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.499076,0.0102144) , 
3, 366.05, 1, 0, 0.550349,0.00125985) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.401282,-0.0252201) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.487798,0.00664348) , 
2, 92.6698, 1, 0, 0.43797,-0.0121229) , 
7, 1.8106, 1, 0, 0.49918,-0.00483372) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.435627,0.00172185) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.480276,0.0150425) , 
7, 1.88152, 1, 0, 0.457828,0.0104638) , 
8, 1.51969, 1, 0, 0.491119,-0.00185163) , 
6, 74.2224, 1, 0, 0.5,0.000402279)    );
  // itree = 40
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.580454,0.00372659) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.481198,-0.00522071) , 
8, 0.912126, 1, 0, 0.547869,0.00104853) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.5415,0.0176235) , 
0, 104.14, 1, 0, 0.547182,0.0034312) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.392775,-0.0187116) , 
1, 115.75, 1, 0, 0.536115,0.00177347) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.448814,0.0134884) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.300859,-0.00462146) , 
7, 2.13769, 1, 0, 0.376525,0.00529445) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.322738,-0.023102) , 
0, 96.3259, 1, 0, 0.357006,-0.00476012) , 
4, 616.701, 1, 0, 0.5,0.000456057)    );
  // itree = 41
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.478201,0.00624469) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.427654,-0.0282476) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.531575,0.00774008) , 
7, 2.12774, 1, 0, 0.493524,-0.00585939) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.580457,0.0103296) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.514312,-0.00536112) , 
7, 2.55653, 1, 0, 0.556612,0.00587314) , 
8, -1.52005, 1, 0, 0.539499,0.0026907) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.446322,-0.00467521) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.423459,-0.0259591) , 
9, 0.467066, 1, 0, 0.441062,-0.0103485) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.399012,0.00811635) , 
9, 1.72261, 1, 0, 0.430639,-0.00561677) , 
5, 118.991, 1, 0, 0.502129,-0.000161186) , 
10, -2.53343, 1, 0, 0.5,0.000540421)    );
  // itree = 42
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.490662,-0.0106512) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.552013,0.0062921) , 
9, -2.61183, 1, 0, 0.546239,0.00602432) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.36678,0.00185975) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.403272,-0.019005) , 
6, 64.9986, 1, 0, 0.385439,-0.00879514) , 
1, 99.7669, 1, 0, 0.519846,0.00359195) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.431701,0.0104327) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.457185,-0.0236743) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.493336,-0.00165461) , 
10, -0.165483, 1, 0, 0.482062,-0.00989803) , 
10, -1.31748, 1, 0, 0.469773,-0.00452389) , 
6, 111.25, 1, 0, 0.507435,0.00158037) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.475168,-0.0150721) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.414675,0.00941062) , 
5, 119.531, 1, 0, 0.450586,-0.00646149) , 
9, 2.33061, 1, 0, 0.5,0.000528629)    );
  // itree = 43
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.478697,-0.0103666) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.557299,-0.000399673) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.381597,0.0162446) , 
3, 347.148, 1, 0, 0.507377,0.00412376) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.628689,0.00524729) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.464422,-0.0116364) , 
3, 312.577, 1, 0, 0.52793,-0.00583064) , 
2, 72.8095, 1, 0, 0.513855,0.000986447) , 
5, 33.7378, 1, 0, 0.510593,-0.00031517) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.372005,0.00961205) , 
5, 208.075, 1, 0, 0.5,0.000449128)    );
  // itree = 44
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.45634,-0.00823397) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.656888,0.0185416) , 
2, 40.099, 1, 0, 0.559033,0.00747715) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.497758,0.000659356) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.438049,-0.015203) , 
7, 3.10888, 1, 0, 0.48688,-0.00249252) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.294634,-0.0242802) , 
1, 99.7669, 1, 0, 0.455602,-0.00554943) , 
7, 1.56383, 1, 0, 0.482477,-0.00216465) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.550164,0.00267787) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.53183,-0.0155241) , 
10, 0.310309, 1, 0, 0.545208,-0.00281108) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.53647,0.00976752) , 
10, 1.72279, 1, 0, 0.543063,0.00102914) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.440657,0.0162333) , 
5, 178.381, 1, 0, 0.526847,0.00388024) , 
2, 64.7817, 1, 0, 0.5,0.00022269)    );
  // itree = 45
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.527505,0.0122173) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.459343,-0.00899444) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.564318,0.00630041) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.496521,-0.000617106) , 
5, 85.9136, 1, 0, 0.522752,0.00268059) , 
8, -1.61801, 1, 0, 0.515307,0.00108148) , 
8, -2.53336, 1, 0, 0.516354,0.00233438) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.517015,-0.0130583) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.490896,-0.00179385) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.562434,0.0123088) , 
2, 81.845, 1, 0, 0.507752,0.00229864) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.305596,-0.0111981) , 
3, 426.8, 1, 0, 0.462686,-0.000478958) , 
9, 1.10155, 1, 0, 0.471824,-0.00303759) , 
9, 0.709277, 1, 0, 0.5,0.000361466)    );
  // itree = 46
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.557668,0.0114793) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.336671,-0.00420364) , 
3, 353.541, 1, 0, 0.484509,0.00865694) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.467111,-0.0112235) , 
8, 1.3175, 1, 0, 0.481717,0.0050263) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.586304,0.00386984) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.497397,-0.0064171) , 
5, 78.9689, 1, 0, 0.524143,-0.00368144) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.491519,0.0112338) , 
8, 2.12814, 1, 0, 0.519382,-0.00108741) , 
10, -0.709336, 1, 0, 0.505777,0.00112088) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.448178,-0.00563187) , 
9, 2.53327, 1, 0, 0.5,0.000351219)    );
  // itree = 47
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.588112,0.0055996) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.6176,-0.00622435) , 
10, -0.709103, 1, 0, 0.605993,-0.00198252) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.609629,0.0152209) , 
0, 82.4836, 1, 0, 0.606499,0.00123258) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.509182,-0.0209798) , 
4, 400.228, 1, 0, 0.593356,-0.00249863) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.327188,-0.00630753) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.513566,0.0141477) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.362641,0.00118764) , 
8, 0.304073, 1, 0, 0.445625,0.00983895) , 
10, -1.31748, 1, 0, 0.418576,0.00619207) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.400777,-0.0139427) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.364528,0.0128284) , 
5, 199.566, 1, 0, 0.387708,-0.00514786) , 
0, 96.3237, 1, 0, 0.410092,0.00307518) , 
4, 427.67, 1, 0, 0.5,0.000340699)    );
  // itree = 48
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.674816,0.0114218) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.620372,-0.0236349) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.643978,0.00136445) , 
7, 2.05628, 1, 0, 0.634838,-0.010657) , 
4, 259.978, 1, 0, 0.645333,-0.00377295) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.46539,0.0216481) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.494585,0.00515562) , 
6, 64.6064, 1, 0, 0.488994,0.00954391) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.463083,-0.000383838) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.421327,-0.0135283) , 
5, 131.933, 1, 0, 0.442429,-0.00776714) , 
6, 134.657, 1, 0, 0.47635,0.00484352) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.464913,-0.0117636) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.389798,0.00206743) , 
1, 80.9974, 1, 0, 0.434715,-0.00763054) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.482349,0.0126032) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.31446,-0.0037544) , 
3, 359.085, 1, 0, 0.411546,0.00775556) , 
8, 0.709394, 1, 0, 0.426622,-0.00225592) , 
7, 2.38995, 1, 0, 0.453505,0.00158209) , 
4, 333.155, 1, 0, 0.5,0.000284147)    );
  // itree = 49
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.45634,-0.00477238) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.656888,0.0137334) , 
2, 40.099, 1, 0, 0.559033,0.00616963) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.601408,0.000202018) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.505995,-0.0171017) , 
3, 212.889, 1, 0, 0.556996,-0.00989207) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.275234,0.0130108) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.398724,-0.0111462) , 
2, 46.8207, 1, 0, 0.313255,0.00330328) , 
4, 426.632, 1, 0, 0.455602,-0.00440291) , 
7, 1.56383, 1, 0, 0.482477,-0.00165578) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.55847,-0.0112193) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.478719,0.00647826) , 
3, 396.191, 1, 0, 0.520671,-0.00400893) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.554971,0.0196885) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.524359,0.00279773) , 
8, -0.709366, 1, 0, 0.535453,0.0119821) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.511537,-0.00871765) , 
9, 2.12798, 1, 0, 0.53037,0.0070905) , 
7, 1.97243, 1, 0, 0.526847,0.00305828) , 
2, 64.7817, 1, 0, 0.5,0.000205971)    );
   return;
};
 
// Clean up
inline void ReadBDT::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDT::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
