// Class: ReadBDT
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.10/04       [395780]
Creator        : marine5575
Date           : Wed Oct  9 17:30:03 2019
Host           : Linux htop.hanyang.ac.kr 2.6.32-696.el6.centos.plus.x86_64 #1 SMP Mon Apr 3 14:56:08 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/marine5575/work/Undergrad2018/mva
Training events: 65134
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "50" [Number of trees in the forest]
MaxDepth: "4" [Max depth of the decision tree allowed]
MinNodeSize: "5%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
nCuts: "30" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "Grad" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
Shrinkage: "5.000000e-01" [Learning rate for GradBoost algorithm]
SeparationType: "giniindex" [Separation criterion for node splitting]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
UseBaggedBoost: "False" [Use only a random subsample of all events for growing the trees in each boost iteration.]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "3" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Poisson distribution in each split with RandomisedTree option]
BaggedSampleFraction: "6.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "pray" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in training sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
RegressionLossFunctionBDTG: "huber" [Loss function for BDTG regression.]
HuberQuantile: "7.000000e-01" [In the Huber loss function this is the quantile that separates the core from the tails in the residuals distribution.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
SkipNormalization: "False" [Skip normalization at initialization, to keep expectation value of BDT output according to the fraction of events]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "6.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 11
lepton1_pt                    lepton1_pt                    lepton1_pt                    lepton1_pt                                                      'F'    [30.0022735596,875.963500977]
met_pt                        met_pt                        met_pt                        met_pt                                                          'F'    [0.174064293504,815.994018555]
tau1_pt                       tau1_pt                       tau1_pt                       tau1_pt                                                         'F'    [30.0001525879,1040.04150391]
jet_ht                        jet_ht                        jet_ht                        jet_ht                                                          'F'    [95.0174484253,3019.39990234]
jetlepmet_ht                  jetlepmet_ht                  jetlepmet_ht                  jetlepmet_ht                                                    'F'    [155.10949707,3288.48583984]
lep1met_pt                    lep1met_pt                    lep1met_pt                    lep1met_pt                                                      'F'    [0.211814135313,879.103881836]
lep1tau1_pt                   lep1tau1_pt                   lep1tau1_pt                   lep1tau1_pt                                                     'F'    [0.17061945796,1256.81884766]
tau1_lep1_dr                  tau1_lep1_dr                  tau1_lep1_dr                  tau1_lep1_dr                                                    'F'    [0.390903234482,5.5550994873]
lep1_met_dphi                 lep1_met_dphi                 lep1_met_dphi                 lep1_met_dphi                                                   'F'    [-3.14144611359,3.14149641991]
tau1_met_dphi                 tau1_met_dphi                 tau1_met_dphi                 tau1_met_dphi                                                   'F'    [-3.14148163795,3.14157342911]
tau1lep1_met_dphi             tau1lep1_met_dphi             tau1lep1_met_dphi             tau1lep1_met_dphi                                               'F'    [-3.14146351814,3.14153146744]
NSpec 2
njet                          njet                          njet                          njet                                                            'F'    [3,12]
nbjet                         nbjet                         nbjet                         nbjet                                                           'F'    [0,6]


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDTNode
   
#ifndef BDTNode__def
#define BDTNode__def
   
class BDTNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDTNode ( BDTNode* left,BDTNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDTNode();

   // test event if it descends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDTNode* GetRight( void )  {return fRight; };

   // test event if it descends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDTNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDTNode*   fLeft;     // pointer to the left daughter node
   BDTNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value applied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDTNode::~BDTNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDTNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDTNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT : public IClassifierReader {

 public:

   // constructor
   ReadBDT( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDT" ),
        fNvars( 11 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "lepton1_pt", "met_pt", "tau1_pt", "jet_ht", "jetlepmet_ht", "lep1met_pt", "lep1tau1_pt", "tau1_lep1_dr", "lep1_met_dphi", "tau1_met_dphi", "tau1lep1_met_dphi" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;
      fVmin[8] = 0;
      fVmax[8] = 0;
      fVmin[9] = 0;
      fVmax[9] = 0;
      fVmin[10] = 0;
      fVmax[10] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[11];
   double fVmax[11];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[11];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDTNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDTNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDTNode*)current->GetRight();
         else current=(BDTNode*)current->GetLeft();
      }
      myMVA += current->GetResponse();
   }
   return 2.0/(1.0+exp(-2.0*myMVA))-1.0;
};

void ReadBDT::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.80759,0.266708) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.757045,0.226687) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.571162,0.0669628) , 
4, 406.629, 1, 0, 0.692225,0.192225) , 
7, 1.64752, 1, 0, 0.735261,0.235261) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.672837,0.156888) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.574243,0.0697846) , 
1, 39.0039, 1, 0, 0.620991,0.120991) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.513851,0.0133088) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.343668,-0.160251) , 
4, 459.132, 1, 0, 0.458122,-0.0418775) , 
7, 1.89019, 1, 0, 0.529438,0.0294377) , 
1, 29.0361, 1, 0, 0.63626,0.13626) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.51555,0.0149317) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.392431,-0.108193) , 
1, 77.4313, 1, 0, 0.446695,-0.0533048) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.417009,-0.0826894) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.282067,-0.228935) , 
3, 284.505, 1, 0, 0.350554,-0.149446) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.224293,-0.296519) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.128724,-0.415672) , 
5, 163.589, 1, 0, 0.17793,-0.32207) , 
5, 114.242, 1, 0, 0.263719,-0.236281) , 
7, 1.55733, 1, 0, 0.31414,-0.18586) , 
1, 52.8076, 1, 0, 0.5,-1.547e-15)    );
  // itree = 1
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.762573,0.136776) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.843714,0.206334) , 
2, 49.4117, 1, 0, 0.805009,0.189106) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.692025,0.105912) , 
4, 415.565, 1, 0, 0.763554,0.161295) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.547268,-0.00822001) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.389874,-0.112814) , 
1, 37.0229, 1, 0, 0.473974,-0.0562255) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.69521,0.144108) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.482868,-0.0489487) , 
9, 0.918778, 1, 0, 0.603932,0.0681485) , 
9, -0.911819, 1, 0, 0.565678,0.0315384) , 
1, 22.245, 1, 0, 0.63626,0.0778222) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.471916,0.0102551) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.332875,-0.100381) , 
5, 131.565, 1, 0, 0.416758,-0.0310644) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.27894,-0.143918) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.382444,-0.0273571) , 
2, 43.3827, 1, 0, 0.337295,-0.0717304) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.147314,-0.245296) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.193997,-0.1824) , 
2, 61.5136, 1, 0, 0.170955,-0.174316) , 
4, 477.833, 1, 0, 0.251135,-0.124868) , 
7, 1.88839, 1, 0, 0.31414,-0.0891839) , 
1, 52.8076, 1, 0, 0.5,0.00717717)    );
  // itree = 2
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.758324,0.0915777) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.806876,0.13656) , 
9, -0.506808, 1, 0, 0.788372,0.12008) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.680792,0.0376001) , 
7, 2.27061, 1, 0, 0.74603,0.0875749) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.48302,0.0152222) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.351003,-0.0905427) , 
10, -1.92539, 1, 0, 0.399839,-0.046474) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.646908,0.138195) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.424644,-0.0352727) , 
9, 0.408759, 1, 0, 0.517628,0.0398698) , 
9, -0.709331, 1, 0, 0.479127,0.0116475) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.4812,0.0126422) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.305837,-0.0883378) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.164075,-0.176051) , 
3, 413.594, 1, 0, 0.261985,-0.0926727) , 
5, 57.2313, 1, 0, 0.318165,-0.0657437) , 
7, 2.38995, 1, 0, 0.411658,-0.0207918) , 
1, 26.4908, 1, 0, 0.5,0.00783892)    );
  // itree = 3
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.709666,0.073732) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.584831,-0.00694287) , 
4, 531.754, 1, 0, 0.685508,0.0567694) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.469308,0.0239971) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.341046,-0.0627207) , 
9, 0.709844, 1, 0, 0.42527,-0.00431823) , 
1, 43.4691, 1, 0, 0.590615,0.0344946) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.362689,-0.115212) , 
7, 3.22288, 1, 0, 0.573842,0.0244468) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.397958,0.0253224) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.286793,-0.0592495) , 
5, 97.2606, 1, 0, 0.336936,-0.0162941) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.155394,-0.160419) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.217753,-0.0839471) , 
2, 62.5836, 1, 0, 0.184087,-0.0855361) , 
5, 142.937, 1, 0, 0.260466,-0.0509358) , 
1, 79.1244, 1, 0, 0.5,0.00668416)    );
  // itree = 4
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.673153,0.0872358) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.366148,-0.123652) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.465035,-0.0598277) , 
9, -0.912095, 1, 0, 0.432386,-0.0705889) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.663003,0.0736612) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.445961,0.0141622) , 
5, 93.2772, 1, 0, 0.598432,0.053438) , 
2, 39.8274, 1, 0, 0.543354,0.0122977) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.204491,-0.179728) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.350379,-0.0124743) , 
2, 39.1467, 1, 0, 0.270122,-0.0735974) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.490013,0.011863) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.231024,-0.0737964) , 
7, 2.16897, 1, 0, 0.348159,-0.0228183) , 
2, 61.5136, 1, 0, 0.311505,-0.0466695) , 
4, 541.808, 1, 0, 0.48124,-0.00349984) , 
7, 0.890664, 1, 0, 0.5,0.00510994)    );
  // itree = 5
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.613863,-0.0174101) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.69372,0.0380407) , 
9, -1.61155, 1, 0, 0.65156,0.00817847) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.283563,-0.132655) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.297569,-0.0455558) , 
8, -0.100578, 1, 0, 0.291476,-0.0689798) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.301832,-0.0160189) , 
0, 62.2058, 1, 0, 0.296226,-0.0428947) , 
1, 39.6686, 1, 0, 0.45067,-0.020696) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.759738,0.127256) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.733073,0.0909886) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.510534,0.029562) , 
4, 385.721, 1, 0, 0.606925,0.0519977) , 
7, 1.17848, 1, 0, 0.642182,0.0679242) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.632857,-0.000831306) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.265883,-0.060441) , 
1, 41.675, 1, 0, 0.431181,-0.0254182) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.520971,0.0252053) , 
10, 2.33091, 1, 0, 0.449676,-0.0155472) , 
9, 0.670224, 1, 0, 0.53071,0.0195895) , 
9, -0.506652, 1, 0, 0.5,0.00413259)    );
  // itree = 6
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.42748,-0.0378185) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.327477,-0.0963594) , 
9, 1.52019, 1, 0, 0.403601,-0.0419568) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.530469,0.0202465) , 
2, 38.9788, 1, 0, 0.429063,-0.0300116) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.734241,0.091597) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.619623,0.0429042) , 
7, 0.968446, 1, 0, 0.642695,0.0474011) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.649065,0.0486881) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.373906,-0.0138042) , 
4, 354.069, 1, 0, 0.46183,0.00681592) , 
7, 2.38025, 1, 0, 0.570818,0.0312723) , 
2, 42.6532, 1, 0, 0.519391,0.00903928) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.495499,-0.0233924) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.185297,-0.105626) , 
7, 1.9409, 1, 0, 0.342144,-0.0422629) , 
3, 566.692, 1, 0, 0.5,0.00342671)    );
  // itree = 7
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.767068,0.0369373) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.475565,0.0144578) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.397326,-0.0304044) , 
10, -2.33066, 1, 0, 0.411206,-0.0179522) , 
1, 19.9213, 1, 0, 0.476804,-0.00888469) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.772867,0.0978107) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.616902,0.0550953) , 
7, 1.65314, 1, 0, 0.684874,0.0653756) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.561364,0.0187136) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.440989,-0.0131369) , 
3, 277.632, 1, 0, 0.490937,0.000715451) , 
9, 0.251764, 1, 0, 0.537954,0.0163911) , 
9, -0.303973, 1, 0, 0.512099,0.00570422) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.277381,-0.0739226) , 
7, 3.38947, 1, 0, 0.5,0.0026416)    );
  // itree = 8
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.794924,0.0527326) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.405244,-0.024738) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.522379,0.00481844) , 
9, -1.31737, 1, 0, 0.492918,-0.0020384) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.512269,0.053129) , 
0, 123.874, 1, 0, 0.494134,0.000947808) , 
1, 13.0762, 1, 0, 0.521429,0.00474195) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.217801,-0.0593968) , 
5, 198.671, 1, 0, 0.5,0.00203858)    );
  // itree = 9
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.490789,0.0103003) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.534568,-0.0279106) , 
6, 61.8504, 1, 0, 0.511548,-0.00694301) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.760772,0.0617398) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.678626,0.0255423) , 
5, 51.7206, 1, 0, 0.713242,0.0345278) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.628357,0.010222) , 
9, 1.11483, 1, 0, 0.688714,0.0271662) , 
2, 39.7059, 1, 0, 0.624388,0.0147818) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.448986,-0.067008) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.361507,-0.0100959) , 
7, 1.73105, 1, 0, 0.376865,-0.0163171) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.656393,0.0273938) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.443709,-0.0146886) , 
7, 1.28498, 1, 0, 0.534847,0.00367411) , 
6, 95.7195, 1, 0, 0.446542,-0.0075001) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.434982,0.0333118) , 
0, 139.159, 1, 0, 0.445469,-0.00446353) , 
4, 357.263, 1, 0, 0.5,0.00140208)    );
  // itree = 10
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.406757,0.0236335) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.423231,-0.030273) , 
6, 36.9155, 1, 0, 0.420061,-0.016074) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.589693,0.020555) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.503411,-0.00653733) , 
2, 91.6347, 1, 0, 0.56474,0.0106654) , 
2, 42.6532, 1, 0, 0.512931,0.00109002) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.274528,-0.0548453) , 
4, 862.646, 1, 0, 0.498742,-0.00108257) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.518465,0.0376045) , 
10, 2.73618, 1, 0, 0.5,0.00107263)    );
  // itree = 11
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.560142,0.0117876) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.441363,-0.0138519) , 
3, 283.687, 1, 0, 0.492412,-0.0018588) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.692156,0.0473967) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.492949,-0.00634416) , 
5, 105.918, 1, 0, 0.628081,0.0257538) , 
9, -0.264964, 1, 0, 0.549577,0.00977611) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.440673,-0.0448696) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.5872,-0.0107439) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.290361,0.0396338) , 
1, 53.3799, 1, 0, 0.464709,0.00531004) , 
0, 52.1094, 1, 0, 0.454928,-0.012008) , 
9, 1.31746, 1, 0, 0.525342,0.00419826) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.358988,-0.0483118) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.334492,-0.0141699) , 
8, -0.709214, 1, 0, 0.343863,-0.0204784) , 
7, 3.05629, 1, 0, 0.5,0.000752333)    );
  // itree = 12
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.690054,0.0368187) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.464136,0.0380328) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.459035,0.00536822) , 
6, 21.745, 1, 0, 0.461683,0.0177947) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.584578,0.00698979) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.279439,-0.0503892) , 
5, 158.329, 1, 0, 0.547456,0.0012557) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.377046,-0.036562) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.345431,0.0241269) , 
2, 92.6658, 1, 0, 0.368035,-0.014739) , 
7, 2.49294, 1, 0, 0.492248,-0.00366585) , 
6, 32.0202, 1, 0, 0.488669,-0.00115321) , 
7, 0.724077, 1, 0, 0.5,0.000691886)    );
  // itree = 13
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.458932,-0.0462414) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.52588,-0.00356153) , 
9, -0.709268, 1, 0, 0.505981,-0.0134041) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.511288,0.0313222) , 
0, 87.5352, 1, 0, 0.507156,-0.00473256) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.753269,0.0705585) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.592649,0.0494125) , 
5, 84.9603, 1, 0, 0.676844,0.0504379) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.449161,-0.0323447) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.205541,0.0324158) , 
7, 1.88886, 1, 0, 0.308045,-0.00134308) , 
5, 114.05, 1, 0, 0.460773,0.0201007) , 
8, -0.657051, 1, 0, 0.488357,0.0053325) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.566112,-0.000352246) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.414777,-0.0393328) , 
7, 2.89572, 1, 0, 0.530661,-0.00761171) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.462945,-0.0723035) , 
9, 1.5201, 1, 0, 0.517596,-0.0180924) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.535676,0.027074) , 
0, 84.5827, 1, 0, 0.521846,-0.00843464) , 
8, 0.912065, 1, 0, 0.5,0.0005461)    );
  // itree = 14
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.56586,0.0224231) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.798439,0.033617) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.719344,-0.0285072) , 
0, 72.7108, 1, 0, 0.769775,0.00798054) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.438266,-0.000970665) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.411555,-0.0190235) , 
10, 0.650499, 1, 0, 0.429162,-0.00574741) , 
1, 20.8501, 1, 0, 0.492545,-0.00319287) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.505564,0.0318099) , 
10, 2.73618, 1, 0, 0.493264,-0.00150249) , 
8, -2.53342, 1, 0, 0.5,0.000495876)    );
  // itree = 15
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.562313,-0.0702707) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.506125,-0.00684579) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.602919,0.027421) , 
2, 61.5148, 1, 0, 0.549507,0.00738325) , 
7, 1.10697, 1, 0, 0.552686,-0.00861421) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.663645,0.0244931) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.699601,0.0722491) , 
0, 93.2903, 1, 0, 0.677677,0.0374602) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.636945,0.0141962) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.360608,-0.0312858) , 
5, 106.248, 1, 0, 0.529433,-0.00141119) , 
7, 1.27757, 1, 0, 0.592993,0.015255) , 
0, 51.5594, 1, 0, 0.577265,0.00594129) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.663264,0.040607) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.356235,0.00437605) , 
5, 62.3411, 1, 0, 0.504543,0.0189164) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.519531,0.0182915) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.331061,-0.0321795) , 
3, 255.177, 1, 0, 0.410349,-0.00669624) , 
7, 2.86827, 1, 0, 0.453841,0.00512993) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.494217,-0.0507274) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.236163,-0.00214723) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.198313,0.0160622) , 
7, 2.77576, 1, 0, 0.217568,0.00348109) , 
1, 51.338, 1, 0, 0.354138,-0.0201918) , 
6, 58.934, 1, 0, 0.409992,-0.0060066) , 
7, 2.22336, 1, 0, 0.5,0.000422445)    );
  // itree = 16
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.444975,-0.0155277) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.487429,0.0219916) , 
0, 70.2469, 1, 0, 0.459872,-0.0018562) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.326551,-0.0411319) , 
3, 314.114, 1, 0, 0.41913,-0.0102826) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.695942,0.0447725) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.551554,0.0100251) , 
7, 1.89004, 1, 0, 0.612533,0.0203369) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.599063,-0.00191723) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.396181,0.027688) , 
4, 539.926, 1, 0, 0.567405,0.00182534) , 
2, 60.0772, 1, 0, 0.585706,0.00933251) , 
2, 40.2457, 1, 0, 0.530677,0.00285255) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.517103,-0.00151094) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.21271,-0.030832) , 
7, 1.97243, 1, 0, 0.368006,-0.00922427) , 
3, 472.357, 1, 0, 0.5,0.000575075)    );
  // itree = 17
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.538854,-0.0115239) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.593724,0.0336372) , 
0, 58.5229, 1, 0, 0.566962,0.0105345) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.453998,-0.0445809) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.575364,0.00215784) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.390641,-0.0267905) , 
9, 1.3566, 1, 0, 0.50575,-0.00685999) , 
9, -1.1141, 1, 0, 0.493832,-0.0136616) , 
8, -2.42227, 1, 0, 0.517234,-0.00591884) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.530433,0.0644951) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.548645,0.0198136) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.16602,-0.0498524) , 
1, 83.5877, 1, 0, 0.428432,0.00269905) , 
0, 47.5716, 1, 0, 0.456966,0.0153288) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.685233,0.0323595) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.46492,-0.00526221) , 
7, 1.73348, 1, 0, 0.518834,0.00346302) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.396398,-0.0613371) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.56765,0.00625234) , 
8, 1.62324, 1, 0, 0.48827,-0.018899) , 
9, 0.912066, 1, 0, 0.510459,-0.00266405) , 
8, 0.526364, 1, 0, 0.490934,0.00390353) , 
8, -0.912015, 1, 0, 0.5,0.000517531)    );
  // itree = 18
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.765599,0.0311445) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.371256,-0.0207968) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.398755,0.00919704) , 
10, -1.31726, 1, 0, 0.390944,0.000400729) , 
1, 21.0041, 1, 0, 0.458413,0.00486072) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.536733,0.0226528) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.481741,-0.0187517) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.561009,-0.000268592) , 
9, -0.303998, 1, 0, 0.529619,-0.00594985) , 
10, -2.53343, 1, 0, 0.530268,-0.00361622) , 
6, 63.8699, 1, 0, 0.504406,-0.000565217) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.436984,0.0219252) , 
0, 139.159, 1, 0, 0.5,0.000529404)    );
  // itree = 19
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.690054,0.0216137) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.384009,-0.0126402) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.569542,0.00643044) , 
2, 40.3285, 1, 0, 0.49607,-0.000646505) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.49146,-0.0210411) , 
2, 94.0425, 1, 0, 0.495591,-0.00233595) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.422487,0.0202185) , 
2, 124.54, 1, 0, 0.488669,-0.000678568) , 
7, 0.724077, 1, 0, 0.5,0.000354482)    );
  // itree = 20
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.459152,0.0215839) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.51625,-0.000858501) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.308651,-0.0251378) , 
7, 2.87025, 1, 0, 0.48335,-0.00330322) , 
6, 32.0202, 1, 0, 0.480623,-0.00104091) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.759351,0.0443012) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.587683,0.00975715) , 
7, 1.94136, 1, 0, 0.678351,0.0217463) , 
9, -0.140582, 1, 0, 0.519085,0.00339156) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.641665,0.0210313) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.564651,-0.0128842) , 
10, 1.11504, 1, 0, 0.594276,-0.000296998) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.371818,-0.00775051) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.404927,-0.0344877) , 
2, 62.5821, 1, 0, 0.384588,-0.0134915) , 
5, 80.0391, 1, 0, 0.489544,-0.00688723) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.424108,0.00769953) , 
9, 2.50085, 1, 0, 0.474413,-0.00393869) , 
9, 0.304065, 1, 0, 0.5,0.00025993)    );
  // itree = 21
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.79972,0.0245881) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.763043,0.00599414) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.705804,-0.0292504) , 
0, 58.1154, 1, 0, 0.73259,-0.0101897) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.43096,-0.00805542) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.432522,0.011843) , 
0, 56.3678, 1, 0, 0.431767,0.00166253) , 
1, 25.0535, 1, 0, 0.486788,-0.000505275) , 
1, 12.8175, 1, 0, 0.513904,0.00107553) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.276558,-0.0203304) , 
4, 862.646, 1, 0, 0.5,0.000292037)    );
  // itree = 22
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.424647,-0.0152206) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.533911,0.0215471) , 
0, 58.5229, 1, 0, 0.486269,0.00507949) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.690989,0.0158062) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.535548,-0.0104512) , 
7, 1.96621, 1, 0, 0.600027,0.000152096) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.390607,-0.0475361) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.248339,-0.0124354) , 
9, 0.303787, 1, 0, 0.320327,-0.0206881) , 
5, 108.366, 1, 0, 0.505371,-0.00690065) , 
10, -1.72202, 1, 0, 0.499152,-0.00299999) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.479062,0.034542) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.480333,-0.0213015) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.624217,0.0145902) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.428174,-0.00947785) , 
5, 71.5901, 1, 0, 0.508255,0.000861825) , 
10, -1.72272, 1, 0, 0.504941,-0.00133625) , 
8, 0.251757, 1, 0, 0.500689,0.002805) , 
8, -0.303988, 1, 0, 0.5,0.000203846)    );
  // itree = 23
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.671786,-0.0302698) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.751849,0.00364222) , 
9, -1.72268, 1, 0, 0.736771,-0.00250297) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.609553,0.0265545) , 
1, 28.6517, 1, 0, 0.711242,0.00282412) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.502978,-0.0316863) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.432916,-0.022578) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.556859,0.00827337) , 
2, 46.8568, 1, 0, 0.505001,-0.00372693) , 
5, 56.2462, 1, 0, 0.504308,-0.012486) , 
1, 34.1294, 1, 0, 0.63626,-0.00272348) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.455958,-0.015047) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.356098,0.0461153) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.352376,0.0153276) , 
8, 0.303348, 1, 0, 0.354399,0.0246522) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.332878,-0.0192687) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.16982,0.0256943) , 
5, 115.045, 1, 0, 0.230453,0.00165361) , 
1, 71.7905, 1, 0, 0.272682,0.00948927) , 
7, 1.3918, 1, 0, 0.31414,0.0042837) , 
1, 52.8076, 1, 0, 0.5,0.000240616)    );
  // itree = 24
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.564903,0.00695362) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.404912,-0.0106659) , 
7, 2.8951, 1, 0, 0.532948,0.00297115) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.255601,-0.0151891) , 
5, 141.969, 1, 0, 0.480623,0.000785573) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.759351,0.0291143) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.587683,0.00488358) , 
7, 1.94136, 1, 0, 0.678351,0.0132584) , 
9, -0.140582, 1, 0, 0.519085,0.00321173) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.495941,-0.0210986) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.442212,0.00878148) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.525366,-0.0213557) , 
8, 1.0364, 1, 0, 0.476789,-0.00372726) , 
8, -1.52004, 1, 0, 0.481956,-0.00753892) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.483153,-0.00614789) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.422825,0.02097) , 
9, 1.67686, 1, 0, 0.4527,0.00526148) , 
0, 84.5804, 1, 0, 0.474413,-0.00423863) , 
9, 0.304065, 1, 0, 0.5,2.87867e-05)    );
  // itree = 25
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.569431,0.00893616) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.566037,-0.00735415) , 
8, -2.68095, 1, 0, 0.56771,0.000719337) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.741624,0.0291682) , 
8, -2.04298, 1, 0, 0.63363,0.00892191) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.44297,0.0201518) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.416821,-0.00392444) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.518192,-0.0252691) , 
6, 121.782, 1, 0, 0.445426,-0.00731744) , 
10, -2.12738, 1, 0, 0.445134,-0.00457323) , 
5, 56.9145, 1, 0, 0.485608,-0.00167554) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.548115,-0.0146293) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.513915,-0.00613176) , 
7, 2.22336, 1, 0, 0.531209,-0.00891261) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.660814,0.0461632) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.479895,0.00160345) , 
7, 2.2515, 1, 0, 0.573516,0.0218949) , 
0, 57.2937, 1, 0, 0.552525,0.00660962) , 
8, 1.72277, 1, 0, 0.5,0.000106337)    );
  // itree = 26
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.690054,0.0166952) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.453398,0.0141965) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.48009,-0.0110853) , 
2, 57.4341, 1, 0, 0.461361,0.00506188) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.556658,-0.00106931) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.334101,-0.0277665) , 
7, 2.47816, 1, 0, 0.510643,-0.00477314) , 
6, 54.8606, 1, 0, 0.495591,-0.00176922) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.422487,0.0139638) , 
2, 124.54, 1, 0, 0.488669,-0.000612053) , 
7, 0.724077, 1, 0, 0.5,0.000173043)    );
  // itree = 27
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.510868,0.0170605) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.488927,0.00721423) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.548976,-0.00445627) , 
6, 67.5572, 1, 0, 0.529635,-0.000574897) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.326155,-0.0282007) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.355821,-0.00137101) , 
10, -0.101177, 1, 0, 0.341354,-0.0102124) , 
7, 3.05629, 1, 0, 0.503888,-0.00189279) , 
0, 33.5233, 1, 0, 0.504406,-0.000740697) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.436984,0.0173385) , 
0, 139.159, 1, 0, 0.5,0.000139069)    );
  // itree = 28
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.61436,-0.00850815) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.480258,0.00998541) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.389898,-0.0129102) , 
0, 78.3056, 1, 0, 0.45378,0.00268424) , 
7, 1.23226, 1, 0, 0.48451,0.000838474) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.68638,0.0203102) , 
9, -0.107923, 1, 0, 0.505846,0.00242504) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.633607,0.0103471) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.559695,-0.017661) , 
9, 1.86639, 1, 0, 0.608165,0.000311614) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.384109,-0.00181506) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.426657,-0.0267048) , 
8, 0.30254, 1, 0, 0.400297,-0.00849558) , 
5, 72.802, 1, 0, 0.499737,-0.00428239) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.450438,0.0132679) , 
0, 111.869, 1, 0, 0.49353,-0.00250925) , 
9, 0.101385, 1, 0, 0.5,8.28156e-05)    );
  // itree = 29
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.616584,0.00338825) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.425881,-0.0127774) , 
5, 65.1043, 1, 0, 0.521011,-0.00333804) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.406999,-0.025663) , 
9, 2.12819, 1, 0, 0.502683,-0.00603814) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.564491,0.0236395) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.406258,-0.00991142) , 
8, -1.494, 1, 0, 0.487678,0.00709255) , 
0, 87.5352, 1, 0, 0.499152,-0.00294792) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.79346,0.0169401) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.707086,-0.026053) , 
1, 16.3023, 1, 0, 0.748584,-0.0048433) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.504358,-0.00735253) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.371649,0.00291347) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.447882,0.044307) , 
8, 1.80767, 1, 0, 0.385737,0.00862012) , 
5, 57.4949, 1, 0, 0.411874,0.00523274) , 
1, 26.4908, 1, 0, 0.500689,0.00257495) , 
8, -0.303988, 1, 0, 0.5,0.000100213)    );
  // itree = 30
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.534489,-0.0245926) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.572652,0.00719927) , 
0, 47.1287, 1, 0, 0.553666,-0.00676933) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.748984,0.0659789) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.618534,0.0123124) , 
7, 1.04004, 1, 0, 0.67626,0.0286836) , 
6, 107.719, 1, 0, 0.611741,0.0100253) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.604962,-0.0235854) , 
2, 95.1641, 1, 0, 0.610311,0.00372246) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.498304,-0.0139131) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.335264,0.0218786) , 
3, 347.095, 1, 0, 0.453585,-0.00404339) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.529411,0.0452289) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.479057,0.00262106) , 
0, 39.6893, 1, 0, 0.500146,0.0164645) , 
2, 61.5138, 1, 0, 0.472119,0.0041199) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.562929,-0.00930863) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.586068,-0.0419181) , 
2, 51.4091, 1, 0, 0.573972,-0.021438) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.38402,-0.00673468) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.182723,0.0189845) , 
5, 114.242, 1, 0, 0.266859,0.00306813) , 
1, 41.8151, 1, 0, 0.403076,-0.00780137) , 
0, 57.2913, 1, 0, 0.436569,-0.00201835) , 
7, 1.7236, 1, 0, 0.5,7.75419e-05)    );
  // itree = 31
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.578464,-0.0282634) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.696784,0.00959809) , 
9, -1.72271, 1, 0, 0.674627,0.00154171) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.415739,0.0323973) , 
1, 77.5871, 1, 0, 0.629273,0.00611558) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.472079,-0.000561077) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.450839,0.0218207) , 
2, 88.524, 1, 0, 0.469512,0.00175224) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.408022,-0.044994) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.42654,-0.00480303) , 
8, -0.508721, 1, 0, 0.418425,-0.0177787) , 
6, 95.7195, 1, 0, 0.45926,-0.00216737) , 
7, 1.7236, 1, 0, 0.521429,0.000861495) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.217801,-0.0195957) , 
5, 198.671, 1, 0, 0.5,9.83456e-05)    );
  // itree = 32
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.699255,-0.0119101) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.445055,0.0231343) , 
1, 39.0243, 1, 0, 0.561213,0.00664596) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.650085,0.026146) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.276941,-0.0101005) , 
1, 42.0365, 1, 0, 0.438696,0.00600643) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.52946,0.00316374) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.184332,-0.0267507) , 
1, 123.343, 1, 0, 0.491162,0.000676205) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.516363,-0.0148032) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.518396,0.00860099) , 
0, 84.5893, 1, 0, 0.516931,-0.00664812) , 
8, 0.70939, 1, 0, 0.50072,-0.00204038) , 
6, 40.7077, 1, 0, 0.491285,-0.000816304) , 
3, 189.352, 1, 0, 0.5,0.000113742)    );
  // itree = 33
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.421049,0.0119363) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.758695,0.0104764) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.452593,-0.00724786) , 
1, 31.635, 1, 0, 0.575088,-0.000557073) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.357277,0.036991) , 
4, 480.969, 1, 0, 0.554824,0.00185772) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.428579,-0.0203248) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.516895,0.00397408) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.200696,-0.0241894) , 
1, 79.1275, 1, 0, 0.410958,-0.00224744) , 
8, -1.72271, 1, 0, 0.414012,-0.00473311) , 
3, 367.712, 1, 0, 0.50522,-0.000464064) , 
9, -2.73612, 1, 0, 0.5,0.000117052)    );
  // itree = 34
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.550626,0.00665076) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.49809,-0.0143196) , 
8, -2.45945, 1, 0, 0.51576,-0.00565955) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.675963,0.0306416) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.256387,0.00279697) , 
1, 61.9007, 1, 0, 0.496492,0.0143936) , 
8, -1.21946, 1, 0, 0.505366,0.00515814) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.662886,0.0356498) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.445801,-0.0216377) , 
7, 2.21781, 1, 0, 0.558123,0.00752689) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.433781,-0.0059488) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.343773,-0.0371895) , 
10, 0.508108, 1, 0, 0.410297,-0.00938605) , 
8, -1.35673, 1, 0, 0.46294,-0.00336316) , 
0, 65.1114, 1, 0, 0.486417,0.00135219) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.418634,-0.0271667) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.557217,0.0107217) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.489828,-0.0214749) , 
9, 0.264946, 1, 0, 0.530869,-0.00149796) , 
9, -1.31742, 1, 0, 0.498348,-0.00743326) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.577895,-0.00968601) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.595677,0.024487) , 
10, 1.72247, 1, 0, 0.586777,0.00664017) , 
6, 96.2161, 1, 0, 0.529744,-0.00243666) , 
8, 1.11474, 1, 0, 0.5,0.000164374)    );
  // itree = 35
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.532496,-0.0116769) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.658611,0.0121979) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.525144,-0.00843303) , 
7, 2.88971, 1, 0, 0.631195,0.00643648) , 
10, -2.12808, 1, 0, 0.610076,0.00286613) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.653969,0.0104546) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.550822,-0.0173042) , 
10, 0.709024, 1, 0, 0.61897,0.000574109) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.410847,-0.0312931) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.349605,-0.00419411) , 
5, 92.3726, 1, 0, 0.384752,-0.0162481) , 
7, 2.27898, 1, 0, 0.523487,-0.00628379) , 
5, 69.7179, 1, 0, 0.572927,-0.00105945) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.320049,0.0337352) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.485499,-0.00229685) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.324104,-0.035159) , 
5, 159.011, 1, 0, 0.410888,-0.0114127) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.216857,0.0294246) , 
7, 2.38498, 1, 0, 0.333546,-0.000638765) , 
10, -1.31678, 1, 0, 0.33109,0.00338176) , 
5, 113.617, 1, 0, 0.5,0.000279816)    );
  // itree = 36
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.563063,0.0213278) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.431422,-0.00865739) , 
3, 283.687, 1, 0, 0.497111,0.00603988) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.599261,0.00223635) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.417178,-0.0233125) , 
5, 62.729, 1, 0, 0.481632,-0.0107267) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.415011,0.0067069) , 
8, -0.709366, 1, 0, 0.464755,-0.00677669) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.372152,-0.0188897) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.616518,0.00723112) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.363164,-0.00497469) , 
5, 105.918, 1, 0, 0.522678,0.00243254) , 
9, -2.33077, 1, 0, 0.51134,0.00121958) , 
10, -0.918489, 1, 0, 0.500401,-0.000658148) , 
10, -2.33075, 1, 0, 0.5,0.000157383)    );
  // itree = 37
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.595078,0.00588851) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.502377,-0.0137901) , 
10, 2.12815, 1, 0, 0.579195,0.00199564) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.740616,-0.0198136) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.508208,0.00966153) , 
1, 36.7941, 1, 0, 0.642276,-0.0045621) , 
6, 83.9923, 1, 0, 0.602435,-0.000420326) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.544057,-0.0210364) , 
9, 2.33083, 1, 0, 0.596283,-0.00227696) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.419464,0.000914434) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.294893,0.0218706) , 
9, 1.72284, 1, 0, 0.388821,0.00395199) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.361308,-0.0171776) , 
8, 0.767669, 1, 0, 0.383396,0.00078719) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.480812,0.0227579) , 
8, 1.51941, 1, 0, 0.394959,0.00284479) , 
5, 85.2659, 1, 0, 0.5,0.000172516)    );
  // itree = 38
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.538403,-0.00873743) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.435047,-0.0397492) , 
10, 1.52019, 1, 0, 0.513962,-0.0128855) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.605934,0.01422) , 
2, 69.3075, 1, 0, 0.543208,-0.0050794) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.470329,0.0375928) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.518482,0.00358321) , 
6, 69.2463, 1, 0, 0.500555,0.0130919) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.737298,0.0110433) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.528888,-0.0172963) , 
7, 1.64819, 1, 0, 0.602082,-0.00651255) , 
2, 45.5644, 1, 0, 0.557621,0.0020728) , 
0, 52.3027, 1, 0, 0.551222,-0.00110227) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.524873,-0.00529175) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.4074,-0.0029242) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.157211,0.0138685) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.171151,0.0493191) , 
9, 0.101385, 1, 0, 0.163931,0.0135393) , 
7, 1.66185, 1, 0, 0.248625,0.00798987) , 
1, 52.8076, 1, 0, 0.353543,0.00329163) , 
4, 559.416, 1, 0, 0.5,3.62708e-05)    );
  // itree = 39
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.491614,0.00974608) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.593381,-0.0140169) , 
9, -1.31747, 1, 0, 0.566687,-0.00600242) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.689549,0.0223356) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.418618,0.0015794) , 
4, 420.156, 1, 0, 0.45605,0.00335805) , 
3, 283.744, 1, 0, 0.500594,-0.000410622) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.547501,-0.0152854) , 
8, 2.33066, 1, 0, 0.504081,-0.00135298) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.557536,0.0199921) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.373546,-0.0181259) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.507846,0.00599003) , 
6, 88.3157, 1, 0, 0.441232,-0.00436697) , 
3, 255.636, 1, 0, 0.486935,0.00417813) , 
10, 1.52011, 1, 0, 0.5,-3.65628e-05)    );
  // itree = 40
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.496525,0.007631) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.465886,0.0259353) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.515966,0.0147734) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.40107,-0.0194751) , 
7, 2.87394, 1, 0, 0.459863,-0.00128085) , 
6, 21.0861, 1, 0, 0.461849,0.00579556) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.567639,0.00361564) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.555003,-0.0127089) , 
2, 95.1641, 1, 0, 0.565305,0.000371368) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.360983,-0.0206042) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.347734,0.0139977) , 
2, 92.6666, 1, 0, 0.356869,-0.00697049) , 
7, 2.43087, 1, 0, 0.50784,-0.00165278) , 
6, 40.7077, 1, 0, 0.500233,-0.000420873) , 
10, -2.73611, 1, 0, 0.5,1.12084e-05)    );
  // itree = 41
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.41111,-0.0133863) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.57293,0.0165126) , 
2, 40.0083, 1, 0, 0.506577,0.00367313) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.555212,-0.0158783) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.536836,0.00337146) , 
0, 87.5386, 1, 0, 0.54949,-0.00812529) , 
6, 63.9552, 1, 0, 0.534342,-0.00396038) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.241539,0.0165995) , 
1, 96.3461, 1, 0, 0.488853,-0.00183806) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.638794,-0.00851306) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.597217,0.0268458) , 
3, 277.102, 1, 0, 0.61136,0.010982) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.69586,0.00586297) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.39108,-0.00695284) , 
1, 34.2742, 1, 0, 0.524229,-0.00114318) , 
10, 0.696384, 1, 0, 0.552956,0.00285446) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.219117,-0.0127824) , 
1, 105.58, 1, 0, 0.508732,0.00151108) , 
10, -0.303982, 1, 0, 0.5,3.99211e-05)    );
  // itree = 42
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.571172,-0.0016553) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.619446,0.0229087) , 
0, 56.8261, 1, 0, 0.596407,0.00969415) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.444012,-0.00735272) , 
3, 362.423, 1, 0, 0.551011,0.00501588) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.667219,0.0105683) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.582973,-0.00858731) , 
0, 58.7733, 1, 0, 0.624122,0.000532288) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.356514,-0.0306343) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.227024,-0.00313515) , 
5, 115.438, 1, 0, 0.264359,-0.00841047) , 
1, 61.757, 1, 0, 0.490525,-0.00278858) , 
8, -1.72271, 1, 0, 0.504081,-0.00103953) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.557536,0.0123917) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.509201,0.00476476) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.322836,-0.0130613) , 
7, 2.55653, 1, 0, 0.441232,-0.000866887) , 
3, 255.636, 1, 0, 0.486935,0.00367883) , 
10, 1.52011, 1, 0, 0.5,8.34505e-05)    );
  // itree = 43
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.653215,-0.0128941) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.664036,0.00858193) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.655845,-0.00940655) , 
8, 1.78174, 1, 0, 0.661726,0.00264631) , 
8, -2.12802, 1, 0, 0.660272,0.000351228) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.458055,-0.0200244) , 
1, 46.0137, 1, 0, 0.63626,-0.00170568) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.405376,0.0164425) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.416073,-0.0172434) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.214169,0.0027661) , 
7, 1.55785, 1, 0, 0.272396,-0.00304465) , 
8, -1.78174, 1, 0, 0.299086,0.000337671) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.414627,0.0212563) , 
8, 2.12798, 1, 0, 0.31414,0.00268682) , 
1, 52.8076, 1, 0, 0.5,0.000152383)    );
  // itree = 44
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.671082,-0.0162961) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.646496,0.000748538) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.546378,0.018298) , 
3, 387.291, 1, 0, 0.62403,0.00403037) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.560624,-7.04154e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.461262,-0.0224317) , 
6, 35.6268, 1, 0, 0.509986,-0.00948543) , 
7, 2.6533, 1, 0, 0.585882,-0.000490684) , 
7, 1.05725, 1, 0, 0.596283,-0.00196381) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.582849,0.0269599) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.623361,0.000943788) , 
2, 62.5821, 1, 0, 0.602343,0.0111078) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.257236,0.0259713) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.314109,-0.00468698) , 
0, 78.3159, 1, 0, 0.284692,0.00682275) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.428491,-0.0330878) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.291719,0.00495874) , 
9, 0.781416, 1, 0, 0.33728,-0.00642998) , 
9, -0.709331, 1, 0, 0.316046,-0.00107868) , 
7, 1.3918, 1, 0, 0.394959,0.00228035) , 
5, 85.2659, 1, 0, 0.5,6.59613e-05)    );
  // itree = 45
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.564466,0.00692986) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.633936,-0.00120557) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.559382,-0.0170486) , 
5, 69.2835, 1, 0, 0.613452,-0.00446369) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.483062,0.0223877) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.387838,-0.00232831) , 
8, -1.51999, 1, 0, 0.399263,0.000680206) , 
5, 83.4443, 1, 0, 0.494256,-0.00160112) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.451163,-0.00133585) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.552909,0.0176482) , 
6, 88.3157, 1, 0, 0.498558,0.00621651) , 
10, 2.12815, 1, 0, 0.494874,-0.000477075) , 
5, 28.5632, 1, 0, 0.5,1.52809e-05)    );
  // itree = 46
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.72078,-0.00333167) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.468745,0.00988153) , 
1, 26.9272, 1, 0, 0.579219,0.00371904) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.25295,0.00256114) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.2519,-0.0369224) , 
9, -1.7243, 1, 0, 0.25248,-0.0102853) , 
1, 59.4158, 1, 0, 0.458198,-0.00146799) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.765266,0.0320946) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.653348,0.00899201) , 
9, 0.237834, 1, 0, 0.712974,0.0153619) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.658847,0.0132537) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.484358,-0.0132013) , 
5, 53.2342, 1, 0, 0.556266,-0.00159614) , 
7, 1.646, 1, 0, 0.617431,0.00502276) , 
9, -0.395531, 1, 0, 0.526632,0.00132155) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.469368,-0.0197752) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.57127,-0.00478558) , 
10, 1.72206, 1, 0, 0.524957,-0.00924665) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.345088,-0.00708047) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.37904,0.0138609) , 
2, 59.662, 1, 0, 0.360099,0.001755) , 
7, 2.04869, 1, 0, 0.434326,-0.00319842) , 
9, 1.11478, 1, 0, 0.5,1.74591e-05)    );
  // itree = 47
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.634867,0.00689735) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.473777,-0.0091872) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.600294,0.00918346) , 
9, -1.11396, 1, 0, 0.553421,0.00189307) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.33069,-0.0231307) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.377322,-0.00378291) , 
2, 59.6598, 1, 0, 0.35237,-0.00992594) , 
7, 2.22121, 1, 0, 0.461685,-0.00349972) , 
4, 324.267, 1, 0, 0.499152,-0.00153293) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.535296,-0.0132223) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.653024,0.00870019) , 
9, -1.31725, 1, 0, 0.617624,0.00142828) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.446013,0.0206512) , 
4, 365.871, 1, 0, 0.57321,0.00536433) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.464719,0.00954957) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.405202,-0.0103217) , 
0, 74.2188, 1, 0, 0.441018,0.00135574) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.48803,-0.0160119) , 
8, 2.36337, 1, 0, 0.449335,-0.00126933) , 
3, 283.687, 1, 0, 0.500689,0.00148072) , 
8, -0.303988, 1, 0, 0.5,0.000130338)    );
  // itree = 48
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.652326,-0.00925673) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.561493,0.00966451) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.472321,0.000928325) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.51975,-0.00586738) , 
8, 1.31743, 1, 0, 0.483902,-0.000658653) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.519252,0.0116521) , 
10, 2.73618, 1, 0, 0.486019,-3.42272e-05) , 
5, 28.5632, 1, 0, 0.491236,0.00056777) , 
4, 256.186, 1, 0, 0.5,0.00013658)    );
  // itree = 49
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.448622,-0.01935) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.665108,0.0126928) , 
2, 40.5059, 1, 0, 0.586053,0.000712481) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.580644,-0.0142624) , 
2, 95.1641, 1, 0, 0.585022,-0.00165599) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.456211,0.00641012) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.350745,-0.00759859) , 
6, 70.0435, 1, 0, 0.418509,0.00120895) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.42762,0.0171967) , 
10, 1.61816, 1, 0, 0.419912,0.0030684) , 
7, 2.05677, 1, 0, 0.499761,0.000783632) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.50231,-0.00820431) , 
10, 2.5335, 1, 0, 0.5,6.66314e-05)    );
   return;
};
 
// Clean up
inline void ReadBDT::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDT::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
