// Class: ReadBDT
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.10/04       [395780]
Creator        : marine5575
Date           : Wed Oct  9 01:09:24 2019
Host           : Linux htop.hanyang.ac.kr 2.6.32-696.el6.centos.plus.x86_64 #1 SMP Mon Apr 3 14:56:08 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/marine5575/work/Undergrad2018/mva
Training events: 65134
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "50" [Number of trees in the forest]
MaxDepth: "4" [Max depth of the decision tree allowed]
MinNodeSize: "5%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
nCuts: "10" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "Grad" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
Shrinkage: "5.000000e-01" [Learning rate for GradBoost algorithm]
SeparationType: "giniindex" [Separation criterion for node splitting]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
UseBaggedBoost: "False" [Use only a random subsample of all events for growing the trees in each boost iteration.]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "3" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Poisson distribution in each split with RandomisedTree option]
BaggedSampleFraction: "6.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "pray" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in training sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
RegressionLossFunctionBDTG: "huber" [Loss function for BDTG regression.]
HuberQuantile: "7.000000e-01" [In the Huber loss function this is the quantile that separates the core from the tails in the residuals distribution.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
SkipNormalization: "False" [Skip normalization at initialization, to keep expectation value of BDT output according to the fraction of events]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "6.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 11
lepton1_pt                    lepton1_pt                    lepton1_pt                    lepton1_pt                                                      'F'    [30.0022735596,875.963500977]
met_pt                        met_pt                        met_pt                        met_pt                                                          'F'    [0.174064293504,815.994018555]
tau1_pt                       tau1_pt                       tau1_pt                       tau1_pt                                                         'F'    [30.0001525879,1040.04150391]
jet_ht                        jet_ht                        jet_ht                        jet_ht                                                          'F'    [95.0174484253,3019.39990234]
jetlepmet_ht                  jetlepmet_ht                  jetlepmet_ht                  jetlepmet_ht                                                    'F'    [155.10949707,3288.48583984]
lep1met_pt                    lep1met_pt                    lep1met_pt                    lep1met_pt                                                      'F'    [0.211814135313,879.103881836]
lep1tau1_pt                   lep1tau1_pt                   lep1tau1_pt                   lep1tau1_pt                                                     'F'    [0.17061945796,1256.81884766]
tau1_lep1_dr                  tau1_lep1_dr                  tau1_lep1_dr                  tau1_lep1_dr                                                    'F'    [0.390903234482,5.5550994873]
lep1_met_dphi                 lep1_met_dphi                 lep1_met_dphi                 lep1_met_dphi                                                   'F'    [-3.14144611359,3.14149641991]
tau1_met_dphi                 tau1_met_dphi                 tau1_met_dphi                 tau1_met_dphi                                                   'F'    [-3.14148163795,3.14157342911]
tau1lep1_met_dphi             tau1lep1_met_dphi             tau1lep1_met_dphi             tau1lep1_met_dphi                                               'F'    [-3.14146351814,3.14153146744]
NSpec 2
njet                          njet                          njet                          njet                                                            'F'    [3,12]
nbjet                         nbjet                         nbjet                         nbjet                                                           'F'    [0,6]


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDTNode
   
#ifndef BDTNode__def
#define BDTNode__def
   
class BDTNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDTNode ( BDTNode* left,BDTNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDTNode();

   // test event if it descends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDTNode* GetRight( void )  {return fRight; };

   // test event if it descends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDTNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDTNode*   fLeft;     // pointer to the left daughter node
   BDTNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value applied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDTNode::~BDTNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDTNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDTNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT : public IClassifierReader {

 public:

   // constructor
   ReadBDT( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDT" ),
        fNvars( 11 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "lepton1_pt", "met_pt", "tau1_pt", "jet_ht", "jetlepmet_ht", "lep1met_pt", "lep1tau1_pt", "tau1_lep1_dr", "lep1_met_dphi", "tau1_met_dphi", "tau1lep1_met_dphi" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;
      fVmin[8] = 0;
      fVmax[8] = 0;
      fVmin[9] = 0;
      fVmax[9] = 0;
      fVmin[10] = 0;
      fVmax[10] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[11];
   double fVmax[11];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[11];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDTNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDTNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDTNode*)current->GetRight();
         else current=(BDTNode*)current->GetLeft();
      }
      myMVA += current->GetResponse();
   }
   return 2.0/(1.0+exp(-2.0*myMVA))-1.0;
};

void ReadBDT::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.822461,0.278228) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.73452,0.208409) , 
1, 21.6256, 1, 0, 0.783317,0.283317) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.724378,0.200087) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.519763,0.0189476) , 
4, 420.473, 1, 0, 0.658435,0.158435) , 
7, 1.80692, 1, 0, 0.71214,0.21214) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.492332,-0.00742625) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.61175,0.10364) , 
6, 102.71, 1, 0, 0.564157,0.0641571) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.470372,-0.0289312) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.321534,-0.184543) , 
4, 405.856, 1, 0, 0.395063,-0.104938) , 
7, 1.7176, 1, 0, 0.456118,-0.0438821) , 
1, 33.8852, 1, 0, 0.58275,0.0827501) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.422901,-0.0766467) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.349425,-0.154001) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.234878,-0.283898) , 
5, 103.349, 1, 0, 0.285177,-0.214823) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.123539,-0.422416) , 
5, 161.352, 1, 0, 0.227619,-0.272381) , 
7, 1.33216, 1, 0, 0.26737,-0.23263) , 
1, 74.3395, 1, 0, 0.5,-4.87679e-15)    );
  // itree = 1
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.798487,0.173514) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.6799,0.0974948) , 
4, 448.212, 1, 0, 0.763655,0.164071) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.674497,0.104807) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.523577,-0.00207864) , 
7, 2.2758, 1, 0, 0.612725,0.0654497) , 
1, 22.2387, 1, 0, 0.68205,0.110749) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.336029,-0.140979) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.602493,0.112342) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.355361,-0.120744) , 
9, 0.59736, 1, 0, 0.472165,-0.00518045) , 
9, -0.856689, 1, 0, 0.429225,-0.0461889) , 
1, 40.6274, 1, 0, 0.58275,0.0491095) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.373382,-0.0494131) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.29196,-0.0968269) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.15573,-0.230868) , 
4, 487.918, 1, 0, 0.21225,-0.144754) , 
7, 1.79859, 1, 0, 0.26737,-0.111298) , 
1, 74.3395, 1, 0, 0.5,0.00702151)    );
  // itree = 2
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.516758,-0.0404313) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.640089,0.0742568) , 
2, 37.8756, 1, 0, 0.569885,0.0100406) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.632338,0.0735049) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.718188,0.130908) , 
10, -1.42777, 1, 0, 0.693928,0.118043) , 
2, 47.3278, 1, 0, 0.639682,0.0708118) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.589351,0.0424558) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.348622,-0.0895538) , 
7, 2.13429, 1, 0, 0.478182,-0.0154401) , 
4, 474.047, 1, 0, 0.600281,0.0497694) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.667087,0.109342) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.57681,0.030355) , 
7, 0.907496, 1, 0, 0.619324,0.0697153) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.472821,-0.00296766) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.209355,-0.147128) , 
5, 147.116, 1, 0, 0.396087,-0.0340293) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.347098,-0.0795649) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.202091,-0.160329) , 
3, 319.948, 1, 0, 0.271343,-0.0978875) , 
7, 2.47667, 1, 0, 0.333463,-0.0660877) , 
7, 1.33161, 1, 0, 0.406501,-0.0313895) , 
5, 80.1111, 1, 0, 0.5,0.00776958)    );
  // itree = 3
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.670926,0.0712598) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.572414,-0.00971243) , 
9, 1.42803, 1, 0, 0.648243,0.0522753) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.352451,-0.0869313) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.436355,-0.0286204) , 
9, -0.285176, 1, 0, 0.40087,-0.0498291) , 
1, 54.1119, 1, 0, 0.599665,0.0322246) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.28294,-0.0540236) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.425908,0.0492004) , 
6, 91.045, 1, 0, 0.337623,-0.0100006) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.178867,-0.119034) , 
5, 160.955, 1, 0, 0.280217,-0.0340309) , 
1, 74.3395, 1, 0, 0.517822,0.0152498) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.304924,-0.11227) , 
7, 3.20774, 1, 0, 0.5,0.00623414)    );
  // itree = 4
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.522472,0.0254232) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.485414,-0.0277672) , 
10, -2.51839, 1, 0, 0.504227,-0.000427221) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.41601,-0.102463) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.466708,-0.0217482) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.305358,-0.0630524) , 
3, 317.522, 1, 0, 0.392938,-0.0321884) , 
8, -0.287085, 1, 0, 0.400652,-0.0506182) , 
10, -1.9991, 1, 0, 0.433367,-0.0347648) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.549363,-0.000864959) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.719204,0.128189) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.55303,0.0541394) , 
7, 2.13762, 1, 0, 0.647705,0.0935102) , 
9, -0.460234, 1, 0, 0.625122,0.0718539) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.458528,-0.0357632) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.564787,0.039723) , 
2, 50.3749, 1, 0, 0.509978,0.000942399) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.422754,-0.0343924) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.274561,-0.0904852) , 
4, 658.65, 1, 0, 0.364014,-0.0442405) , 
3, 351.24, 1, 0, 0.454395,-0.0162633) , 
9, 0.597213, 1, 0, 0.531743,0.0236583) , 
9, -0.856734, 1, 0, 0.5,0.00480686)    );
  // itree = 5
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.80377,0.108002) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.675552,0.0126827) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.749345,0.0638069) , 
9, -0.856385, 1, 0, 0.726497,0.0443668) , 
1, 12.6754, 1, 0, 0.749247,0.0607148) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.323062,-0.0958779) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.510286,0.0508939) , 
2, 40.4996, 1, 0, 0.400385,-0.0282294) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.500242,0.0284256) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.402855,-0.0140954) , 
9, 0.85679, 1, 0, 0.467436,0.0129112) , 
2, 58.8743, 1, 0, 0.428586,-0.0109258) , 
1, 27.4885, 1, 0, 0.524479,0.0104981) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.29702,-0.0443895) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.321281,-0.0818125) , 
3, 665.351, 1, 0, 0.310394,-0.0486378) , 
4, 724.814, 1, 0, 0.5,0.00373639)    );
  // itree = 6
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.674156,0.0524582) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.805733,0.0595105) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.556688,0.0195637) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.451077,-0.0265415) , 
9, 0.856828, 1, 0, 0.521714,0.00418373) , 
1, 19.6154, 1, 0, 0.586129,0.0145014) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.462401,0.00087649) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.302813,-0.0534727) , 
4, 675.242, 1, 0, 0.420075,-0.00983086) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.271739,-0.0399966) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.203633,-0.0823367) , 
3, 422.774, 1, 0, 0.239298,-0.0404713) , 
7, 2.87555, 1, 0, 0.376078,-0.0172881) , 
4, 427.556, 1, 0, 0.482822,-0.0011333) , 
7, 0.860376, 1, 0, 0.5,0.00337887)    );
  // itree = 7
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.392076,-0.0171206) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.391873,-0.0644313) , 
6, 57.2861, 1, 0, 0.391976,-0.032568) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.564498,0.0272696) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.440424,-0.025976) , 
10, -1.99918, 1, 0, 0.488703,-0.0035717) , 
6, 89.9286, 1, 0, 0.433367,-0.0201601) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.8147,0.0943042) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.655865,0.0302388) , 
7, 1.71905, 1, 0, 0.721455,0.0500395) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.428169,0.0194828) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.350429,-0.0337828) , 
9, 0.134644, 1, 0, 0.395918,-0.00151969) , 
1, 58.3055, 1, 0, 0.610916,0.0325323) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.375057,-0.0170717) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.454719,0.030704) , 
10, 0.285986, 1, 0, 0.415492,0.00602037) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.42381,-0.0768233) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.526291,-0.000268524) , 
10, 1.88261, 1, 0, 0.4742,-0.032404) , 
8, 0.285613, 1, 0, 0.438893,-0.00929596) , 
9, 0.960693, 1, 0, 0.531743,0.0132808) , 
9, -0.856734, 1, 0, 0.5,0.00249043)    );
  // itree = 8
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.407598,-0.0529485) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.548331,0.00262063) , 
9, -1.32413, 1, 0, 0.465911,-0.024758) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.605232,0.0370468) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.531574,-0.00475028) , 
3, 271.095, 1, 0, 0.572625,0.0168471) , 
2, 49.5596, 1, 0, 0.519353,-0.0039223) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.527734,-0.0139934) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.206823,-0.065846) , 
1, 55.8254, 1, 0, 0.375487,-0.0259773) , 
3, 360.87, 1, 0, 0.466884,-0.011966) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.743951,0.0855736) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.572113,0.0338422) , 
7, 2.13762, 1, 0, 0.672302,0.055809) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.573826,0.00931438) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.340371,-0.0330779) , 
4, 387.141, 1, 0, 0.452134,-0.00916906) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.494351,-0.00866371) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.557123,0.0420304) , 
10, 1.42724, 1, 0, 0.524052,0.0140751) , 
6, 114.494, 1, 0, 0.471539,-0.00289736) , 
9, 0.337638, 1, 0, 0.52483,0.012686) , 
9, -0.285548, 1, 0, 0.5,0.00212259)    );
  // itree = 9
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.581241,0.034424) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.49369,-0.0337683) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.464399,0.00502841) , 
8, -0.493606, 1, 0, 0.474327,-0.00695529) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.695672,0.0425972) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.480475,-0.00230242) , 
9, 0.337644, 1, 0, 0.53958,0.00846417) , 
9, -0.285548, 1, 0, 0.511719,0.0018805) , 
8, -2.57027, 1, 0, 0.517822,0.00448731) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.304924,-0.0388654) , 
7, 3.20774, 1, 0, 0.5,0.00175459)    );
  // itree = 10
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.796256,0.0514246) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.482984,-0.0391015) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.612866,0.00659194) , 
9, -1.42786, 1, 0, 0.584019,-0.00334656) , 
1, 16.0653, 1, 0, 0.625484,0.00530791) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.435683,-0.0434302) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.335956,0.0114967) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.236926,-0.0216463) , 
7, 2.09657, 1, 0, 0.268263,-0.00674522) , 
7, 1.33351, 1, 0, 0.301772,-0.0136049) , 
1, 58.4429, 1, 0, 0.507195,-0.00160313) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.648802,0.0510867) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.330161,-0.000835512) , 
7, 1.72321, 1, 0, 0.457218,0.0176359) , 
0, 106.908, 1, 0, 0.5,0.00116649)    );
  // itree = 11
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.55767,0.00473101) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.40081,-0.0297373) , 
5, 80.3146, 1, 0, 0.490166,-0.00777583) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.585727,0.0501424) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.659005,0.0335985) , 
9, -0.856578, 1, 0, 0.63406,0.0346514) , 
2, 42.5327, 1, 0, 0.569401,0.0155868) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.560922,0.00218646) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.470995,-0.056173) , 
10, 1.42723, 1, 0, 0.539011,-0.0100675) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.625729,0.0279658) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.407615,-0.00428863) , 
5, 114.942, 1, 0, 0.529152,0.0121982) , 
0, 67.155, 1, 0, 0.535195,-0.00144978) , 
3, 240.027, 1, 0, 0.550566,0.00620595) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.407715,-0.0134718) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.51659,0.0334293) , 
2, 58.2064, 1, 0, 0.466152,0.009783) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.351833,-0.0484482) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.451729,-0.00811619) , 
2, 65.6588, 1, 0, 0.403599,-0.0204286) , 
3, 448.759, 1, 0, 0.437597,-0.00400844) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.337008,-0.0273349) , 
3, 602.567, 1, 0, 0.413056,-0.00777031) , 
3, 360.87, 1, 0, 0.5,0.00106651)    );
  // itree = 12
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.674156,0.0215254) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.441196,-0.021324) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.266827,-0.0883033) , 
3, 328.737, 1, 0, 0.37648,-0.0334181) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.566497,0.0171626) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.400569,-0.0153119) , 
7, 2.98301, 1, 0, 0.537676,0.00980103) , 
2, 38.0738, 1, 0, 0.490436,-0.00286461) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.417937,0.0208084) , 
2, 118.81, 1, 0, 0.482822,-0.000908172) , 
7, 0.860376, 1, 0, 0.5,0.00083906)    );
  // itree = 13
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.529355,-0.00318266) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.527962,0.0296183) , 
8, -0.597157, 1, 0, 0.52884,0.00678212) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.183811,-0.0387656) , 
1, 116.715, 1, 0, 0.488688,0.00362168) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.661847,0.0157091) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.479991,-0.0114024) , 
7, 1.80779, 1, 0, 0.531102,-0.00302678) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.480562,-0.0444306) , 
9, 1.42798, 1, 0, 0.521477,-0.00976333) , 
8, 0.856709, 1, 0, 0.499748,-0.000893116) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.502604,0.0202859) , 
10, 2.57035, 1, 0, 0.5,0.000709601)    );
  // itree = 14
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.526785,-0.00446574) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.561246,0.0226738) , 
8, -0.847306, 1, 0, 0.540449,0.00492501) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.33875,-0.0498666) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.15427,0.0195831) , 
7, 2.17905, 1, 0, 0.242866,-0.0121782) , 
5, 160.01, 1, 0, 0.487031,0.00185488) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.399003,0.00241298) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.548488,-0.0347021) , 
9, -0.856546, 1, 0, 0.491674,-0.0170982) , 
8, 1.06448, 1, 0, 0.487861,-0.00153554) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.618674,0.029164) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.517766,-0.000376517) , 
3, 250.671, 1, 0, 0.557494,0.01009) , 
8, 1.99914, 1, 0, 0.5,0.000491084)    );
  // itree = 15
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.821855,0.0509385) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.570174,-0.0114149) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.579905,0.023187) , 
0, 57.9171, 1, 0, 0.572915,-0.00124006) , 
1, 14.6823, 1, 0, 0.612732,0.00493881) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.391103,0.0153141) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.521176,-0.00491858) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.296439,-0.0262812) , 
7, 2.26607, 1, 0, 0.429035,-0.00972367) , 
10, -1.99879, 1, 0, 0.424517,-0.00715973) , 
5, 67.8762, 1, 0, 0.507195,-0.00184519) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.648802,0.038676) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.330161,-0.00010263) , 
7, 1.72321, 1, 0, 0.457218,0.0131687) , 
0, 106.908, 1, 0, 0.5,0.000316184)    );
  // itree = 16
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.823682,0.0421671) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.760803,0.0277348) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.644924,-0.0299078) , 
0, 70.1136, 1, 0, 0.71777,0.0044029) , 
7, 1.27933, 1, 0, 0.742898,0.0105865) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.483792,-0.0293081) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.60983,0.0102218) , 
9, -0.856883, 1, 0, 0.571476,-0.00188124) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.436299,-0.0121024) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.3676,-0.040178) , 
5, 105.924, 1, 0, 0.415741,-0.0168443) , 
1, 44.3074, 1, 0, 0.488387,-0.00986446) , 
1, 27.143, 1, 0, 0.58275,-0.00228201) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.360168,0.0500502) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.302653,-0.0630806) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.155624,0.0196539) , 
7, 1.79859, 1, 0, 0.206883,-0.0117853) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.360872,0.0468358) , 
8, 1.47986, 1, 0, 0.243918,4.16552e-05) , 
8, -1.42796, 1, 0, 0.26737,0.00804669) , 
1, 74.3395, 1, 0, 0.5,0.000428053)    );
  // itree = 17
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.464709,-0.0365125) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.570442,0.00647768) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.438056,-0.0250504) , 
9, 1.47992, 1, 0, 0.52743,-0.00301032) , 
9, -1.42725, 1, 0, 0.515032,-0.00848684) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.526455,0.0527622) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.453047,0.0106438) , 
0, 50.9893, 1, 0, 0.483224,0.0205123) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.527025,-0.00207345) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.462674,-0.0323015) , 
9, 1.42797, 1, 0, 0.513476,-0.00700061) , 
8, 0.597172, 1, 0, 0.502753,0.00275169) , 
8, -0.85674, 1, 0, 0.507195,-0.00131363) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.530961,0.0267873) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.399642,0.00210146) , 
3, 354.066, 1, 0, 0.457218,0.0106981) , 
0, 106.908, 1, 0, 0.5,0.000415547)    );
  // itree = 18
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.674156,0.014971) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.483591,0.000166426) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.465262,-0.0313004) , 
10, -1.57866, 1, 0, 0.475142,-0.0109958) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.468241,0.0056387) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.380821,-0.0163327) , 
0, 75.3878, 1, 0, 0.438606,-0.00117094) , 
8, -0.285604, 1, 0, 0.452054,-0.00478731) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.731433,0.0326458) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.580621,-0.000405183) , 
7, 2.03857, 1, 0, 0.652938,0.0119003) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.437868,0.00386542) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.487044,-0.0106732) , 
8, 0.285613, 1, 0, 0.45613,-0.00133788) , 
9, 0.337638, 1, 0, 0.506227,0.00203187) , 
9, -0.285548, 1, 0, 0.482822,-0.00091436) , 
7, 0.860376, 1, 0, 0.5,0.000281886)    );
  // itree = 19
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.47661,-0.0254768) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.490747,-0.0109286) , 
8, -0.856089, 1, 0, 0.483646,-0.01544) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.648983,0.0108904) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.311042,-0.0295272) , 
5, 122.131, 1, 0, 0.59519,0.00414401) , 
9, -1.42794, 1, 0, 0.56973,-0.000326142) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.699687,0.044258) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.492529,-0.000874528) , 
7, 1.24859, 1, 0, 0.590433,0.0171957) , 
0, 92.3042, 1, 0, 0.574018,0.00330331) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.591217,0.0353719) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.251078,0.00104842) , 
1, 58.9389, 1, 0, 0.463224,0.0196477) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.400875,-0.0299884) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.452962,0.0166377) , 
2, 71.0714, 1, 0, 0.418977,-0.0102767) , 
6, 37.807, 1, 0, 0.437744,0.00241552) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.310934,-0.0322529) , 
6, 82.9736, 1, 0, 0.407581,-0.00357511) , 
7, 2.26879, 1, 0, 0.5,0.000244329)    );
  // itree = 20
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.504502,-0.0278054) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.574657,0.0106816) , 
0, 44.613, 1, 0, 0.542198,-0.00603784) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.574009,0.0344542) , 
0, 70.1853, 1, 0, 0.553713,0.00722133) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.631483,0.00539887) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.594815,-0.0267495) , 
2, 105.027, 1, 0, 0.626604,0.000929166) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.427899,-0.0320256) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.236605,-0.00697244) , 
7, 1.2813, 1, 0, 0.275318,-0.00921496) , 
1, 58.4429, 1, 0, 0.490527,-0.00300034) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.426707,-0.0151046) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.530984,0.0351673) , 
6, 82.9736, 1, 0, 0.479643,0.009156) , 
10, 1.99917, 1, 0, 0.48875,-0.00101627) , 
8, -1.99909, 1, 0, 0.5,0.000410222)    );
  // itree = 21
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.801182,0.0220498) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.767332,0.00162342) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.737154,0.00401268) , 
1, 16.2199, 1, 0, 0.752803,0.00215134) , 
1, 11.2053, 1, 0, 0.770033,0.00690884) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.575631,0.00426339) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.501968,-0.0169176) , 
5, 105.489, 1, 0, 0.558629,-0.000200598) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.426482,-0.00717687) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.465839,-0.0334638) , 
8, 0.285087, 1, 0, 0.442162,-0.0156506) , 
9, 0.856828, 1, 0, 0.521868,-0.00507716) , 
1, 20.4007, 1, 0, 0.58275,-0.00213663) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.297612,0.0233815) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.172307,-0.0404519) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.284852,0.0120496) , 
9, -0.287508, 1, 0, 0.239306,-0.00370592) , 
10, -1.47975, 1, 0, 0.257016,0.0024006) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.300175,0.0329019) , 
10, 1.42803, 1, 0, 0.26737,0.007308) , 
1, 74.3395, 1, 0, 0.5,0.000341471)    );
  // itree = 22
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.560736,-0.0156634) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.670896,0.0153835) , 
9, -1.73941, 1, 0, 0.643982,0.00611649) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.564041,-0.0203841) , 
9, 1.99919, 1, 0, 0.630459,0.00202682) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.562124,-0.00790783) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.462029,-0.0478445) , 
5, 51.1795, 1, 0, 0.514294,-0.022829) , 
7, 2.73827, 1, 0, 0.600281,-0.00443028) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.412978,0.0381307) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.345587,0.00597074) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.514401,-0.0174534) , 
6, 114.494, 1, 0, 0.408816,-0.00224792) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.390231,0.0246637) , 
10, 1.73978, 1, 0, 0.40565,0.00128877) , 
10, -1.99843, 1, 0, 0.406501,0.00454788) , 
5, 80.1111, 1, 0, 0.5,0.000215927)    );
  // itree = 23
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.565652,-0.0389591) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.658453,0.0318412) , 
0, 52.0884, 1, 0, 0.613741,-0.00159583) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.693067,0.0302074) , 
0, 90.7577, 1, 0, 0.63522,0.00553863) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.511862,0.00389992) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.328587,-0.031593) , 
7, 3.2505, 1, 0, 0.491168,0.000193897) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.652213,0.0121134) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.467273,-0.0296303) , 
7, 1.66444, 1, 0, 0.528827,-0.0131846) , 
6, 89.9286, 1, 0, 0.502245,-0.00374137) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.177316,0.0298171) , 
5, 160.01, 1, 0, 0.459729,-0.00150796) , 
7, 1.32985, 1, 0, 0.5,0.000109075)    );
  // itree = 24
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.439907,-0.0012847) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.420458,0.0126308) , 
0, 75.3784, 1, 0, 0.433401,0.00246913) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.564559,-0.0157946) , 
9, -0.847353, 1, 0, 0.462684,-0.000936515) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.764759,0.0371231) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.596914,-0.000394389) , 
7, 1.70304, 1, 0, 0.670354,0.0115572) , 
9, -0.337515, 1, 0, 0.518028,0.00239306) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.552818,-0.0235002) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.61161,0.00656429) , 
8, 1.42797, 1, 0, 0.576611,-0.00886641) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.469029,-0.00893157) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.330885,-0.0076123) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.413038,0.0151345) , 
10, 0.285717, 1, 0, 0.384581,0.00552309) , 
8, -1.42812, 1, 0, 0.415375,0.00080706) , 
7, 1.79248, 1, 0, 0.476231,-0.00284403) , 
9, 0.285639, 1, 0, 0.5,0.000134174)    );
  // itree = 25
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.620037,0.0236143) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.635529,-0.0136524) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.380733,0.00412383) , 
1, 42.3043, 1, 0, 0.513901,-0.00455584) , 
3, 245.763, 1, 0, 0.553713,0.00500212) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.521833,0.0383949) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.49738,-0.00744557) , 
8, 0.804974, 1, 0, 0.510434,0.0129482) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.638187,0.00677453) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.452245,-0.00579406) , 
7, 1.32985, 1, 0, 0.495149,-0.00213241) , 
0, 36.9956, 1, 0, 0.497582,0.000268655) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.395609,-0.0279953) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.478199,0.00443673) , 
8, 0.337183, 1, 0, 0.436767,-0.00776869) , 
0, 106.91, 1, 0, 0.48875,-0.000898561) , 
8, -1.99909, 1, 0, 0.5,0.000123252)    );
  // itree = 26
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.627736,0.013931) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.535241,-0.0016725) , 
5, 52.8502, 1, 0, 0.561592,0.00244444) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.219458,-0.0142199) , 
1, 115.875, 1, 0, 0.527368,0.00137362) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.359963,0.00724614) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.4208,-0.0210031) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.509966,-0.00671243) , 
10, 1.58409, 1, 0, 0.472538,-0.00991986) , 
10, 0.286026, 1, 0, 0.444624,-0.00614849) , 
9, 1.01248, 1, 0, 0.50782,-0.000403458) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.419732,0.00710858) , 
9, 2.57039, 1, 0, 0.5,0.000120267)    );
  // itree = 27
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.532512,-0.00811916) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.525086,-0.0238118) , 
10, -2.62224, 1, 0, 0.528747,-0.0141149) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.680085,0.0149242) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.556456,-0.00518956) , 
10, 1.73955, 1, 0, 0.633856,0.00584457) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.584809,-0.0128152) , 
5, 65.5836, 1, 0, 0.621031,0.00156973) , 
10, -1.99911, 1, 0, 0.600281,-0.00195685) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.472178,0.0203277) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.376433,0.00497081) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.39199,-0.0259964) , 
0, 92.3181, 1, 0, 0.38123,-0.00287913) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.476114,0.0172188) , 
8, 1.47923, 1, 0, 0.395871,-0.00026977) , 
8, -1.42809, 1, 0, 0.406501,0.00206192) , 
5, 80.1111, 1, 0, 0.5,0.000122866)    );
  // itree = 28
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.549335,-0.000942685) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.499375,-0.0302497) , 
8, -2.20685, 1, 0, 0.52601,-0.011967) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.560447,0.0149022) , 
0, 70.1853, 1, 0, 0.538011,-0.00332676) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.448232,-0.0596414) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.328122,-0.00921635) , 
7, 1.80573, 1, 0, 0.370793,-0.0204036) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.55299,0.0183599) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.529049,-0.00694784) , 
2, 76.2887, 1, 0, 0.545608,0.00827108) , 
2, 38.3471, 1, 0, 0.493537,-0.000270031) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.432756,0.0184552) , 
2, 121.822, 1, 0, 0.486709,0.00130278) , 
8, -1.42792, 1, 0, 0.5,0.0001034)    );
  // itree = 29
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.485325,-0.0079207) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.342054,-0.0526679) , 
3, 328.737, 1, 0, 0.431703,-0.0184143) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.741244,0.0503412) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.607882,0.00988569) , 
7, 0.909142, 1, 0, 0.631978,0.0137147) , 
2, 38.3466, 1, 0, 0.576874,0.0048746) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.54816,-0.0205951) , 
2, 121.822, 1, 0, 0.574018,0.00267594) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.466037,0.0358169) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.439015,-0.00831714) , 
6, 21.1878, 1, 0, 0.44373,-0.000419741) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.32274,-0.0367726) , 
6, 77.2337, 1, 0, 0.418992,-0.00570864) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.325355,0.0233624) , 
2, 118.302, 1, 0, 0.407581,-0.00301955) , 
7, 2.26879, 1, 0, 0.5,0.000143034)    );
  // itree = 30
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.505358,-0.00769924) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.489008,0.0143135) , 
8, -0.649068, 1, 0, 0.497988,0.00125145) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.51945,-0.0209835) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.562129,-0.00380751) , 
0, 55.3962, 1, 0, 0.535959,-0.0119594) , 
8, 1.42797, 1, 0, 0.508277,-0.00232822) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.615903,0.0193083) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.375367,0.00829643) , 
7, 2.16606, 1, 0, 0.499738,0.0109762) , 
0, 85.9311, 1, 0, 0.507195,-0.000642109) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.530961,0.0147658) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.399642,0.00105265) , 
3, 354.066, 1, 0, 0.457218,0.00566936) , 
0, 106.908, 1, 0, 0.5,0.000266478)    );
  // itree = 31
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.645436,0.0243367) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.650913,-0.00275577) , 
6, 54.8555, 1, 0, 0.649755,0.0026603) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.554705,0.0189876) , 
3, 406.325, 1, 0, 0.630459,0.00552415) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.494962,-0.0227727) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.530945,-0.000368903) , 
10, -0.285588, 1, 0, 0.514294,-0.00909781) , 
7, 2.73827, 1, 0, 0.600281,0.00172563) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.673688,0.0152615) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.609951,-0.00138139) , 
5, 113.22, 1, 0, 0.648637,0.00722503) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.326716,-0.00898239) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.253428,0.0127102) , 
4, 619.418, 1, 0, 0.309713,-0.0034232) , 
1, 43.2261, 1, 0, 0.421365,8.46496e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.290558,-0.020172) , 
3, 627.438, 1, 0, 0.406501,-0.00132433) , 
5, 80.1111, 1, 0, 0.5,0.000147272)    );
  // itree = 32
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.497068,0.00579166) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.464978,0.0181183) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.480369,-0.00486831) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.496004,0.0100173) , 
2, 71.0712, 1, 0, 0.484201,-0.000876309) , 
6, 31.3246, 1, 0, 0.481359,0.00134437) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.597455,-0.00280168) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.511418,-0.0205041) , 
0, 79.4777, 1, 0, 0.547563,-0.00944092) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.556941,0.0132072) , 
10, 1.58324, 1, 0, 0.54981,-0.00451742) , 
6, 114.411, 1, 0, 0.500281,-0.000275975) , 
10, -2.57028, 1, 0, 0.5,0.000176364)    );
  // itree = 33
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.5278,-0.000787142) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.365359,-0.0176332) , 
3, 480.181, 1, 0, 0.50303,-0.002476) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.531708,0.0346447) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.443665,-0.00328751) , 
0, 57.9761, 1, 0, 0.490222,0.0122568) , 
8, -0.233693, 1, 0, 0.499554,0.00152184) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.43957,-0.0303355) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.553377,0.00333595) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.475535,-0.0183734) , 
9, 1.73966, 1, 0, 0.537492,-0.000957627) , 
9, -1.99912, 1, 0, 0.520443,-0.00505896) , 
8, 0.85679, 1, 0, 0.507195,-0.000885087) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.470231,0.0169899) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.447063,0.000723971) , 
8, -0.286191, 1, 0, 0.457218,0.00589589) , 
0, 106.908, 1, 0, 0.5,9.10899e-05)    );
  // itree = 34
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.611335,0.0140782) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.625576,-0.00870438) , 
8, -0.6496, 1, 0, 0.618822,0.00219565) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.629141,0.01987) , 
8, 1.42771, 1, 0, 0.621246,0.00570301) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.405214,-0.0146543) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.604339,0.0144105) , 
2, 40.0038, 1, 0, 0.529455,0.00313805) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.450487,-0.0234944) , 
6, 114.12, 1, 0, 0.511801,-0.00164868) , 
7, 1.58589, 1, 0, 0.574018,0.00253058) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.516349,0.0161367) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.422995,-0.00695249) , 
7, 2.86634, 1, 0, 0.467419,0.00338841) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.448169,-0.0384965) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.292668,0.0139545) , 
5, 101.767, 1, 0, 0.366306,-0.0105767) , 
6, 69.3458, 1, 0, 0.437289,-0.000773019) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.179426,-0.0376246) , 
3, 541.979, 1, 0, 0.407581,-0.00296454) , 
7, 2.26879, 1, 0, 0.5,8.67834e-05)    );
  // itree = 35
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.424511,-0.00701964) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.615555,0.0196207) , 
2, 40.4995, 1, 0, 0.507159,0.00383751) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.563449,-2.44819e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.592839,-0.0175707) , 
8, 1.42785, 1, 0, 0.571659,-0.00414705) , 
2, 58.8741, 1, 0, 0.533519,0.00057431) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.443569,-0.0188531) , 
3, 462.698, 1, 0, 0.524479,-0.000947632) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.455247,0.0222126) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.193505,0.00377803) , 
1, 74.3395, 1, 0, 0.310394,0.00883289) , 
4, 724.814, 1, 0, 0.5,0.000170687)    );
  // itree = 36
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.647756,-0.00729905) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.583997,0.0147477) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.691176,0.00247204) , 
2, 54.9328, 1, 0, 0.625587,0.0082805) , 
4, 270.459, 1, 0, 0.632694,0.00375812) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.49584,-0.010223) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.64962,0.0115748) , 
3, 292.941, 1, 0, 0.547901,-0.0024338) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.562799,-0.0202312) , 
8, 1.428, 1, 0, 0.552082,-0.00661715) , 
4, 336.374, 1, 0, 0.589484,-0.00180326) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.518706,-0.0116989) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.567166,0.0205395) , 
8, -1.48017, 1, 0, 0.550998,0.00732309) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.249319,-0.0330925) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.234173,-0.00129143) , 
3, 379.969, 1, 0, 0.23951,-0.00796678) , 
1, 58.4461, 1, 0, 0.386355,-0.000758676) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.359821,0.00326815) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.540714,0.0258435) , 
6, 91.1184, 1, 0, 0.454531,0.0129372) , 
8, 1.42787, 1, 0, 0.401481,0.00227999) , 
4, 439.962, 1, 0, 0.5,0.00014025)    );
  // itree = 37
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.62849,0.0162067) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.750147,0.000273629) , 
2, 44.2959, 1, 0, 0.700977,0.00543203) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.663328,-0.000154508) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.502534,-0.0260629) , 
5, 72.4897, 1, 0, 0.606229,-0.00817223) , 
7, 1.69174, 1, 0, 0.636481,-0.0038285) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.657208,-0.0188257) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.65423,0.00561332) , 
3, 419.808, 1, 0, 0.655644,-0.00458959) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.433203,0.030838) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.362302,-0.00279278) , 
3, 386.38, 1, 0, 0.390587,0.00911638) , 
7, 1.79932, 1, 0, 0.514922,0.00268706) , 
4, 420.473, 1, 0, 0.58275,-0.000948512) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.360168,0.0211034) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.230811,-0.0178557) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.155838,0.0201385) , 
7, 2.73145, 1, 0, 0.206883,-0.00455163) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.360872,0.0170817) , 
8, 1.47986, 1, 0, 0.243918,-0.000155751) , 
8, -1.42796, 1, 0, 0.26737,0.00328918) , 
1, 74.3395, 1, 0, 0.5,0.000163381)    );
  // itree = 38
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.622908,0.00131141) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.515738,0.021301) , 
4, 478.485, 1, 0, 0.609802,0.00316181) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.441844,-0.0137103) , 
4, 550.347, 1, 0, 0.583931,0.000943997) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.448693,-0.0124433) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.392476,0.0089004) , 
5, 123.031, 1, 0, 0.418281,-0.000935914) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.402468,-0.0145911) , 
8, 0.283645, 1, 0, 0.411414,-0.00528618) , 
5, 101.9, 1, 0, 0.537979,-0.000715464) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.246886,0.0242334) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.26517,4.47382e-05) , 
10, -0.285211, 1, 0, 0.258013,0.00493442) , 
5, 160.01, 1, 0, 0.5,5.09814e-05)    );
  // itree = 39
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.603921,-0.0212872) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.494181,0.00923703) , 
7, 2.13617, 1, 0, 0.55089,-0.0056584) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.261086,0.0197249) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.247037,0.006587) , 
9, -2.29181, 1, 0, 0.254207,0.008286) , 
1, 55.8254, 1, 0, 0.424614,0.000276693) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.471733,0.0139277) , 
9, -1.27217, 1, 0, 0.433367,0.00227772) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.542315,-0.0269771) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.68431,0.0286711) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.619672,-0.0146847) , 
0, 69.5254, 1, 0, 0.659586,0.00945509) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.459222,0.00193828) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.526094,-0.00815463) , 
8, 0.285613, 1, 0, 0.486792,-0.00177842) , 
9, 0.167695, 1, 0, 0.530653,0.00107301) , 
9, -0.493227, 1, 0, 0.531743,-0.00103729) , 
9, -0.856734, 1, 0, 0.5,3.23673e-05)    );
  // itree = 40
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.537656,-0.0216258) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.566886,0.00332759) , 
8, -1.42801, 1, 0, 0.559318,-0.00286827) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.650724,0.0210051) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.515115,-0.00132982) , 
7, 1.59008, 1, 0, 0.594443,0.00942461) , 
0, 63.9841, 1, 0, 0.56973,0.000775557) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.699687,0.0197143) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.492529,0.00412604) , 
7, 1.24859, 1, 0, 0.590433,0.00900567) , 
0, 92.3042, 1, 0, 0.574018,0.00248033) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.353021,-0.00780274) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.411256,0.0177965) , 
10, 0.856848, 1, 0, 0.37395,0.00138062) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.595584,4.80236e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.248699,-0.0388803) , 
1, 58.6319, 1, 0, 0.459991,-0.0102823) , 
2, 46.0501, 1, 0, 0.418992,-0.00472483) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.325355,0.0121387) , 
2, 118.302, 1, 0, 0.407581,-0.0030949) , 
7, 2.26879, 1, 0, 0.5,9.04523e-07)    );
  // itree = 41
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.573413,0.0129908) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.535744,0.00416483) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.554088,-0.0142841) , 
8, 2.1019, 1, 0, 0.537545,0.00166506) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.18701,-0.0184314) , 
1, 115.875, 1, 0, 0.49932,0.000453769) , 
8, -2.57023, 1, 0, 0.505897,0.00140808) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.448645,-0.0174909) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.476752,-0.00100077) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.538159,-0.012693) , 
6, 114.926, 1, 0, 0.494857,-0.00358148) , 
9, 0.285614, 1, 0, 0.48232,-0.00630677) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.516063,0.0172973) , 
10, 2.72613, 1, 0, 0.48871,-0.00235269) , 
10, 0.856806, 1, 0, 0.5,0.000117748)    );
  // itree = 42
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.674156,-0.00638142) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.534198,0.0044156) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.571247,-0.00878812) , 
2, 86.5088, 1, 0, 0.538984,0.00209449) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.449691,0.0025663) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.33487,-0.0191582) , 
6, 50.1508, 1, 0, 0.403446,-0.0042626) , 
7, 2.56762, 1, 0, 0.490436,-0.000182525) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.417937,0.0095487) , 
2, 118.81, 1, 0, 0.482822,0.000602812) , 
7, 0.860376, 1, 0, 0.5,0.000105861)    );
  // itree = 43
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.503791,0.0129327) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.621428,0.00871788) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.615295,-0.00510841) , 
10, -0.492729, 1, 0, 0.618789,0.00239674) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.53343,-0.00163244) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.310335,-0.0181863) , 
7, 2.26633, 1, 0, 0.437513,-0.0061293) , 
5, 61.1715, 1, 0, 0.498492,-0.00326126) , 
10, -2.56945, 1, 0, 0.499093,-0.00165438) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.47475,0.0087972) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.419068,-0.0111967) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.536982,0.00502571) , 
9, -2.20689, 1, 0, 0.516525,0.00177381) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.449032,-0.00903484) , 
9, 1.99915, 1, 0, 0.506597,0.000483002) , 
8, 0.337571, 1, 0, 0.500746,0.00149637) , 
8, -0.285563, 1, 0, 0.5,7.40435e-05)    );
  // itree = 44
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.60604,-0.0162147) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.756635,0.0164126) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.784362,0.00260244) , 
9, -0.285869, 1, 0, 0.771972,0.0066663) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.620126,-0.00821006) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.449028,0.0023413) , 
7, 1.79932, 1, 0, 0.51839,-0.00159208) , 
1, 20.3969, 1, 0, 0.580383,0.000426855) , 
8, -2.57022, 1, 0, 0.58275,-0.000889958) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.240456,0.0148323) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.2278,-0.0250318) , 
9, -1.84333, 1, 0, 0.234131,-0.00351639) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.307505,0.0321862) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.282645,-0.00304395) , 
10, 0.285717, 1, 0, 0.292847,0.00775138) , 
9, -0.285548, 1, 0, 0.26737,0.00286219) , 
1, 74.3395, 1, 0, 0.5,9.45375e-05)    );
  // itree = 45
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.430523,-0.0229049) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.500273,0.00295499) , 
0, 50.7428, 1, 0, 0.472074,-0.00606504) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.500352,0.00352133) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.576093,-0.0148858) , 
6, 126.266, 1, 0, 0.507623,0.00135024) , 
10, -1.42792, 1, 0, 0.498792,-0.000491806) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.604169,0.0168708) , 
6, 154.297, 1, 0, 0.507164,0.000549955) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.561311,-0.0139261) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.322047,0.00386653) , 
7, 2.12952, 1, 0, 0.439262,-0.00430094) , 
2, 121.822, 1, 0, 0.5,3.81903e-05)    );
  // itree = 46
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.565894,-0.00512308) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.41736,-0.0145004) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.482472,0.00803102) , 
9, -2.31063, 1, 0, 0.458283,-0.000167411) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.28977,0.0157065) , 
3, 360.87, 1, 0, 0.399433,0.00334604) , 
7, 1.3384, 1, 0, 0.433367,0.00178336) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.542315,-0.0137341) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.561238,0.000650664) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.20831,-0.020153) , 
1, 116.842, 1, 0, 0.526195,-0.00066636) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.577866,0.0115821) , 
8, 2.57032, 1, 0, 0.530653,0.00024853) , 
9, -0.493227, 1, 0, 0.531743,-0.000794407) , 
9, -0.856734, 1, 0, 0.5,3.73641e-05)    );
  // itree = 47
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.742294,0.00454599) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.733159,-0.0130057) , 
8, 1.99915, 1, 0, 0.740455,0.000716958) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.615916,-0.0254806) , 
1, 27.7549, 1, 0, 0.71214,-0.00447717) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.545932,0.0214984) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.516232,0.00447847) , 
10, 0.28566, 1, 0, 0.532716,0.0122397) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.324176,0.0209494) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.442543,-0.00974953) , 
9, -1.42786, 1, 0, 0.414192,-0.00238996) , 
1, 44.9182, 1, 0, 0.456118,0.00278506) , 
1, 33.8852, 1, 0, 0.58275,-0.000806942) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.331442,0.011592) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.253867,-0.0175246) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.151179,0.00451601) , 
7, 2.26502, 1, 0, 0.202447,-0.00456935) , 
8, -1.06459, 1, 0, 0.244597,-0.000208255) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.358551,0.0159686) , 
8, 1.42785, 1, 0, 0.26737,0.00237634) , 
1, 74.3395, 1, 0, 0.5,2.82925e-05)    );
  // itree = 48
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.686348,0.0143145) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.682006,-0.0110674) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.652289,0.00464371) , 
9, 0.285378, 1, 0, 0.669127,-0.00322339) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.387734,0.0237933) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.311782,-0.0114273) , 
9, 0.28585, 1, 0, 0.355713,0.00720583) , 
1, 58.0247, 1, 0, 0.560918,0.000377398) , 
7, 0.732327, 1, 0, 0.574018,0.00150258) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.608435,0.00503211) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.600185,0.0124979) , 
6, 40.686, 1, 0, 0.604383,0.00734596) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.415652,-0.011514) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.311438,0.00744435) , 
3, 342.144, 1, 0, 0.372583,-0.00328259) , 
4, 330.949, 1, 0, 0.437289,-0.000315672) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.179426,-0.0274863) , 
3, 541.979, 1, 0, 0.407581,-0.00191815) , 
7, 2.26879, 1, 0, 0.5,-1.86937e-05)    );
  // itree = 49
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.535463,-0.00309073) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.536994,0.024033) , 
0, 90.7899, 1, 0, 0.535579,-0.000830599) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.519032,0.0119981) , 
0, 104.302, 1, 0, 0.533519,0.000445685) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.443569,-0.0113673) , 
3, 462.698, 1, 0, 0.524479,-0.000477709) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.391582,0.0109541) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.227045,-0.00110921) , 
5, 162.176, 1, 0, 0.310394,0.00386203) , 
4, 724.814, 1, 0, 0.5,1.85031e-05)    );
   return;
};
 
// Clean up
inline void ReadBDT::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDT::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
